### ISSUE TITLE
Fix test-graphics `uniform_int_distribution` template parameter

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#1031]
The `test-graphics` project uses `uniform_int_distribution` with an unsupported type parameter of `uint8_t`:
```cpp
std::uniform_int_distribution<uint8_t> dist(0, 64);
```

----

With Visual Studio 2022 this leads to compile errors:
> C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\random(1908,5): error C2338: static_assert failed: 'invalid template argument for uniform_int_distribution: N4659 29.6.1.1 [rand.req.genl]/1e requires one of short, int, long, long long, unsigned short, unsigned int, unsigned long, or unsigned long long' (compiling source file TestGraphics.cpp) [C:\projects\nas2d-core\test-graphics\test-graphics.vcxproj]
  C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\14.32.31326\include\random(1908,5): error C2338: static_assert failed: 'note: char, signed char, unsigned char, char8_t, int8_t, and uint8_t are not allowed' (compiling source file TestGraphics.cpp) [C:\projects\nas2d-core\test-graphics\test-graphics.vcxproj]

Example logs:
https://ci.appveyor.com/project/OPU/nas2d-core/builds/44397422/job/squptfiuofhvar8w

----

Documentation does mention there is an `int` restriction on the `IntType` parameter:
https://en.cppreference.com/w/cpp/numeric/random/uniform_int_distribution
> `template< class IntType = int > class uniform_int_distribution;`
> ...
> Template parameters
> `IntType`    -    The result type generated by the generator. The effect is undefined if this is not one of `short`, `int`, `long`, `long long`, `unsigned short`, `unsigned int`, `unsigned long`, or `unsigned long long`.

**Comment by cugone** [comment]
As per STL, ["Because the Standard Says So"tm](https://www.youtube.com/watch?v=LDPMpc-ENqY&t=1268s) and just use `uniform_int_distribution<int>` and cast down to `uint8_t`
