### ISSUE TITLE
Run units tests on CI servers

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#110]
When the CI servers complete a build, they should then compile and run unit tests.

----

On Linux, the CircleCI config will need to be updated to run:
```
make check
```

Additionally, the CircleCI Dockerfile and container image may need to be updated to install Google Test.

----

On Windows, an MSVC project will need to be created for the unit tests (I have one already, but not yet tested). Current blocking issue: #101.

We will need to update the AppVeyor config file. It should run the executable produced by the test project. This can be done under the `test_script` section.
```
test_script:
  - cd %APPVEYOR_BUILD_FOLDER%\test
  - '%APPVEYOR_BUILD_FOLDER%\%PLATFORM%\%CONFIGURATION%\Test.exe'
```

AppVeyor should cache any NuGet packages, such as Google Test, so it doesn't waste time downloading and installing them for every build.
```
cache:
  # Cache Nuget packages in "packages" folder. Break cache if "packages.config" is updated.
  - packages -> **\packages.config
```

We may need to adjust the NuGet restore command so it restores packages for all projects in the solution:
```
before_build: nuget restore
```

**Comment by Brett208** [comment]
I noticed appveyor is not running the unit test project yet. I might be able to help out with this on Sunday or Monay. I think Unit Tests will be needed before all the filesystem changes make there way in.

**Comment by DanRStevens** [comment]
Tagging PR #146 as contributing to this issue. We now have unit tests running on Linux on CircleCI.

Issue #149 details the blocking issue to get unit tests running on MacOS on CircleCI.
