### ISSUE TITLE
Re-introduced audio bug

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#1103]
While experimenting with a Windows VM, I saw we may have re-introduced a bug loading the background music, as seen in:
- https://github.com/OutpostUniverse/OPHD/issues/219

I believe the bug may have been introduced by the removal of `vcpkg` install flags for `SDL2-mixer` here:
- 7405f6ec3bdd68df54c815bd40a3b073b45c7780
> `SDL2-mixer[libflac,libmodplug,libvorbis,mpg123,nativemidi,opusfile]`

Without those install flags, `vcpkg` may build a version of `SDL2-mixer` without support for the needed audio format.

Also, since we did some manual copying of DLLs related to that audio format, it's possible this bug may be hidden by old files still being around on developer's machines. It could be that cleaning the solution output folder may be needed to reproduce the error.

As I was working on other `vcpkg` changes at the time, it's possible my changes in progress were related, so this may need some verification.

This may be easier to address after switching to `vcpkg` Manifests (Issue #373).

**Comment by ldicker83** [comment]
Running in a VM often causes this as an invalid or null audio device is provided to SDL and NAS2D assumes with MixerSDL that it will always get a valid audio device. There used to be (may still exist) a Null Mixer that could be used in its place if an invalid audio mixer is provided.

**Comment by ldicker83** [comment]
Huh. Well then.

It's weird that it's a problem, I thought I'd tried a full build on a clean Windows install afterward. Will have to look further into it.

**Comment by DanRStevens** [comment]
So you may have been right about the VM lacking audio support. I double checked the VM, and it indeed lacked audio support. Adding audio hardware to the VM allowed the game to play sound.

----

There were a few interesting findings while looking into this. First off is that the `PostBuildEvent` used in OPHD to copy OGG related DLL files is no longer needed (PR https://github.com/OutpostUniverse/OPHD/pull/1392). It seems `vcpkg` will copy these files on it's own now.

----

Perhaps related to that, is the removal of the `vcpkg` flag for `libvorbis` when installing `sdl2-mixer`. It seems the core install of `sdl2-mixer` with `vcpkg` now includes support for OGG files.

----

The two flags that `vcpkg` removed for `sdl2-mixer` were:
- `libvorbis`
- `nativemidi`

Additionally, the `sdl2-mixer` package has a feature flag which was possibly added since then:
- `fluidsynth`

That means the following flags are potentially now usable:
`"features": ["opusfile", "mpg123", "libmodplug", "libflac", "fluidsynth"]`

----

To investigate, I branched off the point before the flags were removed, so I could run a CI build and see any errors concerning the flags. The flags were removed in commit 7405f6ec3bdd68df54c815bd40a3b073b45c7780, so need to branch off of commit 0c6a9a51f2f08c5e04df6df941e51f4867d51b18.

Errors were:
- Package names converted to lowercase (SDL -> sdl)
- Two errors about unsupported flags

Build Logs:
- https://github.com/lairworks/nas2d-core/actions/runs/5085908388/jobs/9139861943
  - > <unknown>:1:1: error: invalid character in package name (must be lowercase, digits, '-')
    on expression: SDL2
- https://github.com/lairworks/nas2d-core/actions/runs/5085917795/jobs/9139880463
  - > sdl2-mixer has no feature named nativemidi.
- https://github.com/lairworks/nas2d-core/actions/runs/5085928257/jobs/9139900389#step:1:36
  - > sdl2-mixer has no feature named libvorbis.

----

Not sure if we want to add back any extra feature flags. We probably don't need them, and only experimented with them to get OGG support. Though it may be useful to have that extra support if people want to mod the game.
