### ISSUE TITLE
Remove Resource names

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#1127]
The Resource classes have a name field, which is largely unused outside of the constructor, which it might be used as a file path to load data from disk. There doesn't seem to be a clear need to store this value, so perhaps we should conserve memory by removing the name fields.

There was some discussion of this in:
- https://github.com/lairworks/nas2d-core/pull/971#discussion_r687294516

**Comment by ldicker83** [comment]
Generally agreed. In the early development of NAS2D the 'name' field was used as a way to handle caching. This ended up using string comparisons which are expensive so there were other methods used instead. I'm in favor of dropping this field.
