### ISSUE TITLE
Remove Doxygen comments on private class fields

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#1128]
There are a few places in the code with Doxygen comments on private class fields. I'm not sure it really makes a whole lot of sense to use Doxygen for private fields. Perhaps they should be removed, or possibly converted to regular comments.

Related, if there was a need to comment the field, that may be a sign the field name was not very descriptive, so perhaps it should be renamed.

In other cases, comments may have simply restated variable names, in which case they should definitely be removed.

I noticed a few such removals suggested in PR #971.

**Comment by ldicker83** [comment]
I would convert to regular comments where they're helpful and dump the comments for comments that just restate the code. When I was first doing NAS2D I went a little nuts with commenting everything I could.
