### ISSUE TITLE
MacOS builds on CircleCI

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#123]
Currently the MacOS builds are being done on TravisCI. The experience on TravisCI has been kind of painful, with slow and often delayed builds. Additionally TravisCI doesn't seem to prioritize using updated compilers and standards. This may hold us back from using more modern compiler features.

We should check into doing MacOS builds on CircleCI. They may now offer MacOS as part of the free tier.

Reference:
https://circleci.com/docs/2.0/hello-world-macos/

**Comment by cugone** [comment]
@DanRStevens 
@ldicker83 

MacOS builds on CircleCI under lairworks have been approved. It's equivalent to the "Seed" plan but perpetually free and 1x concurrency.

**Comment by cugone** [comment]
@DanRStevens 
@ldicker83 

Good news:
 - MacOS builds are upwards of 30x faster on CircleCI.
 - Linux builds are 7x faster on CircleCI.

Bad news:
 - most recent stable xcode 10.2 still does not have full C++17 STL support as of its release 13 days ago.
   - They even *removed* the filesystem header and library support that existed in 10.2 beta 4!
   - https://forums.developer.apple.com/message/354637#354637
 - CircleCI currently only supports 10.0
 - It's entirely a waiting game for Apple to get their affairs in order then CircleCI to install the appropriate release.

The Internet is fed up with xcode being not-up-to-date and I can now see why so few cross-platform apps and games don't include MacOS in that list.
