### ISSUE TITLE
Fix Windows CI Builds

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#124]
Windows CI builds are currently failing on AppVeyor with:
```
"C:\projects\nas2d-core\proj\vc14\NAS2D.sln" (default target) (1) ->
"C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj" (default target) (2) ->
(ClCompile target) -> 
  ..\..\src\Filesystem.cpp(226): error C3861: 'PHYSFS_readBytes': identifier not found [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(267): error C2065: 'PHYSFS_Stat': undeclared identifier [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(267): error C2146: syntax error: missing ';' before identifier 'stat' [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(268): error C3861: 'PHYSFS_stat': identifier not found [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(268): error C2228: left of '.filetype' must have class/struct/union [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(268): error C2065: 'PHYSFS_FILETYPE_DIRECTORY': undeclared identifier [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(349): error C3861: 'PHYSFS_writeBytes': identifier not found [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(434): error C3861: 'PHYSFS_getLastErrorCode': identifier not found [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
  ..\..\src\Filesystem.cpp(434): error C3861: 'PHYSFS_getErrorByCode': identifier not found [C:\projects\nas2d-core\proj\vc14\NAS2D.vcxproj]
    4 Warning(s)
    9 Error(s)
```

This is caused by the recent PhysFS upgrade. The methods are available in the PhysFS 3.0.1 release which the code is now targetting. These methods are not available in the old PhysFS 2.0.3 package, which the CI build is still installing.

The changes were introduced during an AppVeyor service interruption due to a configuration problem on our end.

----

Long term, there seems to be some desire to move away from PhysFS, and towards the new native C++17 `<filesystem>` library. Due to slow adoption and old tools on some CI providers, such an upgrade is currently blocked.

For now, I think we should try to update the build dependencies on the AppVeyor build to use PhysFS 3.0.1.

The current config uses NuGet packages to install the dependencies. Currently NuGet repositories offer a PhysFS 2.0.3 package, but have no available PhysFS 3.0.1 package.

We could potentially try to put together a NuGet package for PhysFS 3.0.1. I believe the source code licensing should allow use to create such a package ourselves. It might also be of interest to the PhysFS author. Microsoft has documentation on [Creating NuGet packages](https://docs.microsoft.com/en-us/nuget/create-packages/creating-a-package).

Failing that, we could create a script to download the package on the AppVeyor build.

Alternatively, we could potentially rollback the changes for the PhysFS 3.0.1 upgrade. That may be difficult to undo the piecemeal updates though. There are likely quite a few dependent changes already merged on top of them by now.

**Comment by cugone** [comment]
The proposed changes in the vc17 project PR branch fix these issues. Both Linux and Windows compile clean with Windows only taking 45 seconds each on AppVeyor and Linux a little over 3 minutes for GCC and a little under 3 minutes for Clang on TravisCI. Apple doesn't play well with others and is the only hold out.

**Comment by DanRStevens** [comment]
PR #120 fixes the Windows build, but it breaks the MacOS build. As such, there's a blocking problem that prevents us from merging it in.

Additionally, PR #120 contained some big behavioural changes that are likely to break downstream projects, such as OPHD. Namely, handling of platform specific write folders. To complicate things, we have no testing in place to verify behavior before and after the changes.

To complicate things further, we can't really get proper before and after testing in place because as this Issue mentions, the Windows CI build is currently broken.

Additionally, PR #120 has grown rather large and hard to review. It's unlikely we'll be able to just merge it in with it's current form.

----

In terms of the proposal above, updating the PhysFS package (assuming an updated package exists or were created), would be about a 1 line source change, and very easy to verify. It would also only impact the Windows platform, so no chance of breaking builds on other platforms.

It would also unstick development of unit tests that could be used to verify the changes you are proposing in #120.
