### ISSUE TITLE
Add VS2019 project files

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#134]
VS2019 had its General Availability release (full release) last week.
I know AppVeyor has an RC build environment of it but it might be a good idea to at least have the project sitting around for other devs and when AppVeyor updates its Build Environments.

**Comment by DanRStevens** [comment]
This very exciting news.

I think my preference would be to wait a little bit before upgrading. One reason is that we may update project file settings in the meantime, so if we only have one set of project files, it would reduce the maintenance burden. In particular, I do actually want to go over the project files and try to cleanup and simplify things. As such, I think upgrades should be done after any cleanup, so they may take advantage of an already cleaned up project file to upgrade from.

The other thought I have, is I'd like to wait until AppVeyor provides an upgraded environment to run builds from, and to also give developers a chance to upgrade on their own. At that time, it would be nice to switch completely to a new project file format, again reducing the maintenance burden.

My thought is to defer on this. Hopefully not for too long though.

**Comment by Brett208** [comment]
Agreed that it is better to wait a bit unless we really need something in VS2019. There will likely be bugs with the new toolset that surface in various ways in different dependencies. I like letting others hunt through these than dealing with them myself if it isn't needed. Also as Dan stated, waiting a bit for other applications to support 2019 more fully first.

**Comment by cugone** [comment]
@Brett208 

This is true.

I have to wait for Unreal to support VS2019 and Visual Assist needs to push an update to fix an improper loading error for VA Build 2324 when run in VS2019.

This is why I always keep the previous version of VS around when a new one comes out since Microsoft has made them able to be installed side-by-side.

**Comment by ldicker83** [comment]
I've been working on this one since yesterday -- the only thing blocking me now is how to add vcpkg to appveyor for Windows builds -- nuget doesn't have the latest versions of PhysFS or GLEW but vcpkg does. Once I can tweak the appveyor build environment to also pull GLEW I'll be able to push the VS2019 solution.

**Comment by ldicker83** [comment]
Was having difficulty with the nuget packages. @cugone was able to resolve. Deleted my original branch and merged in his.

Appveyor still has 'preview' builds of VS2019 but the 'non preview' was only released sometime this week. I say we move forward with VS2019. We can hang onto VS2017 if anybody has a strong desire but I don't really see the point.

In the mean time I'll consider this issue closed.
