### ISSUE TITLE
Drop travis CI

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#137]
- Circle CI builds take about 1 minute per platform
 - AppVeyor builds take about 45 seconds per platform
 - TravisCI builds take 3-6 minutes or more per platform.
 - TravisCI's build environment is way more out of date than CircleCI and AppVeyor.

In addition TravisCI's cache mechanism is completely different from CircleCI and is soley based on branch, language, and compiler instead of the much more useful directory paths.

https://docs.travis-ci.com/user/caching/

 > - There is one cache per branch and language version/ compiler version/ JDK version/ Gemfile location/ etc.
> - Only modifications made to the cached directories from normal pushes are stored.

**Comment by DanRStevens** [comment]
I would like to eventually drop TravisCI. It's slow and more difficult to maintain. However, it does have automatic setup for Pull Request builds. A PR build is what you'd get after merging the branch to master, which is important to check in cases where master has received merges from other independent branches, and so has diverged from the branch point of the current branch.

We could potentially do the PR builds from CircleCI for Linux and MacOS, though we'd need to manually set that up over there. I'm not currently sure of the details. I had in the past looked into how to get a PR build checkout. I never really investigated if anything special needed to be done for notify hooks.

AppVeyor does automatic PR builds for Windows.

----

We could potentially disable the branch builds (aka push builds) for TravisCI. That is now sufficiently covered by CircleCI.

Curiously, I noticed the branch builds were not running when I spot checked a few recent PRs. Might be an account/security related cause. It could be that only PR builds run when the push comes from a user account outside the organization.

**Comment by ldicker83** [comment]
Should we move forward with removing TravisCI? Seems all the rest are working.

**Comment by DanRStevens** [comment]
Not yet. TravisCI is still doing the PR builds, which CircleCI hasn't yet been configured to do.

There is also the issue of building with both GCC and Clang, which I don't think was sorted out yet.

We're close, but not quite there yet.

**Comment by ldicker83** [comment]
Bleh. Welp, I'll leave it alone then for now.

**Comment by DanRStevens** [comment]
I noticed we are no longer building on TravisCI, so I guess it was dropped at some point. We still have the `.travis.yml` file present though. Perhaps we should remove that file and close this issue.

**Comment by DanRStevens** [comment]
For reference, I stumbled upon this comment about TravisCI being turned off:
https://github.com/lairworks/nas2d-core/pull/159#issuecomment-488162841
