### ISSUE TITLE
Install Google Test to MacOS environment (CircleCI)

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#149]
We should install Google Test to the MacOS build environment on CircleCI.

It would be nice if there was a `brew` command to install it, though a quick Google search suggests that there isn't. Maybe there is another package manager that offers and easy to install way.

If not, a source install can be done, with caching of the build output. We probably don't need to cache the source, just the build output.

To obtain the source, perhaps a `git checkout` can be done from GitHub, or a `wget` or `curl` of an archive. We should probably use a tagged release for this, rather than `HEAD`.

The `makefile` provides some hints on how you might build the project once the source is already downloaded:
```
GTESTSRCDIR := /usr/src/gtest/
GMOCKSRCDIR := /usr/src/gmock/
GTESTDIR := $(BUILDDIR)/gtest
GMOCKDIR := $(BUILDDIR)/gmock

gtest:
	mkdir -p $(GTESTDIR)
	cd $(GTESTDIR) && cmake -DCMAKE_CXX="$(CXX)" -DCMAKE_CXX_FLAGS="-std=c++17" $(GTESTSRCDIR)
	make -C $(GTESTDIR)

gmock:
	mkdir -p $(GMOCKDIR)
	cd $(GMOCKDIR) && cmake -DCMAKE_CXX="$(CXX)" -DCMAKE_CXX_FLAGS="-std=c++17" $(GMOCKSRCDIR)
	make -C $(GMOCKDIR)
```

Note that modern packages of Google Test combine both GTest and GMock, and they should both build with a single build command. The separation above is largely to support older packages used on the TravisCI platform. A modern package has a top level CMake file and looks more like:
`/usr/src/googletest/`:
```
CMakeLists.txt
googlemock/
googletest/
```

----

@cugone: This might be a good task for you.

**Comment by cugone** [comment]
What about adding the source directly to the project and just building it as part of building the engine itself?

**Comment by DanRStevens** [comment]
My recommendation is a short download / build / install script.

For Google Test, the code can be downloaded with a `git clone` (preferably using a tagged release), or by downloading and unpacking one of the release packages (using `curl` piped into `tar`):
https://github.com/google/googletest/releases

----

Maybe a year ago, I did a bunch of reading on the recommended ways to install dependencies. There seemed to be 3 main suggestions, which tended to fall in the following order of priority:
1) Package management system
2) Download / build / install / setup script
3) Direct inclusion in the repository

The first is the simplest and easiest to maintain by far. Conveniently it relies on the work of others, but requires other people to have already done the work.

The second option means doing the required scripting work yourself. Sometimes a bit painful if you're not familiar with scripting package installation, but generally a very workable and satisfying solution when it's done.

The third option is mainly useful if obtaining the source is inherently difficult, such as for a closed source project, paid only access, or request only access were the author sends it to you specifically. Direct inclusion tends to bloat the repository though, and generally requires the most maintenance burden when upgrading dependencies. That last point about upgrades is easy to dismiss as trivial, though in reality it's never as simple as the previous two options.

That that the third option doesn't actually address building or installing the package, just making the source code available. You'd still have to do much of option 2 to build the source, unless it's a dependency that doesn't require any kind of build or install step, such as a header only library.

Sometimes I see people using the third option when their scripting skills are too weak for option 2, and there is no suitable option 1. I'd be hesitant to recommend this though.

----

It would be good to cache the Google Test compile. Google Test isn't a large project, so building with the main project shouldn't add much to compile time, but then NAS2D isn't very large either, so it'll probably be about a 25% increase in build time if it's not cached.

----

Rough plan:
```
curl packageUrl | tar --unpackOptions  # Download source
cd unpackedFolder && cmake --cmakeOptions && make  # Build the package
cp unpackedFolder/lib*.a /usr/lib/  # Copy library files to global install location
```

----

@cugone: If you have no interest, then don't worry about it. I just thought I'd suggest it as it seemed related to some of your previous work.

**Comment by cugone** [comment]
I don't have an interest at all at becoming a build manager, no, doubly so for macOSX (or any mac) as A. I do not have a mac available to test any of it on prior to pushing to the repo; and B. as previously stated, I abhor macs.

The related prior work was just to get circleCI working because it was a better solution than TravisCI.

**Comment by DanRStevens** [comment]
Perhaps just wishful thinking on my part. I don't own a Mac either. :wink:
