### ISSUE TITLE
Get working `<filesystem>` library on MacOS

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#152]
Some recent updates were blocked by access to the `<filesystem>` library on the MacOS platform. MacOS has added support for C++17 _language features_, but still lags in support of C++17 _standard library features_.

The following may provide some ways to work around this problem:
https://stackoverflow.com/questions/49577343/filesystem-with-c17-doesnt-work-on-my-mac-os-x-high-sierra

It may be possible to `brew install clang`, and with Clang 7.0.1+ compile with `<filesystem>` support. It requires linking with `-lc++fs`.

----

We could also potentially substitute with Boost's filesystem library, which the standard library version derives from. In that case, it would be possible to `brew install boost`. Some source file updates would be required to allow it to fallback on the Boost version.

To fallback on earlier library support, the `__cpp_lib_filesystem`, `__cpp_lib_experimental_filesystem`, or the `__has_include` [feature detects](https://en.cppreference.com/w/User:D41D8CD98F/feature_testing_macros) could be used:
```cpp
#ifdef __cpp_lib_filesystem
#include <filesystem>
namespace fs = std::filesystem;
#elif __cpp_lib_experimental_filesystem
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;
#else
#include <boost/filesystem>
namespace fs = boost::filesystem;
#endif
```

Some caution is needed though as there are slight incompatibilities between the different versions of the library.

**Comment by ldicker83** [comment]
Eeesh, Boost is huge. What about the one I suggested: https://github.com/gulrak/filesystem

It uses a BSD 3-clause license which should be compatible with the NAS2D zlib license. Not sure if it's easy to script pulling a tagged git repository specifically for macOS X or if we should just use Boost.

**Comment by DanRStevens** [comment]
We could set additional fallbacks:
```cpp
#ifdef __cpp_lib_filesystem
#include <filesystem>
namespace fs = std::filesystem;
#elif __cpp_lib_experimental_filesystem
#include <experimental/filesystem>
namespace fs = std::experimental::filesystem;
#elif __has_include(<boost/filesystem>)
#include <boost/filesystem>
namespace fs = boost::filesystem;
#elif __has_include(<ghc/filesystem>)
#include <ghc/filesystem>
namespace fs = ghc::filesystem;
#else
#error "No <filesystem> support"
#endif
```

It would be up to the environment maintainer to choose which version of the library they want to install.

Of course, with the above code, the priority order is fixed. That might not be such a bad thing though, if the built in libraries are selected first, or preference is given to the boost library, which the official ones derive from.

**Comment by ldicker83** [comment]
I'd like to get this tested with macOS sooner rather than later and start moving forward with the filesystem rewrite.

I'm going to try pulling @cugone 's modifications if they're still available through his fork and start working with them locally. The rewrite wasn't bad but it felt like it was somewhat incomplete. Either way, having that as a working branch on the main project repository I think is a good thing.

**Comment by cugone** [comment]
@ldicker83 

Unfortunately I nuked the branch. Here are github's backups:  

https://github.com/cugone/nas2d-core/blob/62aca61cab552038caf795e55982456a600413f0/include/NAS2D/Filesystem.h

https://github.com/cugone/nas2d-core/blob/87d418bdfaa93e206a02739843f8ed8192497123/src/Filesystem.cpp

You'll need to manually fixup the use of custom preproc defines before it'll compile though.

**Comment by DanRStevens** [comment]
Yes, I think we should try to hang on to that work. We seem to have gotten much closer to being able to incorporate it in a stable controlled way.

One point of interest for me, I remember liking the `forEachFileInFolders` part. I was thinking that would be a nice addition. A few weeks ago, when it looked like there were blocking problems, I found myself wondering if a PhysFS version of that could be written so we'd have the functionality early. Maybe no point in such a rewrite now.

----

We now have units tests running on CI for all 3 platforms. I think our focus should now be on writing unit tests to cover the filesystem code. That way we can verify the filesystem interface is maintained through the replacement.

Of course that means we need to get really specific on what the filesystem interface really is, and on how to write good unit tests for that.

**Comment by DanRStevens** [comment]
As per https://github.com/lairworks/nas2d-core/issues/179#issuecomment-566124388, MacOS should now have `<filesystem>` support. That may render much of the above discussion obsolete.

As a side note, the Mingw compiler still has lacking support for `<filesystem>`, so the above feature detect include with support for `<experimental/filesystem>` may still help portability.
