### ISSUE TITLE
Create a NAS2D Project in Projects tab

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#168]
Creating a project in the Projects tab will allow for easier creation and assigning of tasks and let others know who has what task(s) currently checked out so there is no duplicate work being done.

More Info:
https://help.github.com/en/articles/about-project-boards

**Comment by DanRStevens** [comment]
Ahh yes, I've ignored that tab for far too long. I suppose it's time.

Guess I have a bit of reading and experimenting to do.

**Comment by ldicker83** [comment]
Speaking of, I need to decide which PR to merge and which to reject (between 167 and 169). They're basically the same changes.

**Comment by DanRStevens** [comment]
You mean #166 and #167, which both deal with Mixer. Not to be confused with #169, which deals with Renderer.

**Comment by DanRStevens** [comment]
@cugone, are you able to assign an issue to yourself? There's a link for that on the top right of each Issue page. I'm not certain if you would have access to it though, as you've never been added to the LairWorks organization. That might be what we're really after to avoid duplicate effort.

The Project tab is also a good idea. We should probably try using more of these GitHub features. I suspect the Project tab is more useful when you have a large backlog of tasks, with milestones for each, which you want to distribute among a team of programmers. I haven't used it yet, so it's hard to say. We're probably at a point where we can start making use of something like that.

**Comment by cugone** [comment]
@DanRStevens 

> ...are you able to assign an issue to yourself?

No I can not as I am a lowly contributor not a collaborator nor an org member. I would not have write access without manual intervention: https://help.github.com/en/articles/project-board-permissions-for-an-organization.

**Comment by ldicker83** [comment]
I've updated this so that you're now a collaborator. I haven't done much with GitHub projects but willing to learn and see how effective it is. Almost all of my development efforts on GitHub have been a sort of lone wolf type of deal.

**Comment by DanRStevens** [comment]
I assume with collaborator status, you can now create branches and PR right from the original repository, and don't need to work from a fork of it. That might make pulling in updates changes slightly easier.

----

Well, the project board is created, so I guess this should be closed now.

We haven't yet used it really, nor learned how to use it, though that seems to be another matter.
