### ISSUE TITLE
Add Unit Tests to cover the Filesystem interface

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#175]
Unit tests should be added to cover the Filesystem interface. This will help verify planned changes to this component.

Additionally, it may help us to clarify what we really need from the interface to this component. Some methods may be rather specific to the underlying implementation, rather than a truly useful high level abstraction.

After tests are written, we may want a discussion as to what the tests should be.

**Comment by cugone** [comment]
Don't forget to add tasks to the project board. :)
