### ISSUE TITLE
Review Filesystem requirements and design

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#179]
We should take a look at what we really need from the Filesystem component, and if the current design meets those well.

One consideration is that some aspects of the Filesystem interface seem tied to exposing specifics of the current PhysFS implementation, rather than any particular high level interface. Others may be in contrast with common practice in other libraries such as `<filesystem>`, and may be worth looking into why.

One aspect mentioned by @cugone is the `extension` method, which returns extensions without the leading ".". This means there is no way to distinguish between the following two cases:
```cpp
extension("file.");  // Currently "", perhaps should be "."
extension("file");  // Currently "", perhaps should be ""
```

We may also want to handle extensions used in directory names:
```cpp
extension("DirName.ext/");  // Currently "ext/", perhaps should be ".ext"
```

One thought I had, is perhaps splitting out virtual filesystem methods from real filesystem methods. An example of a virtual filesystem concern is to restrict writing to a specific data folder, or finding static game assets packaged with the executable file. An example of a real filesystem concern is finding the user folder, or the app specific write folder, which would then be used as a mount point for the virtual filesystem.

----

Tagging Issue #175 as related, and PR #176 as related.
Edit: Tagging Issue #118 as related.

**Comment by ldicker83** [comment]
The original intention of the Filesystem object was to provide a platform independent way of reading from archive files that was transparent to the end user of NAS2D. Basically ,it allowed packing all data assets into a ZIP file (or similar) and reading from that. This was especially important at the time that NAS2D/The Legend of Mazzeroth was being developed (circa early 2008) as C++ had not really been updated, it was messy when dealing with filesystem code, etc.

With the recent updates to C++, filesystem operations are basically built into the language (with macOS continuing to be difficult). It basically means that using an external C-based library for filesystem operations is no longer necessary. Reading out of archive files is getting less and less important so at this point it's more about providing a consistent interface. But, seeing as C++17 effectively solved that problem the Filesystem object may now be superfluous.

The only advantage at this point is seamlessly reading from zip archives. Still though, that's more of a 'nice to have' type of deal and seems like it would be better for the end user to make said decisions to use the library. By not using it it would remove yet another dependency (zlib).

So I can be persuaded either way. Filesystem did what it needed to do until C++ caught up and provided a standard way to deal with the native filesystem. Pulling it would mean that all NAS2D based projects would need to deal with files directly but I don't really see that as a problem. At the same time, having the filesystem object does provide a simpler interface at the cost of overhead and unnecessary hand holding.

**Comment by ldicker83** [comment]
Any thoughts on this?

As a side note, this would require some internal changes to some of the asset loading as it does depend on the Filesystem object, so it's a bit of a project.

**Comment by DanRStevens** [comment]
You make a good point in that our need for this layer has been greatly reduced, and can be reduced further.

I do like being able to use built in C++ language features whenever possible. In this case, the lag with MacOS support is a bit annoying though. I'd be tempted to leave in a small compatibility layer until that catches up.

----

What about features such as having a virtual filesystem? That's something the built in filesystem library doesn't attempt to address. We don't really need this, but some aspects of it may be nice. Some aspects of the asset loading currently depend on this in small and not particularly important ways.

Determining a platforms specific user write folder is another thing which isn't handled by the built in filesystem library. We do need that, for things like saved games, and it is rather fundamental to cross platform game development.

Perhaps the previous code can be replaced / broken up into smaller new components with a tighter focus.

**Comment by cugone** [comment]
@ldicker83 
@DanRStevens 

Good news! Apple Clang finally has actual `<filesystem>` support for Xcode 11.1/macOS 10.15 and up.

https://developer.apple.com/documentation/xcode_release_notes/xcode_11_release_notes

 - `Clang now supports the C++17 <filesystem> library for iOS 13, macOS 10.15, watchOS 6, and tvOS 13. (50988273)`

AND CircleCI has up-to-date support! https://circleci.com/docs/2.0/testing-ios/#supported-xcode-versions


This means that the process of migrating towards universal `<filesystem>` use with a replacement for the old PhysFS can begin!

**Comment by DanRStevens** [comment]
That's very good news. I'd love to be able to use `<filesystem>` much more freely.

Just a quick reminder though that `<filesystem>` is not a complete replacement for everything the old `Filesystem` class handled. In particular, the platform specific write folders (issue #212) is not handled by `<filesystem>`, and so we'd need a small bit of custom code to manage that. We should write that code first, so the transition can be done smoothly.

There are also some virtual filesystem semantics handled by the old `Filesystem` class. That feature maps fixed resource names to static data distributed alongside the exe or packed into archives. We could either re-implement the support without PhysFS, or transition to not use virtual filesystem semantics. If we transition to not use virtual filesystem semantics, that will affect downstream projects, and so they'll need some kind of update, and it'll dump more responsibility on them. I remain a little uncertain how we would do that smoothly. My gut feeling is that retaining some degree of virtual filesystem semantics would be a smoother transition path. I don't believe it would be a whole lot of code to maintain virtual filesystem semantics, and I do think that would ease the burden on downstream projects.

I guess what I envision is that we'll still have a `Filesystem` class, but it will be implemented internally based on `<filesystem>` instead of PhysFS. Do that will require a bit of custom code to handle platform specific write folders, and abstracting away the actual filesystem location and reading data from either disk or archive files.

**Comment by cugone** [comment]
At the very least keeping the original interface and then just converting the implementation to use `<filesystem>` as much as possible as well as not deleting functions, only adding, would be a start and downstream projects wouldn't even know the difference.

**Comment by DanRStevens** [comment]
I agree. That's probably a good way to start.

I'm sort of hoping that can be done through a series of small changes. I kind of want to keep change sets down to about one screen of code until we get a bit more momentum going again.

**Comment by DanRStevens** [comment]
This issue has gotten a bit unfocused. The discussion part seems to have come to an end. Issue #379 lays out the current roadmap for `Filesystem` changes.

The only remaining actionable item is the change of specification for the `extension` method. I checked OPHD and op2-landlord, and neither project uses this function. That means we are free to proceed with changing specifications as if it were an internal concern.

Within NAS2D the only use is actually the unit test code.

I'm guessing code refactoring removed all previous uses of this method.
