### ISSUE TITLE
Consider splitting Common apart

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#181]
Consider splitting `common.h` and `common.cpp` into separate files and namespaces. It currently contains both math-y and string-y functions and even the entire primitives header. If I only want math functions, I also unintentionally get a bunch of unrelated string operations and vice-versa.

Later if various random number, intersection test, floating-point equivalency test, (math) vector operation, range map, interpolation, conversion, noise, etc, functions are added (hint :) ) the string functions will get lost.

It would be much more readable and comprehensible to move all the math functions to something like a MathUtils header and namespace and similar with the string functions. It also avoids pulling in code you don't use and by extension reduces compile times. Right now, if I need the string functions and someone changes the math functions my code gets recompiled.

**Comment by DanRStevens** [comment]
I agree with splitting Common.h into smaller more targeted header files.

I don't know if we need to add more namespaces. C++ usually has a pretty flat namespace structure. Usually it's one namespace per library. The C++ namespace mechanism isn't really a full proper module system, so it doesn't tend to get the same nesting that a C# project would get.

**Comment by cugone** [comment]
Namespaces prevent collisions with standard and common (hah) function/object names. One perfect example is `clamp`, you have one, the standard has one (that really should be fixed...); Qualifying names with namespaces reduces collisions and unintentionally using the wrong function.

**Comment by DanRStevens** [comment]
We should probably use the `clamp` version from the standard. Though to be pedantic, the standard has [`std::clamp`](https://en.cppreference.com/w/cpp/algorithm/clamp). Standard library methods are already in a namespace to prevent this sort of collision.

Usually C++ projects use one namespace per library. Even with such minimalism, it's enough to avoid problems, unless you have duplicate names in the same library. It would probably be bad practice if you had duplicate names in the same library.

**Comment by ldicker83** [comment]
I would agree with removing NAS2D::clamp in favor of std::clamp for the sake of brevity and to avoid code duplication.

As for splitting apart Common, I would also agree. It started off as a set of basic utility type functions and has grown over time to include a lot.

**Comment by ldicker83** [comment]
As far as the namespaces go, I'm okay with using nested namespaces. I do it with the XML stuff. Just made sense to have it in its own namespace. I would think the same could be done with the utility functions. E.g.,:

namespace NAS2D::String and NAS2D::Math. Undecided on others but this is one I want to have fleshed out and ready for milestone 1.6.0.

**Comment by DanRStevens** [comment]
The XML stuff is 3rd party code, and already an independent library. In that case, I think it makes a little more sense to have an extra namespace.

I don't think the same needs to be done for all the different little sections of NAS2D. That just seems like overkill. As everything is already in the NAS2D namespace, you'd only really be protecting against name collisions within the library itself.

I think end users would thank you if they didn't have to code (exaggerated) examples like:
`NAS2D::String::CaseInsensitive::English::Inflexions::pluralOf(tableName)`

**Comment by cugone** [comment]
I generally see namespaces used to gather and collect like-minded free functions. String-operations: `StringUtils`, Math operations: `MathUtils`, Easing functions: `MathUtils::Easing` (nested because "mathy" and there are a lot of them so as to not crowed the other math functions.) Internal to `.cpp` (or even function level) namespace aliasing can mitigate the longer-nested ones.

**Comment by DanRStevens** [comment]
Namespaces can be re-opened and modified. You can split a namespace among multiple files. In fact, we already do, in that both the header file and the implementation file have to (re)open the same namespace. At another level, the whole library already shares the NAS2D namespace.

----

It sounds to me what you'd really like is a proper [module](https://clang.llvm.org/docs/Modules.html) system. That hasn't quite made it into C++ yet, though there has been a lot of work on the idea as a standards proposal.

Until then, we're stuck with namespaces, which simply just aren't proper modules. You can try to hack it, but the result won't be very good. That's part of the reason why people use a largely flat namespace hierarchy. The benefits just aren't really there in any sort of tangible way.

In terms of established practice, it's common to use a fairly flat namespace model. The C++ standard library is quite large (understatement), though the vast majority of it exists directly in the same `std` namespace. Sure, there are a few sub-namespaces, such as `filesystem`, and [`std::string_literals`](https://en.cppreference.com/w/cpp/string/basic_string/operator%22%22s), but those exceptions are few and far between, and often the result of special considerations.

As for creating aliases with `using`, that's generally discouraged, which means you're often stuck typing out the full namespace for every name you import.

----

I would like to break things up into sections, but in terms of the C++ language support with namespaces, there's just no compelling reason for deep nesting. It does however leave you paying a price.

My recommendation is to split the files, but stick to a flat namespace using just `NAS2D`.

**Comment by DanRStevens** [comment]
Looks like this was closed by #218.
