### ISSUE TITLE
Replace boolean parameters with extra string methods

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#199]
The following methods have a boolean flag parameter:
```cpp
std::vector<std::string> split(std::string str, char delim = ',', bool skip_empty = true);
std::string join(std::vector<std::string> strs, char delim, bool skip_empty = true);
std::string join(std::vector<std::string> strs, bool skip_empty = true);
```

The problem with `bool` parameters, is they are not very self documenting at the point of call. In particular, for a call such as the following, there's no way for someone to infer what the boolean does without reading additional documentation, or finding the method definition:
```cpp
auto result = split(string, ',', false);
```

Instead of using boolean flag parameters, two versions of the methods can be provided. For instance, there might be a `split`, and `splitStripEmpty`, or `join`, and `joinSkipEmpty`. This would provide much better documentation at the point of call about what is intended.

As a side benefit, it also allows lifting the boolean checks out of the inner loops of the above methods, and effectively make them static decisions at the point of call. That should result in more optimized code.

**Comment by cugone** [comment]
One other option to consider is a using a scoped enum:

    enum class StringOptions
    {
        SkipEmpty
        PreserveEmpty
        //...
    };
    
    //Declarations
    std::vector<std::string> split(std::string str, char delim = ',', const StringOptions& opts);
    std::string join(std::vector<std::string> strs, char delim, const StringOptions& opts);
    std::string join(std::vector<std::string> strs, const StringOptions& opts);
    
    //Calls
    split(string, ',', StringOptions::PreserveEmpty);
    join(strings, ',', StringOptions::SkipEmpty);
    join(strings, StringOptions::PreserveEmpty);

It self-documents at both the call site and declaration, avoids duplicating code with another function definition and the implementation doesn't have to change that much.

**Comment by DanRStevens** [comment]
Yes, a scoped enum is more self documenting. However, if the enum values are going to be hardcoded constants, you're pushing a compile time decision into a runtime check.

Consider the difference between the following:

Original:
```cpp
while (std::getline(ss, curString, delim)) {
	if (skip_empty && curString.empty()) { continue; }
	result.push_back(curString);
}
```

Branch lifted out of inner loop:
```cpp
if (skip_empty) {
	while (std::getline(ss, curString, delim)) {
		if (curString.empty()) { continue; }
		result.push_back(curString);
	}
} else {
	while (std::getline(ss, curString, delim)) {
		result.push_back(curString);
	}
}
```

Branch lifted out of inner function:
```cpp
if (skip_empty) {
  splitSkipEmpty(string);
} else {
  split(string);
}
```

In the last case, if the `skip_empty` value is likely to be a hardcoded constant, then it doesn't need to be there, nor does the whole `if`/`else` block.

For methods like this, that value is almost always going to be a hardcoded constant.

----

This is like how in the file access API, the `seek` method was designed to take a direction parameter, so you could seek from the beginning of the file, the current position in the file, or the end of the file. This was almost certainly a mistaken design. The decision as to how seeking should be done was very nearly always a compile time decision.

**Comment by cugone** [comment]
Hmm...now that I see it, that's actually a nice solution. Skipping empty entries is dependent on the data and for a mature dataset that is unlikely to change so can be a hard-coded design.
