### ISSUE TITLE
Fix Warning C4706 - Using result of assignment as condition

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#201]
A recent change has created a lot of compiler warnings:
```cpp
src/Configuration.cpp:219:18: warning: using the result of an assignment as a
      condition without parentheses [-Wparentheses]
                while (xmlNode = root->iterateChildren(xmlNode)) // warn...
                       ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

This is the result of many lines similar to the following:
```cpp
		while (xmlNode = root->iterateChildren(xmlNode)) // warning C4706: intended
```

Previously, these lines had an extra set of parenthesis which were silencing the warning:
```cpp
		while ((xmlNode = root->iterateChildren(xmlNode)))
```

----

It may be possible to provide a bit of support code to enable [range-based for loops](https://en.cppreference.com/w/cpp/language/range-for) to replace those `while` loops. In particular, the existence of `begin` and `end` methods can allow the compiler to generate a range-based for loop.

There are two ways to use `begin`/`end`. Either as member methods on a class, or as free floating methods which take an iterable parameter. If we wish to avoid modifying existing classes (perhaps from within the XML library), we can instead use the later form of free floating methods.

**Comment by ldicker83** [comment]
Range based loops won't work without modification to the underlying TinyXML implementation to provide a range. Such a modification is possible but I think would add too much overhead and would defeat the purpose of the "tiny" in the title. A different control mechanism would provide a better way to handle this.

Live code handling this differently with better control mechanisms can be found in OutpostHD's IO functions for savegames ([starting at line 139](https://github.com/ldicker83/OPHD/blob/master/src/States/MapViewStateIO.cpp#L139)):

```
XmlAttribute* attribute = map->firstAttribute();
while (attribute)
{
    if (attribute->name() == "diggingdepth") { attribute->queryIntValue(depth); }
    else if (attribute->name() == "sitemap") { sitemap = attribute->value(); }
    attribute = attribute->next();
}
```

Here we're explicitly moving to the next node within the `while` loop instead of doing this in the condition test itself. More verbose, sure, but ultimately a lot easier to understand. This could potentially be done in a `for` loop instead:

```
for(auto attribute = map->firstAttribute(); attribute; attribute = attribute->next())
{
   /* code here */
}
```

Either method should work fine but would need to be tailored to the individual use case (internally NAS2D only uses the XML library in the Configuration and Sprite objects).

**Comment by cugone** [comment]
In my own engine I got sick of writing the for loop to iterate over tinyxml2's child elements and attributes so I created a set of helper functions (`XMLElement` is an alias for `tinyxml2::XMLElement`) :


    void ForEachChildElement(const XMLElement& element, const std::string& childname /*= std::string{}*/, const std::function<void(const XMLElement&)>& callback /*= [](const XMLElement&) { / * DO NOTHING * / }*/)
    {
        auto childNameAsCStr = childname.empty() ? nullptr : childname.c_str();
        for(auto xml_iter = element.FirstChildElement(childNameAsCStr);
            xml_iter != nullptr;
            xml_iter = xml_iter->NextSiblingElement(childNameAsCStr))
        {
            callback(*xml_iter);
        }
    }

    void ForEachAttribute(const XMLElement& element, const std::function<void(const XMLAttribute&)>& callback /*= [](const XMLAttribute&) { / * DO NOTHING * / }*/)
    {
        for(auto attribute = element.FirstAttribute(); attribute != nullptr; attribute = attribute->Next())
        {
            callback(*attribute);
        }
    }

The side effect of using these is any algorithm that requires iterating over the set (like counting child elements or attributes; or getting all the element or attribute names; etc) becomes a very short function call and lambda:


    unsigned int GetAttributeCount(const XMLElement &element)
    {
        unsigned int attributeCount = 0;
        ForEachAttribute(element,
        [&](const XMLAttribute& /*attribute*/)
        {
            ++attributeCount;
        });
        return attributeCount;
    }

**Comment by ldicker83** [comment]
I'd be interested to see how this would be implemented using NAS2D's version. Keeping in mind of course that it's based on the original TinyXML and it's very stripped down. I'm game for providing uses that would work in lambda expressions... once I figure out how to actually use lambda expression (I know, I'm a little embarrassed that I haven't quite grasped the concept yet but I'll stick with I've been too busy in real life to take the time to learn about them).

Anyway, I'd like to go through the XML implementation in NAS2D and revamp it a bit. There's a lot of messy code and some stuff that's dubious using pointer arithmetic that I'm pretty sure is either incorrect or is difficult to really understand. It also doesn't take really good advantage of the STL and containers so ... eh.

**Comment by cugone** [comment]
Since tinyxml's developer recommends users use tinyxml2 because all future work will be focused on it (he's basically abandoned it in favor of version 2), and the NAS2D code is being updated anyway, it wouldn't be that hard to port it over.

**Comment by DanRStevens** [comment]
Both good solutions.

In terms of supporting range based for loops, without modifying the existing XML library code, I believe it can be done with external methods as follows:
```cpp
namespace NAS2D::Xml {
	
class XmlChildIterator {
public:
	XmlChildIterator() = default;
	XmlChildIterator(const XmlNode& xmlNode) : currentChild(xmlNode.firstChild()) {}
	XmlChildIterator& operator++() { currentChild = currentChild->nextSibling(); return *this; }
	bool operator!=(const XmlChildIterator& other) const { return currentChild != other.currentChild; }
	const XmlNode& operator*() { return *currentChild; }
private:
	const XmlNode* currentChild = nullptr;
};

XmlChildIterator begin(XmlNode& xmlNode) {
	return XmlChildIterator(xmlNode);
}

XmlChildIterator end(XmlNode& xmlNode) {
	return XmlChildIterator();
}

}
```

Usage would then be something like:
```cpp
for (auto& xmlChildNode : xmlParentNode) {
  // ...
}
```

----

Sounds like upgrading to TinyXML2 may be a good idea. Perhaps this can be done along with Issue #211.
