### ISSUE TITLE
Determine special folders without using PhysFS

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#212]
On the path towards replacing / removing the current `Filesystem` component (Issue #209), we need a way of determining appropriate platform specific write folder for things like game settings and saved games.

Currently the platform specific write folder is handled by PhysFS from within the `Filesystem` component. As this is likely to be removed soon, it needs a replacement.

----

@cugone, I believe you did some work towards such a method in the past. Are you able to dig up that work somewhere?

**Comment by cugone** [comment]
I asked for some clarification on the issue last month: https://github.com/lairworks/nas2d-core/pull/120#discussion_r272785613 . I know there was some contention on whether or not to remove some of the stored directories, like `mUserDirectory` or `mPrefDirectory` at the time and my concerns were that the platform differences were very different and potentially ambiguous, particularly for windows, and I didn't get a response. Removing some of the directories will mitigate, but not eliminate, some concerns.

Have there been any changes to this line of thinking between @ldicker83 and you about what is and is not being removed? What about the concerns I've outlined?

**Comment by DanRStevens** [comment]
Ahh, sorry, seems I missed replying to that comment.

That comment contains a decent summary of various options. Some aspects of the design we need are perhaps not entirely clear as there are quite a few subtle differences between paths and environment variables. We may need to do some experimentation to figure out what we really want.

In terms of what we need to support, the two most important are:
- Executable folder for reading static game assets
- Write folder for user configuration settings
- Write folder for saved games

These may or may not be the same folder, or a subfolder of another.

If we want, we might optionally allow retrieving other folders as well:
- User's home folder (Examples: `C:\Users\UserName\`, `/home/UserName/`)
- Current working directory (`std::filesystem::current_path()`)
- Startup working directory (the current working directory might change after startup)

These are optional, and maybe not so useful for games. The User's home folder, or related things such as Documents or Pictures might be useful in other contexts, such as image editors or document editors. That's out of scope though.

----

We may also want to give some consideration to things like Roaming or Local folders, as Windows distinguishes between the two in certain contexts. I believe we'd want the Roaming location.

----

Useful references:
https://docs.microsoft.com/en-gb/windows/desktop/shell/about-user-profiles
https://ss64.com/nt/syntax-variables.html
https://specifications.freedesktop.org/basedir-spec/latest/index.html#introduction

**Comment by cugone** [comment]
Back when the `std::filesystem` update was still potentially going to be added sooner rather than later I was inspired and added a lot of these types of functions to my own engine, could some of this implementation be used here?

https://github.com/cugone/Abrams2018/blob/master/Engine/Code/Engine/Core/FileUtils.hpp
https://github.com/cugone/Abrams2018/blob/master/Engine/Code/Engine/Core/FileUtils.cpp

**Comment by DanRStevens** [comment]
Yes.

I'm not quite certain yet what we need, but some of those look useful.

----

For the large `enum`, I was thinking perhaps define all the values on all platforms, even if some values don't represent a valid folder on the current platform. That could be useful in cross platform uses, where code running on one platform is creating paths or manipulating a filesystem for another operating system. It would also result in consistent enum values across platforms, which might be useful in case those values are ever stored to disk. The validity of an ID on the current platform can be checked with one of the query functions.

Though from another point, having platform specific enum values creates platform dependent code. I think what's really needed is some kind of platform independent abstraction, where high level concepts have IDs which map to platform specific folders. This is the involved part that requires a lot of thought and effort though.

----

For `bool` returning methods, it might be better to report errors with exceptions (which are not ignored by default like `bool` return values are), and then just return the actual data value. C++ has evolved since the early days, and exceptions should now be zero cost, and returning a `std::string` can now be done efficiently. Most `[out]` parameters can now be eliminated in favor of return values, and using exceptions for error reporting.

**Comment by cugone** [comment]
The `bool` returning functions are query only. They shouldn't throw an error simply because a bad path was passed. For the enum-based queries, they only throw an error if the enum is ever updated and used but it's not updated in the query function, i.e., it's most definitely an error that needs to be fixed immediately so a loud fail is necessary.

**Comment by DanRStevens** [comment]
This is maybe getting a bit off topic, though an example is:
```cpp
bool ReadBufferFromFile(std::vector<unsigned char>& out_buffer, const std::string& filePath)
```
This could be designed as follows, with failure indicated by an exception:
```cpp
std::vector<unsigned char> ReadBufferFromFile(const std::string& filePath)
```

----

To simplify things, we should probably focus on just the app specific write folder for now. I think we should start with replicating what PhysFS provides. In Issue #118, this was listed as:
```
Windows: "C:\\Users\\bob\\AppData\\Roaming\\My Company\\My Program Name"
Linux: "/home/bob/.local/share/My Program Name"
MacOS: "/Users/bob/Library/Application Support/My Program Name"
```

We may still want to discuss what we'll call this folder, and if we should have separate methods to return folders of different semantic meaning, such as the config folder versus the saved game folder (even if the folder ends up being the same).

**Comment by cugone** [comment]
I'm a little hesitant to copy a potentially multi-megabyte vector by value. (Until proven otherwise by profiling the code...)

The other bool-returning functions, sure, but the read/write file functions....yikes.

**Comment by ldicker83** [comment]
I'm still somewhat hesitant to introduce any sort of filesystem code into NAS2D in favor of placing that burden on the end user..... but, I see the use in having code that's pretty much seamless.

To that end, there's really only one read/write directory on the Big Three. Dan mentions it here:

> Windows: "C:\\Users\\bob\\AppData\\Roaming\\My Company\\My Program Name"
Linux: "/home/bob/.local/share/My Program Name"
MacOS: "/Users/bob/Library/Application Support/My Program Name"

I'm game to offer a simple function, say getApplicationDataPath() or something to that effect that provides this location to the end user. Microsoft's explanation is that all modern Windows programs should take advantage of the AppData/Roaming and only ever install and read/write from these paths, "never the directory containing the binary". Means end users on Windows platforms will absolutely need to have their applications packaged with an installer of sorts to write the binaries to an operating path and the data into the user path.

As much as I hate it, it's part of moving forward (I guess).

I'm not sure a full blown class will be needed for the future of NAS2D, I think a few convenience functions as @cugone has shown in his repositories should suffice. Put it in a sort of "FileUtils" type of file. Not sure it'll need to be in its own namespace (e.g., NAS2D::FS) but that's the general direction I'm leaning in.

**Comment by DanRStevens** [comment]
I agree. A couple of convenience functions should fill our needs. I don't think it needs to be a full class.

I beliece @cugone identified two areas that needed custom methods. One was determining the write folder. The other was determining the executable folder. I believe he had working code for both.

----

I'm curious what problems would necessitate having an installer. I'm not sure I see the need. I suspect a game package could still be made portable. Do you mean writing data to the user specific folder, rather than a game folder on an external hard drive? If so, I suppose the write folder could be conditional on the access permissions of the executable folder. We would need to clarify behavior. One suggestion is if the executable folder allows writing, then default to that as the write location, otherwise fallback to the write area within the user folder.

**Comment by cugone** [comment]
There are really only two filesystem functions that are required:

    ReadBufferFromFile
    WriteBufferToFile

Their use is to dump a file to or from memory; hitting the disk as little as possible, usually just once. Any other function is just convenience for the user.

**Comment by cugone** [comment]
Just asked for clarification for Linux's version of AppData on StackOverflow.
https://stackoverflow.com/questions/56364165/how-to-get-known-paths-for-linux

It's not as simple as asking the operating system like MacOSX and Windows; you pretty much have to hard-code the path to a (hopefully) standard-compliant filesystem directory and hope for the best: https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard

I think leaving it up to the user and any separate OS-specific ports they may make is a better idea than trying to make every OS happy on the Filesystem front.

**Comment by cugone** [comment]
@ldicker83 
@DanRStevens 

Just a side note:
I was looking through my registry to clean up after uninstalling Discord and noticed that Unreal Engine had an entry `EpicGames > Unreal Engine > [version]` just for "InstalledDirectory".

**Comment by DanRStevens** [comment]
Thanks for the links. The answer you got provided a nice summary for Linux. In particular, the linked document at:
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

The `$XDG_DATA_HOME` variable seems appropriate for saved games. We could potentially use `$XDG_CONFIG_HOME` for config settings. If we need to simplify, we could use `$XDG_DATA_HOME` for both saved games and config.

From the answer and linked document, in case the variables are not set, they should have the following defaults:
```
$XDG_DATA_HOME = $HOME/.local/share
$XDG_CONFIG_HOME = $HOME/.config
```

----

In terms of file access, I don't think we need to handle that in the library. As long as we can handle the ugly platform specific path part, we can read data using standard C++ library methods.

Actually, I might prefer leaving file reading out of the library and just providing the paths. Doing a full file read isn't always very efficient, and not always even possible for large files that may exceed the size of memory. Some library users may prefer streaming access for certain tasks, so if we can avoid forcing a decision on them it may be better.

----

Limiting the API to just providing default paths on certain supported platforms also makes it easier for a library user on an unsupported platform. If we can't provide a reasonable path for their platform, they can  just provide their own path from some other means. What they do with the path, or how they pass it on to read from is pushed on to the library user, or handled with the standard C++ library.

----

I don't know of a Registry equivalent for Linux. If you wanted to store an install path in the Register on Windows, that could work, though you'll still need to figure out a path to set in there, or a default path if the Registry entry is not set. In that case, you're still determining a platform specific path.

I should also caution that relying on the Registry could make the app less portable, in that people wouldn't be able to just copy it to a USB stick and play it from there. They would need to run an installer, unless the Registry setting was optional.

**Comment by DanRStevens** [comment]
While discussing input and SDL with cugone, I came across an SDL2 header file `SDL_filesystem.h`.
Documentation: [SDL2 Filesystem](https://wiki.libsdl.org/CategoryFilesystem)

It seems SDL2 provides methods for finding the executable path, and a program specific write folder. That can be used to implement the two most important needed functions discussed above.

**Comment by DanRStevens** [comment]
I was just thinking, the SDL2 Filesystem methods don't depend on PhysFS, and so don't need PhysFS to be initialized. That makes them callable before PhysFS is initialized.

Potentially the two methods could become static members of the `Filesystem` class.

Might want to handle that as a separate change though.
