### ISSUE TITLE
Extract code - size of collection of collection

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#217]
Looking at the new string methods, there seems to be a common repeated part that may be of general enough use to be extracted to it's own method. There are two slight variations of it, both of which will appear twice with the method splitting / bool parameter removal:

Version 1 (join without delimiter):
```cpp
const auto acc_op = [](const std::size_t& a, const std::string& b) noexcept->std::size_t { return a + b.size(); };
auto total_size = std::accumulate(std::begin(strs), std::end(strs), std::size_t{0u}, acc_op);
```

Version 2 (join with delimiter):
```cpp
const auto acc_op = [](const std::size_t& a, const std::string& b) noexcept->std::size_t { return a + std::size_t{1u} + b.size(); };
auto total_size = std::accumulate(std::begin(strs), std::end(strs), std::size_t{0u}, acc_op);
```

The second version can be written in terms of the first version:
```cpp
auto version2Sum = Version1Sum(strs) + strs.size();  // In this case, could add -1
```

----

In terms of generalizing the code, these methods are performing a flattening operation. The method is taking a collection of collections (a vector of strings, where strings are a collection of characters), and flattening them down to a single collection (a collection of characters). The operation is generic and could work on any collection types.

As part of that operation, the above lines calculate the output collection size needed for such an operation. The basic calculation is to determine the sum of the sizes of the inner collection over the outer collection. This generalizes no matter what the collections are of.

The simplified (no delimiter) case can be calculated with:
```cpp
template <typename Container>
std::size_t SumOfSizes(const Container& container)
{
      std::size_t sum = 0;
      for (const auto& item : container) {
              sum += item.size();
      }
      return sum;
}
```

The delimiter terminated case (delimiter follows every element, like semicolon terminated statements in C++) could be calculated with:
```cpp
auto size = SumOfSizes(container) + container.size() * sizeOfDelimiterInInnerCollectionUnits;
```

The delimiter separated case (delimiter between every pair of elements, like a comma separated list) could be calculated with:
```cpp
auto size = SumOfSizes(container) + (container.size() - 1) * sizeOfDelimiterInInnerCollectionUnits;
```

Required operations on the collection types are:
- The outer collection supports ranged-for (such as any forward iterable collection)
- The inner collection contains a `size()` member

**Comment by cugone** [comment]
Playing devil's advocate here:

 - What problem does generalizing the original code solve?
 - Does splitting the original code out into another function make the code more performant or less?
 - Did you measure the difference?
 - Is there a difference for large collections?
 - The STL algorithms are already pretty well optimized. What advantage is there to going back to a range-based for-loop over an `accumulate` call?

**Comment by DanRStevens** [comment]
I didn't measure for efficiency differences. I don't expect any. There was no particular reason for me to hand write the loop as opposed to using `std::accumulate`. It simply seemed like the more natural way to write it when I was focusing on that one little bit.

This is more about reducing code duplication. The same code is effectively duplicated in 4 different places (with 2 slight variants). By collapsing those 4 blocks of code into a common method call, it can reduce the duplication, and potentially reduce maintenance burden. To fully accomplish this, the two variants of the loop can be adapted to use a common loop part, and a post loop fixup to account for the size of all delimiters being added.

Being able to use the generalized code for some potential future use is more just a bonus.
