### ISSUE TITLE
Replace Common usages with StringUtils and/or MathUtils

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#219]
Engine-side of  #218 . Downstream projects will need to update separately.

Replace all usages of `Common.h` with `StringUtils.h` and/or `MathUtils.h`

**Comment by DanRStevens** [comment]
This should perhaps be an Issue on the OutpostHD project:
https://github.com/ldicker83/OPHD/issues

**Comment by cugone** [comment]
There are a few usages engine-side as well. It should probably be both. :)
