### ISSUE TITLE
Add math support classes

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#226]
Add several math support classes:

> Vector2
Vector3
Vector4
Matrix4
AABB2

Vectors/Matricies/AABB2s are used large-scale in nearly all math operations. They can be used as parameter packs for points, directions, minimums, maximums, matrix rows and columns; they are used in collision detection, collision resolution, to define areas for boundaries, viewable areas, texture UVs, verticies... the list goes on.

The advantage of these over the currently designed `Point_2d` and `Rectangle_2d` is they are not themselves renderable and as such are much faster. They can be used as arguments to rendering operations such as a `vertex` class or to support the existing point and rectangle classes.

**Comment by DanRStevens** [comment]
What do you mean not renderable, and therefore much faster? I'm not sure I quite understand what this addition will do.

For anyone else who doesn't know what AABB2 is, Google comes up with a 2-dimensional Axis Aligned Bounding Box.

**Comment by cugone** [comment]
They are designed as pure math concepts and have no need to support drawing inside the class. The class names suggest a different use than `Point_2d` or `Rectangle_2d` do (even though they may contain the same data, the operations/functions are different.)

They are also designed to be super cheap to copy or move and pass around because in a game environment you can expect to have millions of vectors in a scene at once (AABB2s in the thousands depending on scene complexity.)

**Comment by DanRStevens** [comment]
If the data fields are the same, the efficiency should also be the same. Having extra methods available doesn't incur any particular runtime cost. Are you proposing a change to the data fields to support faster operations?

Or is this more of a type system thing, where a Point and a Vector are distinct types, even though they can both be represented with the same fields?

**Comment by cugone** [comment]
Yes. :)

Kidding aside, it makes it very clear what the code is doing. For example, what does it mean to add, subtract or multiply two points on a graph? Conceptually these have no meaning. For vectors, they are well-known and understood.

It's easier and faster to write a vector class and its operations from the beginning to be performance critical up front rather than trying to ham-fist a 10-year-old unrelated class into that role.

**Comment by cugone** [comment]
Closing this issue as `Vector`, `Point`, and `Rectangle` are things. Will reopen different issue for Matrices and the need for 3/4D Vectors.
