### ISSUE TITLE
Remove `Release Gold` configuration

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#233]
There is little difference between the `Release` and `Release Gold` configuration. Mostly just a few optimization settings. Ideally we should only have a single release configuration, with one set of optimization settings. We should perhaps merge the differences, and remove the `Release Gold` configuration.

Currently I see the following differences in settings:

`Release Gold|Win32`:
```
      <Optimization>Full</Optimization>
      <FavorSizeOrSpeed>Speed</FavorSizeOrSpeed>
      <InlineFunctionExpansion>AnySuitable</InlineFunctionExpansion>
      <OmitFramePointers>true</OmitFramePointers>
```

`Release Gold|x64`:
```
      <Optimization>MinSpace</Optimization>
      <FavorSizeOrSpeed>Size</FavorSizeOrSpeed>
```

`Release` (`Win32` and `x64`):
```
      <Optimization>MaxSpeed</Optimization>
      <EnablePREfast>true</EnablePREfast>
```

----

As a side note, I once read that due to effects of processor caches, optimizing for size often produced the fastest code. I don't know if that is still true.

**Comment by cugone** [comment]
I generally have three "Release" builds:

 - The default `Release` build: useful for profiling (never profile debug code!)
 - A `FastDebug` build: A copy of the default but with optimizations turned off to facilitate step-through debugging.
 - And a `FinalBuild` build: All optimizations turned on and all debug pre-processing defines and asserts disabled.

**Comment by DanRStevens** [comment]
Well, they do allow multiple configurations for cases where you might need them. In our case here, I don't think we really need them. We don't do anything too fancy development wise.

For distribution licensing reasons (on the Microsoft debug runtime), we can only really distribute the `Release` versions. That's somewhat reflected in the AppVeyor builds, which are only setup to build the `Release` versions. The other part simply being build time. If you want the `Debug` versions, that's likely only for local debugging.

I think Leeor was looking into removing the Gold configuration at some point in the past.
