### ISSUE TITLE
Rename `isRectInRect`

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#235]
The method `isRectInRect` would seem to imply containment, as in one rect is entirely contained in the other. In actuality, the method tests if two rects overlap at all. The method should be renamed to reflect that.

Related, the method test overlap in an endpoint inclusive way. Looking at method usage, it seems endpoint exclusive might be more appropriate to how it is used. The exclusive way may also be more common and expected by end users. When the method is renamed, we should give some consideration to the exact definition of what it does, and if any behaviour update is required.

My suggestion is to transition it to endpoint exclusive. That may require some updates to the test cases.

**Comment by cugone** [comment]
It can be renamed `DoRectsOverlap` and a separate function `Contains` can be added if needed.

**Comment by ldicker83** [comment]
Honestly, it was intended as a basic intersect test. It could be moved into the Rectangle_2d and Rectangle_2df classes as Rectangle_2d/f::intersects(const Rectangle_2d/f& r). Would actually simplify syntax in a number of areas.

**Comment by DanRStevens** [comment]
I was thinking similar. We could easily offer member functions for both `intersects` and `contains`. The later being more sensible as a member function, as the relationship is not symmetric, so a free form function would not make it obvious which rect contains the other. With `intersects` the relationship is symmetric, so would be clear as either a member function or a free standing function.
