### ISSUE TITLE
Bug in debug output code

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#249]
Looks like there is a bug on line 480. I think `filePath` was intended, rather than `name()`:
https://github.com/lairworks/nas2d-core/blob/7772e27677d9df98601d861c620b3c1d1d4f4e2d/src/Renderer/RendererOpenGL.cpp#L474-L482

This code was introduced in commit 5df940df.

The `name()` method returns the name of the `Renderer` object, which in this case will be `"OpenGL Renderer"`.

**Comment by ldicker83** [comment]
Looks like a legit oversight to me.
