### ISSUE TITLE
Modify Renderer Interface to maintain color draw state

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#25]
Currently the renderer interface is set up such that every call to the renderer asks the user to provide color information. Each function provides default values for these colors.

While this makes it very easy to set up rendering parameters for tinting images and primitives for drawing, it unfortunately *also* adds to the complexity of the overall interface. The even more serious problem is in the OpenGL implementation which now makes a call to `glColor4ub` *for every single draw call*. Since almost everything is drawn using the values `{ 255, 255, 255, 255 }` this leads to a LOT of overhead and wasted time.

---

### Changes
Instead, the Renderer should store state information about both the clear color and the draw color. If the user wants to change the draw color, they will need to explicitly set them. The following functions should be added to the Renderer interface:

This will represent an interface breaking change (again) but most legacy code should be easily adapted.

#### Additions
```cpp
void clearColor(int r, int g, int b);
void resetClearColor(); // sets clear color to black { 0, 0, 0 }
void drawColor(int r, int g, int b, int a);
void resetDrawColor(); // sets draw color to white { 255, 255, 255, 255 }
```

#### Removal
All color information from all draw calls (e.g., drawImage, drawText, drawLine, etc.) can be removed from from function prototypes. This will be a fundamental change regarding how draw functions are used.

### Justifications
My initial thinking was to simply have each function test the current draw color against what was specified and make changes accordingly but this would further bloat overhead.

While forcing the user to explicitly set color states is annoying and not the cleanest look, profiling in 'gDEBugger' shows that it would eliminate *tens of thousands* of completely superfluous OpenGL state changes that effectively do nothing. While performance changes may not be immediately obvious to the end user, the reduced overhead would be significant and would also force the user to think about how to group draw calls to to avoid making too many state changes.

**Comment by ldicker83** [comment]
I realized that this is such a large change that it should be in its own milestone, probably closer to a version 2.0 of NAS2D. Will leave it without a milestone for the time being.

**Comment by DanRStevens** [comment]
From an API usability standpoint, I think I would advise against making this change.

The API is much easier to use when all the parameters needed for a single operation are provided in a single call. That is particularly true for points, lines, and rectangles, which often aren't drawn in the default color. If the color parameter was split off, many of those operations would then need two calls to complete. This isn't the most user friendly approach, but then, stateful APIs usually aren't.

If you're concerned about performance, and if it really does matter, maybe do as you suggested and test the last set color, and skip the `glColor4ub` call if it's the same. With some of the recent code cleanup, all color setting is now routed through a helper function which takes a `NAS2D::Color` parameter, and passes the components to `glColor4ub`. It would be easy enough to add a `static` local variable to store the last set color, and skip the operation if the colors compared equal. As a bonus, `NAS2D::Color` already provides an `operator ==`.

**Comment by ldicker83** [comment]
The direction that we're going with NAS2D makes this a sort of moot point. The general idea was to try to reduce the number of state changes in OpenGL (and probably DirectX) but it doesn't really seem necessary in all of this. It would probably be safe to either close or delete this issue and mark it as "wont change".

**Comment by DanRStevens** [comment]
Ok. Seems there was a handy "wontfix" label already available.
