### ISSUE TITLE
Refactor `_music_complete` in `Mixer`

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#251]
The `_music_complete` signal exhibits poor encapsulation:
```cpp
	/**
	 * Gets a reference to a NAS2D::Signals::Signal0<void>, a signal raised
	 * when a Music track has finished playing.
	 */
	NAS2D::Signals::Signal0<void>& musicComplete();

protected:
	// ...
	NAS2D::Signals::Signal0<void> _music_complete; /**< Callback used when music finished playing. */
```

The member variable was declared `protected`, but is returned by a `public` member function. This effectively make it public. This also exposes it to the caller, so the caller can raise signals, which at a glance seem like they should be controlled by the `Mixer` itself. It seems the [Law of Demeter](https://en.wikipedia.org/wiki/Law_of_Demeter) has been violated here.

A more protective design would have a method that accepts a callback delegate, without exposing the signal object. You might also need a method to unset the callback, though for simple designs, it may be acceptable to just rely on destruction of the `Mixer` to clear the setting.

**Comment by ldicker83** [comment]
An unset method would be needed as listeners may go out of scope before the mixer (e.g. State)

**Comment by DanRStevens** [comment]
The `MakeDelegate` call can be moved to the caller, and the underlying delegate type can be passed:
```cpp
Utility<Mixer>::get().addMusicCompleteHandler(MakeDelegate(this, &GameState::musicComplete));
```

The implementation in the `Mixer` class then looks something like:
```cpp
void Mixer::addMusicCompleteHandler(NAS2D::Signals::Signal0<>::_Delegate handler)
{
	return _music_complete.connect(handler);
}


void Mixer::removeMusicCompleteHandler(NAS2D::Signals::Signal0<>::_Delegate handler)
{
	return _music_complete.disconnect(handler);
}
```
