### ISSUE TITLE
Fix implementation reserved identifiers

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#258]
While reviewing #247 I noticed several variable names and classes that started with an underscore followed by a capital letter. Though not illegal, identifier names of this construction (along with any name that contains an underscore followed by another underscore) are reserved for the implementation and should never be used. Since this is a targeted change but may be pervasive I think one big feature branch with smaller commit changes to the entire project are required so the changes can be applied at once.

**Comment by DanRStevens** [comment]
I agree that we should avoid names that begin or end with underscore. A single underscore is allowed in some cases, but it can be hard to remember which cases are standard conforming.

Plus, I find underscores just kind of look ugly. :P

**Comment by DanRStevens** [comment]
Was just thinking we need a reference for underscore naming rules.

StackOverflow reference:
[What are the rules about using an underscore in a C++ identifier?](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier)

**Comment by ldicker83** [comment]
About mid-way through development I started experimenting with other naming methods for member variables. This was one of the ones I tried.

I reserve underscores now only for local variables in functions but even that I'm not really consistent with preferring instead to just use lowercase names.

Anyway, definitely in favor of this.
