### ISSUE TITLE
Move pre-defined Color_4ub colors from Renderer to Primitives file

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#259]
It's quite likely that another part of the engine or downstream project will want to use them. Keeping them local to the Renderer translation unit promotes bad practices of duplicating them.

At the same time they should be renamed to not use the out-dated "all caps for constants/enums" "rule" as that has been relegated to macros only.

N.B. I have actually had this bite me in the past. I named a scoped enum value for keys as `DELETE`. By including the `<windows.h>` header it created a macro named `DELETE` and since macros are strict and direct text replacement, things exploded.

Ref: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Renum-caps
Ref: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-not-CAPS
Ref: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Res-ALL_CAPS
Ref: https://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rl-all-caps

**Comment by DanRStevens** [comment]
I think I would agree here. Common color names should perhaps be more accessible.

I also agree about not using all caps. I generally use UpperCamelCase for constants.

Interesting links about macro interference. I've run into similar myself. A macro from a header renamed a function on me, which resulted in later link errors, because a function with the exact name I used wouldn't be found. It was one of those WindowsFunction -> WindowsFunctionA / WindowsFunctionW macros.

**Comment by ldicker83** [comment]
Agreed on UpperCamelCase naming. All caps is old practice and comes from the code base from almost 12 years ago.

It will have breaking changes for apps that depend on NAS2D but it's simple enough to make the upgrade.

I would also recommend adding them to a nameapace so that instead of ColorWhite, ColorGreen, ColorLightRed, etc., they would look like NAS2D::Color::White and so on.

**Comment by cugone** [comment]
> 
> I would also recommend adding them to a nameapace so that instead of ColorWhite, ColorGreen, ColorLightRed, etc., they would look like NAS2D::Color::White and so on.

By declaring them inside the Color_4ub class as `public static Color_4ub Red;` We get that behavior for free! :D

**Comment by DanRStevens** [comment]
Speaking of which, perhaps we should do something about the name `Color_4ub`. That may be a different issue though.

On a related note, I assume the maximum value for colors changes based on data type. For unsigned bytes, I would assume `0 .. 255` (inclusive). For floating point, I would assume `0.0 .. 0.1` (inclusive).

**Comment by cugone** [comment]
> 
> 
> Speaking of which, perhaps we should do something about the name `Color_4ub`. That may be a different issue though.
> 
> On a related note, I assume the maximum value for colors changes based on data type. For unsigned bytes, I would assume `0 .. 255` (inclusive). For floating point, I would assume `0.0 .. 0.1` (inclusive).

`Rgba` maybe? It represents the order of bytes. You could have another named `Bgra` (directx has an option to use this format), etc.

Yes, the maximum value changes. It's not that difficult to convert to/from float/unsigned char formats as a member function in the class. It really only matters as an interface to lower-level interfaces. E.g. DirectX expects float values. They are usually stored as `Vector4`s on the CPU-side; it's simple to provide a number of member function on the color type:

```
Rgba::Rgba(const Vector4& fromFloats) {
    SetRgbaFromFloats(fromFloats);
}
Vector4 Rgba::GetRgbaAsFloats() const {
    return Vector4{ r / 255.0f, g / 255.0f, b / 255.0f, a / 255.0f };
}
Vector3 Rgba::GetRgbAsFloats() const {
    return Vector3{ r / 255.0f, g / 255.0f, b / 255.0f };
}
void SetAsFloats(float normalized_r, float normalized_g, float normalized_b, float normalized_a) {
    r = static_cast<unsigned char>(normalized_r * 255.0f);
    g = static_cast<unsigned char>(normalized_g * 255.0f);
    b = static_cast<unsigned char>(normalized_b * 255.0f);
    a = static_cast<unsigned char>(normalized_a * 255.0f);
}
void SetAsBytes(unsigned char red, unsigned char, green, unsigned char blue, unsigned char alpha) {
    r = red;
    g = green;
    b = blue;
    a = alpha;    
}
void SetRgbaFromFloats(const Vector4& fromFloats) {
    SetAsFloats(fromFloats.x, fromFloats.y, fromFloats.z, fromFloats.w);
}
void SetRgbFromFloats(const Vector3& fromFloats) {
    SetAsFloats(fromFloats.x, fromFloats.y, fromFloats.z);
}
```
