### ISSUE TITLE
Split Primitives file into separate class files

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#260]
The primitives file contains several unrelated classes and should be split up.

Tagging #259 as related.

**Comment by DanRStevens** [comment]
Agreed. The name "Primitives" really doesn't tell me what to expect in that file. Might be people throwing rocks and spears, and cooking over an open fire.

On a related note, the Point and Rect classes should probably be templatized to reduce duplication. For backwards compatibility, the old names can become `using` aliases to the template with a given type substitution. I've been meaning to tackle that one myself.

**Comment by DanRStevens** [comment]
On another related note, we should prefer `struct` with public member variables to `class` with getter/setter methods for every member field. If you truly want public read/write access to every field, then what you really have is a `struct`, and so it should just be one.

**Comment by cugone** [comment]
Or just make the members public and remove the getter/setters,:

```cpp
class Color_4ub {
    public:
        /* ...Lots of helper methods, static pre-defined colors, static Random color functions, etc... */
        unsigned char r;
        unsigned char g;
        unsigned char b;
        unsigned char a;
    protected:
    private:
};
```

**Comment by DanRStevens** [comment]
Then again, you have a `struct`. The only difference between a `class` and a `struct` is default visibility.

```cpp
struct AStruct {
  // Defaults to `public:`
  // ...
};

class AClass {
  // Defaults to `private:`
  // ...
};
```

They can both contain the exact same things (member variables, member functions, static members, nested types, etc.).

**Comment by cugone** [comment]
Yes but I refer you to convention: https://www.fluentcpp.com/2017/06/13/the-real-difference-between-struct-class/

Conventionally `struct` is used for POD-types that are just a bundle of related variables with no methods; it can't *do* anything it's just a container. Similarly, convention says a `class` may have member variables all declared public just like a `struct` but unlike a `struct` it has methods and actions that act on that data with meaning.

**Comment by DanRStevens** [comment]
Yes, and I'm saying `Point` and `Rect` types are basically just POD-types. The `Color` type is as well.

As per that link:

> Finally a simple rule of thumb for choosing between struct or class is to go for class whenever there is at least one private member in the structure.

These structs should not have any private members.

> In fact a user of a class is not supposed to know what data the class is storing, or if it contains any data at all for that matter.

We do know the data, and there is no reason to hide it. There are no invariants relating the `x` and `y` values to each other.

From the end of the article, he links to:
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-struct  (The big reason)
http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-class  (A poor fit)

**Comment by DanRStevens** [comment]
I realize some of my earlier points may have been a little off topic. I decided to open new issues to address them separately. This issue can remain focused on splitting the files.

Related new issues:
#267 Use template for common code of Point and Rectangle
#268 Convert Point and Rectangle from class to struct
