### ISSUE TITLE
Merge `Filesystem::init` with constructor

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#263]
I'd like to suggest merging `Filesystem::init` with the constructor, and removing `Filesystem::init` as a (public) member function.

I believe this is more consistent with current C++ design principles. If the `Filesystem` object experiences an error during initialization, it should `throw` from the constructor, preventing object creation. This means you can never have a partially initialized zombie object. That removes the need to test for things like `isInit` in each member function before doing anything. If the object isn't initialized, then it never existed, and so there was never any object to call member functions on. I think this would make for a much cleaner design.

----

Changes:
- Move the `init` parameters over to the constructor
  - Have the constructor call `init`
  - If an init error occurs, `throw std::runtime_error` (or derived)
- Remove `init` from the public member section
- Remove `isInit` style checks from member functions

Optionally, the `init` method can be removed entirely if the contents are moved into the constructor.

There should be no default constructor on `Filesystem`.

**Comment by DanRStevens** [comment]
Will be interested to see what you come up with.

I know this is a bit late to mention, but as for my (very recent) https://github.com/lairworks/nas2d-core/pull/243#issuecomment-569457030, this change could eliminate the need for things like `mIsInit`. That could be a way of simplifying PR #243, and cutting down on its bulk. Doing so though would require merging this first as an independent change, and rebasing the other branch, which could potentially be a bit of work. Maybe not really fair for me to ask this late into changes. It would really help cut down on the size of a review chunk though.

**Comment by ldicker83** [comment]
In agreement here -- I wouldn't be entirely opposed to just moving the init code into the constructor in an effort to maintain a tidy interface even though that flies in the face of best practices. Will investigate and see how best to approach this.
