### ISSUE TITLE
Convert Point and Rectangle from class to struct

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#268]
The Point and Rectangle classes behave more like structs than classes. As such, they should simply be declared as such. In particular, the private fields all have public getter/setter methods, making the fields essentially public anyway. Direct access should just be given.

For backwards compatibility, we could still offer the same getter/setter methods, though they should be deprecated and removed at some point.

From the C++ Core Guidelines:
[C.2: Use class if the class has an invariant; use struct if the data members can vary independently](http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#Rc-struct)

There are no invariants to be maintained. The `x`, `y`, `width`, `height` values may all vary independently.

**Comment by ldicker83** [comment]
What is the benefit of converting to struct except that all members are public by default?
