### ISSUE TITLE
AppVeyor supports full Visual Studio 2019

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#273]
We can upgrade to using the non-preview of VS2019 as AppVeyor now has support for VS2019 16.4, the latest version as of this issue.

**Comment by DanRStevens** [comment]
Oh excellent. That is good news.

**Comment by cugone** [comment]
Just tested it on my own repos. Works great and the only thing we have to do is remove the word "Preview" from the image name in the appveyor yaml file.
