### ISSUE TITLE
Pulling fresh from master doesn't build on Windows

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#278]
I pulled a fresh copy of master for my laptop and several issues popped up:

 - GL/glew.h couldn't be found.
 - physfs.h couldn't be found (this will go away with future updates).
 - Several `.pdb`s are listed as using an obsolete format and need to be deleted and recompiled.

This is probably because vcpkg isn't being setup correctly on build. Setting up a `Properties > Configuration > Build Event > Pre-Build Event` to have vcpkg download and setup the required submodules might fix the issue.

**Comment by DanRStevens** [comment]
PhysFS and GLEW are the `vcpkg` dependencies, so you're probably right about that. Add GoogleTest to that list if you're also building the test project, though that won't build until you've first built the base project.

It would be nice to more tightly integrate installing `vcpkg` dependencies with the project file, much like how NuGet packages are automatically installed if they are missing. We can probably do it with similar project file code. There might also be a `vcpkg` option to more tightly integrate with the project file. Not having Visual Studio, I haven't tried experimenting with it.

----

The `.pdb` files would be generated by a build. Are you sure it's a fresh checkout? It kind of sounds like the folder was copied from another computer where a build had been done before.

**Comment by cugone** [comment]
I double-checked by deleting the entire folder and re-cloning the repo. Same issues.

**Comment by DanRStevens** [comment]
There are no `.pdb` files checked into the repository though. How can they be an obsolete format if they don't exist? And if they were generated by the current compiler, they should be a matching format. Something here doesn't make sense.

**Comment by cugone** [comment]
Yeah I have never seen that error before.

I pulled latest on `vcpkg.git` (apparently I was 99+ commits behind and the version I had did not support VS2019) and set up a Pre-Build Event locally to run the `installvcpkgdeps.bat` file.

Works now.

Is there a way to force a git pull on vcpkg or would that be a prerequisite of trying to build from source?

**Comment by DanRStevens** [comment]
This is all new territory to me.

I don't actually use `vcpkg` on Linux. The dependencies we need all have system packages on Ubuntu 18.04, so I just use those to install them.

It can be a bit awkward to test this stuff on AppVeyor. Most of what I know about `vcpkg` comes from Brett experimenting with it in other OPU projects.

**Comment by cugone** [comment]
I'm in the same boat for Linux/MacOS builds. :P 

I'd like to at least get to a state where a new user trying to build source can pull latest and build without errors (provided they have the prerequisites installed i.e. vcpkg, git, etc.)

**Comment by DanRStevens** [comment]
I found this curious note in the documentation:
[Linking NuGet file](https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#linking-nuget-file)

It looks like `vcpkg` has some way to integrate directly with the project file. However, it contains a note about how that's not recommended for open source projects. It doesn't explain why. I've been tempted to play with the option to see what it does. I assume the warning goes beyond a simple need to have `vcpkg` installed to use the project file?

----

Failing any sort of built-in `vcpkg` integration, we could perhaps model some changes based on what NuGet does to the project file:

```
  <Import Project="$(VCTargetsPath)\Microsoft.Cpp.targets" />
  <ImportGroup Label="ExtensionTargets">
    <Import Project="packages\sdl2.nuget.redist.2.0.9\build\native\sdl2.nuget.redist.targets" Condition="Exists('packages\sdl2.nuget.redist.2.0.9\build\native\sdl2.nuget.redist.targets')" />
    <Import Project="packages\sdl2.nuget.2.0.9\build\native\sdl2.nuget.targets" Condition="Exists('packages\sdl2.nuget.2.0.9\build\native\sdl2.nuget.targets')" />
    <Import Project="packages\sdl2_mixer.nuget.redist.2.0.4\build\native\sdl2_mixer.nuget.redist.targets" Condition="Exists('packages\sdl2_mixer.nuget.redist.2.0.4\build\native\sdl2_mixer.nuget.redist.targets')" />
    <Import Project="packages\sdl2_mixer.nuget.2.0.4\build\native\sdl2_mixer.nuget.targets" Condition="Exists('packages\sdl2_mixer.nuget.2.0.4\build\native\sdl2_mixer.nuget.targets')" />
    <Import Project="packages\sdl2_image.nuget.redist.2.0.4\build\native\sdl2_image.nuget.redist.targets" Condition="Exists('packages\sdl2_image.nuget.redist.2.0.4\build\native\sdl2_image.nuget.redist.targets')" />
    <Import Project="packages\sdl2_image.nuget.2.0.4\build\native\sdl2_image.nuget.targets" Condition="Exists('packages\sdl2_image.nuget.2.0.4\build\native\sdl2_image.nuget.targets')" />
    <Import Project="packages\sdl2_ttf.nuget.redist.2.0.15\build\native\sdl2_ttf.nuget.redist.targets" Condition="Exists('packages\sdl2_ttf.nuget.redist.2.0.15\build\native\sdl2_ttf.nuget.redist.targets')" />
    <Import Project="packages\sdl2_ttf.nuget.2.0.15\build\native\sdl2_ttf.nuget.targets" Condition="Exists('packages\sdl2_ttf.nuget.2.0.15\build\native\sdl2_ttf.nuget.targets')" />
  </ImportGroup>
  <Target Name="EnsureNuGetPackageBuildImports" BeforeTargets="PrepareForBuild">
    <PropertyGroup>
      <ErrorText>This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is {0}.</ErrorText>
    </PropertyGroup>
    <Error Condition="!Exists('packages\sdl2.nuget.redist.2.0.9\build\native\sdl2.nuget.redist.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2.nuget.redist.2.0.9\build\native\sdl2.nuget.redist.targets'))" />
    <Error Condition="!Exists('packages\sdl2.nuget.2.0.9\build\native\sdl2.nuget.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2.nuget.2.0.9\build\native\sdl2.nuget.targets'))" />
    <Error Condition="!Exists('packages\sdl2_mixer.nuget.redist.2.0.4\build\native\sdl2_mixer.nuget.redist.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_mixer.nuget.redist.2.0.4\build\native\sdl2_mixer.nuget.redist.targets'))" />
    <Error Condition="!Exists('packages\sdl2_mixer.nuget.2.0.4\build\native\sdl2_mixer.nuget.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_mixer.nuget.2.0.4\build\native\sdl2_mixer.nuget.targets'))" />
    <Error Condition="!Exists('packages\sdl2_image.nuget.redist.2.0.4\build\native\sdl2_image.nuget.redist.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_image.nuget.redist.2.0.4\build\native\sdl2_image.nuget.redist.targets'))" />
    <Error Condition="!Exists('packages\sdl2_image.nuget.2.0.4\build\native\sdl2_image.nuget.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_image.nuget.2.0.4\build\native\sdl2_image.nuget.targets'))" />
    <Error Condition="!Exists('packages\sdl2_ttf.nuget.redist.2.0.15\build\native\sdl2_ttf.nuget.redist.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_ttf.nuget.redist.2.0.15\build\native\sdl2_ttf.nuget.redist.targets'))" />
    <Error Condition="!Exists('packages\sdl2_ttf.nuget.2.0.15\build\native\sdl2_ttf.nuget.targets')" Text="$([System.String]::Format('$(ErrorText)', 'packages\sdl2_ttf.nuget.2.0.15\build\native\sdl2_ttf.nuget.targets'))" />
  </Target>
```

The `Condition="!Exists(...)"` syntax seems to be general and usable for arbitrary commands. Perhaps we could make use of it to see if the `vcpkg` folder for project dependencies doesn't exist, and only then try to run the `InstallVcpkgDeps.bat` batch file.

Currently I only see an example to `Import` project settings, or display an `Error` message. Though perhaps it can be combined with the `PreBuildEvent` step? This would also certainly require doing raw edits to the project file with a text editor.
