### ISSUE TITLE
Point and Rectangle should have explicit conversion for underlying base type

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#281]
The `Point` and `Rectangle` classes have a lot of overloaded functions to convert between an underlying type `int` and an underlying type of `float`. This in effect allows for implicit conversions, which may have unexpected rounding effects that could impact correctness, and also lead to hidden performance implications.

Rather than rely on what are effectively implicit conversions, there should exist explicit conversion methods. This would allow the caller to express conversion intent much more clearly.

----

As a first step, we could provide such explicit conversion functions, while making no other modifications that would affect backwards compatibility. Use of these explicit conversions would then be voluntary.

As a second step, the extra overloads that effectively do silent implicit conversions could be deprecated or removed. This would break old code. It would however make it easy to find code that should be updated, and the update itself would be fairly simple. Just add an explicit conversion call.

----

Related: Issue #267
If the common methods are templated, the conversion method could also be templated to convert to any other underlying type, using a default implementation of `static_cast`.

----

Old code:
```cpp
Point_2d pointInt{0, 0};
Point_2df pointFloat{0, 0};

// Implicitly trigger conversions (potentially bad)
if (pointInt == pointFloat) {
  // ...
}
```

New code:
```cpp
Point_2d pointInt{0, 0};
Point_2df pointFloat{0, 0};

// Explicitly convert type
if (pointInt.toFloat() == pointFloat) {
  // ...
}
```

New code (template version):
```cpp
Point_2d pointInt{0, 0};
Point_2df pointFloat{0, 0};

// Explicitly convert type
if (pointInt.to<float>() == pointFloat) {
  // ...
}
```

**Comment by ldicker83** [comment]
In favor of this. Prefer the templatized version as it's in line with #267.

**Comment by DanRStevens** [comment]
Ok. I agree.

To make the template implementation work, I think we need to implement #267 first. That way classes of different types all have the same template name, allowing the exact type to be easily specified by the type parameter. Meanwhile, getting rid of the extra overloads means less work to implement #267, assuming you account for all current overloads.

It may make sense to first implement the non-template solution here first, then complete #267, then revisit here to switch to the template method.

----

It occurred to me, there may be an easy way to make this adjustment that preserves backwards compatibility. Implement this using a conversion operator, rather than a named conversion method:
```cpp
Rectangle_2df::operator Rectangle_2d() const
```

Previous code could then implicitly call the conversion operator to map between types. That means no breaks in downstream code. The following could compile using the conversion operator:
```cpp
Rectangle_2d converted = object.getFloatRect();
```

This would require removing the constructor overloads to map between types, so as to remove ambiguity. The comparison overloads could then be removed, as mixing types would trigger an implicit conversion, and then simply call the comparison operator on matching types.

Initially, these conversions would be done implicitly, like before. At some point in the future, we could declare the conversion operator explicit, which would then trigger errors where an implicit conversion was attempted. That would be an easy way to find and fix where implicit conversions are happening.

**Comment by DanRStevens** [comment]
Actually, now that I think about it, once the API asymmetry is removed by this change, converting the conversion operator to a template method is then dead simple and effectively part of issue #267. I'm going to consider this issue closed once we have the non-template method merged. The conversion of the ... conversion operator, ... to a template method, is then handled as part of #267.

**Comment by DanRStevens** [comment]
Doh! I only did the `Rectangle` classes, not the `Point` classes. Re-opening for corresponding updates to `Point`.

**Comment by ldicker83** [comment]
I thought something was missing. Leave it to me to check things out while I'm both tired and doing it on a phone in bed. 😩

**Comment by DanRStevens** [comment]
Nah, it was my fault. I was tired and distracted when I made the PR. Should be fine though, the two changes are independent sets, which can, and maybe even should have been done as separate PRs. I just shouldn't have tagged the first PR as closing the issue.
