### ISSUE TITLE
Update Docker images

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#292]
The Docker images haven't been updated in a while. We should perhaps check for updates and do a refresh build.

Tasks:
- Pull updated Docker images
- Update versions of software to install
- Rebuild Docker images
- Push updated images to DockerHub with updated version tags
- Update CircleCI config to use new images

Related: We might consider producing images to support more compilers. In particular, we could probably support builds with:
- GCC (current Linux build)
- Clang (current MacOS build)
- Mingw-w64 (cross compile for Windows from Linux)

**Comment by cugone** [comment]
The only stipulations I have are make sure the versions are high enough to
support at least all library and language features of C++17 and Windows 8.1
(Windows 7 is out of support and realistically should no longer be the
minimum.)

**Comment by DanRStevens** [comment]
I don't entirely agree. I think the build should use stock tools from the latest Long Term Support (LTS) release of Ubuntu. If that doesn't provide new enough libraries by default, then we should probably offer workarounds within the project source.

I'm not opposed to experimenting with build images for newer compilers or newer versions, but I consider that somewhat optional. For instance, we could experiment with an Ubuntu 19.04 release, and we could experiment with an Ubuntu 18.04 release using alternate non-default compilers from the universe repository, such as `gcc-8`.

Looking to the future, we're getting pretty close to the Ubuntu 20.04 LTS release. If something absolutely needs updated packages, we could consider saving some of the development effort and waiting a few months before making that change.
