### ISSUE TITLE
GCC Warning - null destination pointer

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#293]
Newer versions of GCC are showing the following 4 warnings (they are all basically the same):
```
In file included from include/NAS2D/Filesystem.h:13:0,
                 from src/Resources/Image.cpp:14:
include/NAS2D/StringUtils.h: In function 'std::__cxx11::string NAS2D::string_format(const string&, Args ...) [with Args = {const char*, int}]':
include/NAS2D/StringUtils.h:40:30: warning: null destination pointer [-Wformat-truncation=]
   std::size_t size = snprintf(nullptr, std::size_t{0u}, format.c_str(), args...) + std::size_t{1u};

                      ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

In file included from include/NAS2D/Filesystem.h:13:0,
                 from src/Resources/Font.cpp:14:
include/NAS2D/StringUtils.h: In function 'std::__cxx11::string NAS2D::string_format(const string&, Args ...) [with Args = {int}]':
include/NAS2D/StringUtils.h:40:30: warning: null destination pointer [-Wformat-truncation=]
   std::size_t size = snprintf(nullptr, std::size_t{0u}, format.c_str(), args...) + std::size_t{1u};

                      ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include/NAS2D/StringUtils.h: In function 'std::__cxx11::string NAS2D::string_format(const string&, Args ...) [with Args = {unsigned int}]':
include/NAS2D/StringUtils.h:40:30: warning: null destination pointer [-Wformat-truncation=]
   std::size_t size = snprintf(nullptr, std::size_t{0u}, format.c_str(), args...) + std::size_t{1u};

                      ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

include/NAS2D/StringUtils.h: In function 'std::__cxx11::string NAS2D::string_format(const string&, Args ...) [with Args = {int, int}]':
include/NAS2D/StringUtils.h:40:30: warning: null destination pointer [-Wformat-truncation=]
   std::size_t size = snprintf(nullptr, std::size_t{0u}, format.c_str(), args...) + std::size_t{1u};

                      ~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

The code looks basically good. The destination pointer is `nullptr`, but the size is also `0`, so should be safe. The intention of the code is to calculate how much buffer space is needed, and then do an appropriate allocation before doing the operation for real.

Nevertheless, the warning should be eliminated somehow.

**Comment by cugone** [comment]
A quick google search shows this is a bug in GCC. If GCC has a way to ignore a specific warning a la `#pragma warning` like microsoft that would be ideal.

**Comment by DanRStevens** [comment]
I did some searching and didn't see anything concerning bugs for this specific issue. I did see a false bug report in a case where a user was legitimately triggering the warning by accident. Would appreciate a link concerning the actual supposed bug.

----

On another note, I found what looks to be the origin of the code for this method:
[`std::string` formatting like `sprintf`](https://stackoverflow.com/questions/2342162/stdstring-formatting-like-sprintf)

----

Looking at the code, I noticed it temporarily allocates an array of `char` as a working buffer, then copies that temporary array into a `std::string`. It would be possible to pre-allocate space for a `std::string` using [`resize`](https://en.cppreference.com/w/cpp/string/basic_string/resize), and then do the formatting directly to the `std::string`'s buffer.

For a bit of inspired reading:
[how to pre-allocate memory for a std::string object?](https://stackoverflow.com/questions/3303527/how-to-pre-allocate-memory-for-a-stdstring-object)

There would need to be some small adjustments for the null terminator, and staying within method specification, though the solution would something like:
```cpp
auto size = snprintf(nullptr, 0, ...); // +1?
std::string buffer;
buffer.resize(size);
snprintf(buffer.data(), buffer.size(), ...); // Writes null terminator within size, so size-1 bytes for data
return buffer; // Resize -1?
```

**Comment by ldicker83** [comment]
This method was effectively a copy/paste from Stack Exchange many years ago though it's not from the one you linked (I don't think) -- anyway, I never liked it but I needed a quick solution and viola, that was born.

I still think there's a better way to do this. As you mentioned, pre-allocating space in a `std::string` and then working on the `std::string` itself is a better solution than creating a temporary array, operating on that and then copying it into a `std::string`.

**Comment by cugone** [comment]
I ran this little snippet through compiler explorer. With `-Wformat-truncation` turned on from GCC (trunk) all the way down to GCC 8.1 and it generated neither errors nor warnings:

https://godbolt.org/z/4wFWX-

```
#include <cstdio>
#include <memory>
#include <string>
#include <vector>

template<typename... Args>
std::string string_format(const std::string& format, Args... args)
{
    static constexpr std::size_t buffer_size = 2048u;
    static char stack_memory_string[buffer_size];
    std::size_t req_size = std::snprintf(stack_memory_string, buffer_size, format.c_str(), args...);
    if(0 <= req_size && req_size < buffer_size) {
        stack_memory_string[req_size + 1] = '\0';
        return std::string{std::cbegin(stack_memory_string), std::cbegin(stack_memory_string) + req_size + 1};
    }
    if(req_size < 0) {
        return {};
    }
    std::vector<char> result{};
    result.resize(req_size + 1);
    result.back() = '\0';
    std::snprintf(result.data(), result.size(), format.c_str(), args...);
    return std::string{std::cbegin(result), std::cend(result)};
}

int main()
{
    std::string str = "YOUR NAME";
    std::string msg = string_format("Hi! %s", str);
}

```

**Comment by DanRStevens** [comment]
Ehh, I really don't like static buffer sizes. That's just asking for trouble.

**Comment by DanRStevens** [comment]
Actually, to be fair, upon closer examination, this looks similar to an idea I had.

The `std::string` is often implemented with a small string optimization. Allocations below that amount will not allocate external memory with `new`, but rather store the string in internally allocated buffers within the `std::string` object itself.

If we pre-allocate a `std::string` under the small string optimization size (dependent on compiler, though we could choose the minimum of the compilers we care about), then we can use that buffer for the initial `snprintf` run to determine the needed size. The code would be essentially the same as before, but passing a valid minimum sized buffer instead of `nullptr`.

----

Or, since it's now 2020, maybe we can look into using [`std::format`](https://en.cppreference.com/w/cpp/utility/format/format). We'd need to upgrade what compiler we use though, along with the standard setting to C++20. Maybe not quite time for that yet though, as I expect support will be lagging a bit. Unless we want to defer on this issue for a little while. :wink:

**Comment by cugone** [comment]
> 
> 
> Actually, to be fair, upon closer examination, this looks similar to an idea I had.
> 
> The `std::string` is often implemented with a small string optimization. Allocations below that amount will not allocate external memory with `new`, but rather store the string in internally allocated buffers within the `std::string` object itself.
> 
> If we pre-allocate a `std::string` under the small string optimization size (dependent on compiler, though we could choose the minimum of the compilers we care about), then we can use that buffer for the initial `snprintf` run to determine the needed size. The code would be essentially the same as before, but passing a valid minimum sized buffer instead of `nullptr`.
> 
> Another option might be to pass a potentially valid `std::string::data` buffer, but with size 0. Maybe that would be enough to get around the warning.
> 
> Or, since it's now 2020, maybe we can look into using [`std::format`](https://en.cppreference.com/w/cpp/utility/format/format). We'd need to upgrade what compiler we use though, along with the standard setting to C++20. Maybe not quite time for that yet though, as I expect support will be lagging a bit. Unless we want to defer on this issue for a little while. 😉

---

C++20 won't be standardized until later this year :crossed_fingers: and implemented by The Big Three until 2021 or later. :crossed_fingers: :crossed_fingers: 

---

MSVC defines "small" as 16 bytes. The above implements "small" as 2048 bytes. Beyond the "copy this buffer into the string" at the end which is a `std::memcpy` call it does no allocation. Personally, if you have to format a string that is 2KiB or larger, you have bigger problems.

I like the way the `std::format` is going but it's just too far in its infancy to be of use.

**Comment by DanRStevens** [comment]
Ok, I wrote up some unit tests for `string_format`.

I'll try some of the ideas presented here. If they work, I'll push everything together. If not, I'll push just the unit tests.
