### ISSUE TITLE
Rename Color_4ub

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#299]
Currently the name is pseudo-hungarian notation. It would be better to represent it as the order of bytes, specifically when dealing with low-level interfaces like DirectX where order matters. Another class could be created to convert to/from these required formats.

Suggest renaming the current implementation to `Rgba`. Other classes for specific formats (e.g. `Brga`) can be created along with an explicit conversion constructors if needed.

**Comment by DanRStevens** [comment]
For some reason, I was under the impression there was both a `uint8_t` variant of this, and a `float` variant of this. That doesn't seem to be the case.

I'd be tempted to just rename this to `Color` and be done with it. The code involved here is not low level enough to really care about color component ordering at the hardware level. We can leave that distinction to low level code where it really matters. From the high level interface to the library, one consistent format would likely make for an easier to use API.

My vote is to just rename to `Color`.

**Comment by ldicker83** [comment]
I'm okay with renaming this to simply Color. At the time I named this I was working with OpenGL and working with the function glColor4ub()... hence the 4ub.

Anyway, I'm in favor of making it simply Color and dropping the post-fixed implementation.
