### ISSUE TITLE
Change Color_4ub::White to Color_4ub::Normal in Renderer interface

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#301]
There are a couple of lines in the Renderer interface which use Color_4ub::White instead of Color_4ub::Normal. While they equate to the same thing the point of having Color_4ub::Normal is to indicate that there is no color tinting/transorm used.

**Comment by cugone** [comment]
I'm voting to close this. A white vertex color/texture is standard practice and understood to mean "no tinting" because math and multiplicative identity.

**Comment by cugone** [comment]
Tagging @DanRStevens

**Comment by DanRStevens** [comment]
I'm no expert in these matters, though the argument sounds reasonable. It doesn't seem like a large stretch to understand `Color::White` means do nothing. Maybe this can be documented where relevant.

From a non-expert perspective, I wouldn't automatically know that `Color::White` has the implication of do nothing, though I also wouldn't automatically know quite what `Color::Normal` really means either.
