### ISSUE TITLE
Examine Rectangle operator overloads and remove those that make no sense

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#303]
Related to #266, Rectangle includes a number of operator overloads that, when thought about, don't make a whole lot of sense.

Addition is simple enough though its implementation is dubious (it adds all of the internal components of both rectangles, shouldn't this be just width/height?) Same deal for subtraction.

Subtraction operation, though, can lead to rectangles with negative values, another case that doesn't make much sense.

It may make more sense to simply remove all overloaded operators except for the equivalency operators.

**Comment by DanRStevens** [comment]
I would support removing arithmetic operators on `Rectangle`. As you've pointed out, they don't make inherent sense.

Instead, I think `Rectangle` should provide ways to get corner `Point`s, or a size `Vector`. From there, arithmetic can be done on the `Point` and `Vector` components, which can then be used to create a new `Rectangle`.

As part of that, `Rectangle` should be constructible from either two `Point`s, or from a `Point` and a `Vector` (size).

**Comment by ldicker83** [comment]
These are good points but I think outside the scope of this changeset. I'll open a separate issue to handle these two cases.
