### ISSUE TITLE
Review `Timer` code

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#334]
~~The `Timer` class can probably have the explicit constructor removed and defaulted, and instead initialize member values inline in class declaration in the header file.~~ Edit: Done. (#335)

----

~~The member variable `mLastTick` can probably be moved to a local variable within the `delta()` method.~~ Edit: Done (#335)

----

Looking at `delta()` and `accumulate()`, it seems this class doesn't have one clear responsibility. Further, the `adjust_accumulator` method appears to break encapsulation. We may want to review the overall design and objectives of the class at some point.

**Comment by DanRStevens** [comment]
I went looking at how `Timer` code is used to gain a bit of context.

----

The `Timer` class contains the following public member functions:
```cpp
unsigned int tick() const;
unsigned int delta();

unsigned int accumulator();
void adjust_accumulator(unsigned int a);

void reset();
```

----

The `delta()` method is called from `Renderer`:
```
nas2d-core/src/Renderer/Renderer.cpp:219:	fadeTimer.delta();	// clear timer
nas2d-core/src/Renderer/Renderer.cpp:241:	fadeTimer.delta(); // clear timer
nas2d-core/src/Renderer/Renderer.cpp:519:		float fade = (fadeTimer.delta() * mFadeStep) * s
```

Within OPHD, it is called from:
```
src/States/SplashState.cpp:133:		unsigned int tick = BYLINE_TIMER.delta();
```

Curious how calls to `delta()` are commented with `// clear timer`. There is also a `reset()` method, which wasn't used in those contexts.

----

The `tick()` method is not called from within NAS2D:

Within OPHD, it is called from:
```
src/Map/TileMap.cpp:378:					int glow = 120 + sin(mTimer.tick() / THROB_SPEED) * 57;
src/States/SplashState.cpp:133:		unsigned int tick = BYLINE_TIMER.delta();
src/States/SplashState.cpp:140:		r.drawImageRotated(mFlare, static_cast<float>(_x) + 302 - 512, static_cast<float>(_y) + 241 - 512, BYLINE_TIMER.tick() / 600.0f);
src/States/SplashState.cpp:143:		BYLINE_SCALE += tick * BYLINE_SCALE_STEP;
src/States/SplashState.cpp:144:		BYLINE_ALPHA += tick * BYLINE_ALPHA_FADE_STEP;
src/States/PlanetSelectState.cpp:133:	float rotation = (mTimer.tick() / 125.0f);
src/States/PlanetSelectState.cpp:147:	float _rotation = mTimer.tick() / 1200.0f;
```

----

The `accumulate()` method is call from:
```
src/Resources/Sprite.cpp:143:		while (frame.frameDelay() > 0 && static_cast<int>(mTimer.accumulator()) >= frame.frameDelay())
src/Resources/Sprite.cpp:145:			mTimer.adjust_accumulator(frame.frameDelay());
```

Within OPHD, it is called from:
```
src/UI/Core/TextField.cpp:274:		if(mCursorTimer.accumulator() > CURSOR_BLINK_DELAY)
src/UI/Core/Slider.cpp:354:		if (mTimer.accumulator() >= mPressedAccumulator)
src/States/SplashState.cpp:101:	if (r.isFaded() && !r.isFading() && mTimer.accumulator() > FADE_PAUSE_TIME)
src/States/SplashState.cpp:154:		if (mTimer.accumulator() > 11000)
src/States/SplashState.cpp:160:	else if (mTimer.accumulator() > PAUSE_TIME)
src/States/PlanetSelectState.cpp:33:		if (mTimer.accumulator() > 7)
src/States/MapViewStateDraw.cpp:44:	if (GLOW_TIMER.accumulator() >= 10)
src/States/Planet.cpp:73:	if (mMouseInArea && mTimer.accumulator() >= constants::PLANET_ANIMATION_SPEED)
```

Within op2-landlord, it is called from:
```
src/StartState.cpp:390:	if (mTimer.accumulator() > 200)
src/TextField.cpp:163:		if(mCursorTimer.accumulator() > CURSOR_BLINK_DELAY)
src/Slider.cpp:257:		if (mTimer.accumulator() >= mPressedAccumulator)
```

----

The `adjust_accumulator()` method is called from:
```
src/Timer.cpp:56:void Timer::adjust_accumulator(unsigned int a)
src/Resources/Sprite.cpp:145:			mTimer.adjust_accumulator(frame.frameDelay());
```

----

The `reset()` method is called from:
```
src/Resources/Sprite.cpp:92:	mTimer.reset();
```

Within OPHD, it is called from:
```
src/UI/Core/TextField.cpp:276:			mCursorTimer.reset();
src/UI/Core/Slider.cpp:187:		mTimer.reset();
src/UI/Core/Slider.cpp:357:			mTimer.reset();
src/States/SplashState.cpp:79:		BYLINE_TIMER.reset();
src/States/SplashState.cpp:107:		mTimer.reset();
src/States/SplashState.cpp:163:		mTimer.reset();
src/States/PlanetSelectState.cpp:36:			mTimer.reset();
src/States/MapViewStateDraw.cpp:47:		GLOW_TIMER.reset();
src/States/Planet.cpp:66:		mTimer.reset();
src/States/Planet.cpp:75:		mTimer.reset(); // don't care about frame skips.
```

Within op2-landlord, it is called from:
```
src/StartState.cpp:393:		mTimer.reset();
src/TextField.cpp:165:			mCursorTimer.reset();
src/Slider.cpp:131:	mTimer.reset();
src/Slider.cpp:140:	mTimer.reset();
src/Slider.cpp:260:			mTimer.reset();
```

**Comment by ldicker83** [comment]
I think the Timer class can be used within an 'Accumulator' class versus having both functions within as they are mutually exclusive. E.g., if you're using the Timer as an accumulator, you're not checking the ticks or delta.

Or the Accumulator can be its own stand alone class without needing a Timer. Might make more sense to do it that way.

**Comment by DanRStevens** [comment]
Well I don't think we actually need a separate class. You can already "accumulate" with the `Timer` object by just not resetting the initial reference point.

The new class update is actually pretty much identical in function to the old one, just with renamed methods, and a cleaned up interior. That's something I came to realize when I re-added the `delta` method in #1061.
