### ISSUE TITLE
Rectangles with negative width or height

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#356]
We should discuss if we want to allow `Rectangle` to have negative `width` or `height`. Currently it is allowed. For a POD type with public fields, there would be no practical way to prevent it when the `BaseType` is a signed type. I think we should allow it.

We also need to be clear on what that means. It could mean a reversed `Rectangle`, which expands in the opposite direction. It could mean an empty `Rectangle`. I suppose this will depend on context. Some code would currently treat such a `Rectangle` as having no area, and so would effectively be `null`, but without having dimensions set to `0`.

We might want to consider putting checks in some places to handle negative sizes, or to map negative sizes to `0`. We may also choose to ignore this, and leave it up to the user if they want to deal with it.

This concern may also be a sign to add more method options. In particular, a `Rectangle` can be constructed from two `Point` objects. Normally the points would be specific corners in a specific order. It is however possible to use any two opposing corner points, in any order. Doing so would require a bit more work in the factory method though, such as sorting coordinates into min/max. It might also not be desired, since coordinates in the opposite order may indicate an empty area, rather than a positive area with the corner points swapped. This could be handled by providing two different methods, depending on what behaviour is desired.

Currently I'm inclined to somewhat ignore this concern until I hit a case that forces me to address it.

**Comment by cugone** [comment]
Not to sound like a broken record, but I'm going to advocate, again, the `mins,maxs` approach instead of `x,y,width,height` because this problem doesn't exist when using the former. Even with a constructor that takes a center and radius, and the radius accidentally being negative, it still works because internally every other value (dimensions, center, padding, etc) is derived:
```
Rectangle(Vector centerX, float radiusX, float radiusY)
: mins(center.x - radiusX, center.y - radiusY)
, maxs(center.x + radiusX, center.y + radiusY)
{ }
Rectangle::Translate(Vector translation) {
    mins += translation;
    maxs += translation;
}
Vector Rectangle::CalcDimensions() {
    return maxs - mins;
}
Vector Rectangle::CalcCenter() {
    return mins + (maxs - mins) * 0.5;
}
Vector Rectangle::SetPosition(Vector center) {
    const Vector2 half_extents = CalcDimensions() * 0.5;
    mins = center - half_extents;
    maxs = center + half_extents;
}
void Rectangle::AddPaddingToSides(float paddingX, float paddingY) noexcept {
    mins.x -= paddingX;
    mins.y -= paddingY;

    maxs.x += paddingX;
    maxs.y += paddingY;
}
//The following are dependent on the handedness of your library and how the viewport is set up, I'm assuming default windows/directX top-left origin instead of default OpenGL lower-left here.
void Rectangle::TopLeft() {
    const auto half_extents = CalcDimensions() * 0.5;
    const auto center = CalcCenter();
    return center + Vector(+half_extents.x, -half_extents.y);
}
void Rectangle::BottomLeft() {
    const auto half_extents = CalcDimensions() * 0.5;
    const auto center = CalcCenter();
    return center + Vector(-half_extents.x, +half_extents.y);
}
void Rectangle::TopRight() {
    const auto half_extents = CalcDimensions() * 0.5;
    const auto center = CalcCenter();
    return center + Vector(+half_extents.x, -half_extents.y);
}
void Rectangle::BottomRight() {
    const auto half_extents = CalcDimensions() * 0.5;
    const auto center = CalcCenter();
    return center + Vector(+half_extents.x, +half_extents.y);
}

```

**Comment by DanRStevens** [comment]
Looks like we can see uses for the following factory methods:
- `Rect::Create(Point startPoint, Vector size)`
- `Rect::Create(Point startPoint, Point endPoint)` (mins/maxs)
- `Rect::CreateFromCorners(Point point1, Point point2)` (Any opposite corner points, in any order)
- `Rect::CreateFromCenter(Point center, Vector halfExtents)` (Size or half extents)

----

I would argue the mins/maxs doesn't really eliminate the problem when you consider fields are public. If you require that one point contain the minimum x and y values, and the other the maximum x and y values, then you've imposed an invariant on a **`class`**. It is no longer a **`struct`**. If it really is implemented as a struct, with public fields, there is nothing stopping a user from going in and swapping points around so they're in opposite or mixed order. This is effectively the same situation as having negative `width` or `height` values.

For the `Point` and `radius` example, again, a negative radius effectively inverts the rectangle. Trying to prevent a negative radius would also mean a class invariant, and would require a private field.

----

If you use fixed formulas for the 4 corner points, the order of the 4 corner points can be manipulated by swapping the order, values, or signs of the `Rectangle` parameters.

**Comment by cugone** [comment]
>
>I would argue the mins/maxs doesn't really eliminate the problem when you consider fields are public.

The fields are only public for convenience of access due to the nature of a math-derived type and constantly having to refer to them. Under normal use cases, you would only construct and/or modify the object with the provided functions. Default constructing a null object then trying to modify the fields directly is rare.

**Comment by DanRStevens** [comment]
I think this discussion has concluded and this issue can be closed.

No action needed.

----

Ensuring a `Rectangle` has non-negative sizes amounts to maintaining an *invariant*.

A `struct` with public fields is not able (by itself) to maintain a strict invariant. A `class` with private fields is needed to maintain an invariant.

Whether or not we need any sort of invariant, such as positive sizes, is debatable, and I would say often not necessary or even desirable. Trying to maintain an invariant may actually get in the way for cases where it is not desired. As such, there isn't really a `Rectangle` level invariant, and so nothing to maintain. In the few cases where an invariant is desired, it can be left to the programmer to ensure the `struct` is used correctly to ensure the invariant. For typical cases, this seems quite easy and natural. Effectively we may ignore this concern at the `struct` level.
