### ISSUE TITLE
Move geometry files out of Renderer folder

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#358]
As mentioned in #352 (and possibly elsewhere), the `Renderer` folder is probably not the best place for some of the classes stored there. We should find a better more descriptive folder for:
- `Point`
- `Vector`
- `Rectangle`

Additionally, we may want to also consider moving:
- `Color`

----

I was originally thinking `Geometry/`, though another suggestion was simply `Math/`. Other suggestions welcome.

**Comment by DanRStevens** [comment]
Looking back at this, I'm thinking of creating a `Math/` folder containing:
- `Point`
- `Vector`
- `Rectangle`
- `MathUtils`
- `Trig`

**Comment by ldicker83** [comment]
I suppose it could be moved to Math/ but things like Point and Rectangle and Color are graphics primitives though they do also provide math utility. Primitives maybe?

Kind a head scratcher for me but I have no real preference on this -- anything that makes sense is okay with me.

**Comment by DanRStevens** [comment]
I think you're right about them being primitives. I was kind of tempted to put them at repository root, though things are already a bit cluttered there already.

There are a few places where `Point` and `Vector` are used outside the realm of graphics. Take for instance map tile indexing, rather than pixel indexing. The classes are perhaps more abstract and general and can be used in many contexts, graphics just being one strong use of them. I suppose if we ever got into physics calculations, they could be used there too.

The `Color` class I wasn't planning to move, since it's less clear where that would be used outside the realm of graphics. It doesn't seem to fit under Math.

**Comment by ldicker83** [comment]
Wouldn't fit there unless we added color blending methods to it.

Point/Vector/Rectangle can probably all be moved to Math since they fit better there now.
