### ISSUE TITLE
Add Vector scalar multiply and divide

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#360]
The `Vector` class should be given scalar multiply and divide operations:
- `Vector& operator*=(BaseType multiplier)`
- `Vector& operator/=(BaseType divisor)`
- `Vector operator*(BaseType multiplier) const`
- `Vector operator/(BaseType divisor) const`

This would be useful for scaling, direction reversal, linear interpolation, taking averages, or finding center points.

**Comment by cugone** [comment]
Along with this, adding left-side multiply is useful:

 - friend Vector operator*(BaseType lhs, const Vector<BaseType>& rhs) noexcept;

**Comment by DanRStevens** [comment]
Ah yes, I need to check on commutativity of the `Point + Vector` operation.

**Comment by DanRStevens** [comment]
I opened issue #362 to track the commutative properties separately, since it affects `+` and `*`.
