### ISSUE TITLE
Add Rectangle center method

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#361]
The `Rectangle` struct should be given a `center` method, which returns a `Point` for the center of the rectangle.
- `Point<BaseType> center() const`

**Comment by DanRStevens** [comment]
I just realized this method already exists. Looks like it was copied from the original `Rectangle_2d` class. What we need is not a method to return a center point, but a constructor to create a `Rectangle` from a center point. That is discussed somewhat in #356.

I'm going to close this.

**Comment by cugone** [comment]
Where? The only place the word `center` appears in `Rectangle.h` is in the component-wise `center_x` and `center_y` functions. There is no `center` function that returns a point.

**Comment by DanRStevens** [comment]
Ahh, right, I was reading too quickly.
