### ISSUE TITLE
Font.cpp AppVeyor warnings

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#368]
The following warnings are shown on AppVeyor for `Font.cpp`:
```
C:\projects\nas2d-core\src\Resources\Font.cpp(323): warning C26451: Arithmetic overflow: Using operator '+' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '+' to avoid overflow (io.2). [C:\projects\nas2d-core\proj\vs2019\NAS2D.vcxproj]
C:\projects\nas2d-core\src\Resources\Font.cpp(323): warning C26451: Arithmetic overflow: Using operator '*' on a 4 byte value and then casting the result to a 8 byte value. Cast the value to the wider type before calling operator '*' to avoid overflow (io.2). [C:\projects\nas2d-core\proj\vs2019\NAS2D.vcxproj]
```

Looking at the code, it seems the loop indexes `row` and `col` should be declared as `std::size_t`. The `GLYPH_MATRIX_SIZE` constant should perhaps also be declared as `std::size_t`. This may cause some cascaded changes to the `glyphWidth` and `glyphHeight` parameters to the method:
```
bool loadBitmap(const std::string& path, int glyphWidth, int glyphHeight, int glyphSpace)
```

**Comment by cugone** [comment]
Depending on the font implementation being used negative values for glyph dimensions are expected. BMFont is one example. SDL2 documentation on the `TFF_Font` family of functions on the other hand, gives no indication. So I think this is safe to change.

Might want to add an assert that the `glyphWidth` and `glyphHeight` are always sane values and never `std::size_t(-1)` or some ridiculously high value. That way there's at least some indication when the return values are negative.

**Comment by DanRStevens** [comment]
Hmm, interesting. Seems there are some aspect to fonts that I don't completely understand.

Perhaps reduce the suggested change to just the loop index variables `row` and `col`. Maybe leave the `GLYPH_MATRIX_SIZE` variable alone for now.
