### ISSUE TITLE
Build an ImageRectangle graphics primitive.

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#37]
Currently the Renderer has a function to draw rectangles that are textured. While this works it's really not the job of the Renderer to perform this function. Additionally, the current implementation requires references to individual image parts (basically 9 separate images) and is extremely inefficient.

That is where the ImageRectangle comes in. This class will replace the image rect function from the Renderer class.

### Related Tasks
Task #36
Task #38

**Comment by DanRStevens** [comment]
This makes sense. The task is accomplished by delegating to other simpler `Renderer` methods. It can be effectively implemented outside the `Renderer` class. In particular, none of the overloads are `virtual`, and there would be no reason to expect a `Renderer` specific implementation would provide higher efficiency.
