### ISSUE TITLE
Convert std::string filename/filepath arguments to FS::path

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#386]
This is a safety and portability issue. By using `FS::path` types instead of strings it avoids issues where denormalized string path separators do not equal each other and equality is required such as key searching:

`std::string::operator==` returns `false` for the below paths but `std::filesystem::path::equivalent` treats them as the equal because they all resolve to the same file.
```
data\\textures\\tiles.png
data/textures\\tiles.png
data/textures/normals/../tiles.png
data/textures/tiles.png
```
Ref: https://en.cppreference.com/w/cpp/filesystem/equivalent
Ref: https://en.cppreference.com/w/cpp/filesystem/path/operator_cmp

**Comment by cugone** [comment]
>
> One point of caution is the canonicalization methods are lagging on some compilers. If the `<experimental/filesystem>` headers are used, they might not be present at all.

Luckily they exist in the compilers being targeted on circleCI and AppVeyor. :)

**Comment by DanRStevens** [comment]
I've also been working on a Mingw-w64 build, which I think that would fail for.
