### ISSUE TITLE
Prefer in-class initalizers and only initialize class members that are actually passed in as arguments to the Ctor

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#387]
Related #385 

Ctors that do nothing but initialize class members in an initializer list can be simplified by having sensible defaults declared in the class header and the only members that are listed in the initializer list be the ones actually in the Ctor argument list.

Default Ctors can be completely removed and declared `=default` or `=delete` as needed as well.

**Comment by DanRStevens** [comment]
I believe this has been closed by PR #405.
