### ISSUE TITLE
Change Pre-build step to $(ProjectDir)../../InstallVcpkgDeps.bat

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#392]
This allows for downstream projects to not have to copy `InstallVcpkgDeps.bat` into their root folder.

Currently the value is `$(SolutionDir)../../InstallVcpkgDeps.bat` which is relative to the solution folder which is different for downstream projects and points to the root folder of their solution and not the inner NAS2D root folder.

**Comment by DanRStevens** [comment]
Reference: #353

**Comment by cugone** [comment]
That means the base NAS2D submodule for OPHD needs to be updated.

I made this issue because I had forgotten that #353 existed and was wondering why the project was still set to `$(SolutionDir)`

**Comment by DanRStevens** [comment]
Reference: https://github.com/ldicker83/OPHD/issues/146
