### ISSUE TITLE
FileLogger might be helpful

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#393]
I was looking at OPHD and noticed it used an odd hack to log to a file. A proper multi-threaded FileLogger class might be helpful to include in the engine.

**Comment by DanRStevens** [comment]
For reference, some logging code was added to the OP2Utility project.

Bit of a side point, it was supposed to be a quick and simple thing, though quite quickly became a fair bit of work to get right.

One of the problems was initialization order, and when it is safe to allow logging, and what to do if messages are logged before the setup point. Considering C++ has unspecified initialization order for globals from different translation units, that's a very real concern. Changing the order of object files passed to the linker can mean the difference between a working program, and mysterious crashes before main even starts. Object file ordering is not something that's typically set or transparent to developers.

Related to all that is the specification for the logging system. It sounds deceptively simple to specify something like logging, but there are actually some surprising things to consider and get right.

----

Though yes, logging support could be helpful.

**Comment by cugone** [comment]
Maybe adding an additional Application class that sits above the game might help. It's job is to create and keep references to all the systems that need to be alive during the game, including the game itself. The one I have is project specific but I've generalized it enough I could move it into my engine:

https://github.com/cugone/Roguelike/blob/master/Roguelike/Code/Game/App.hpp

https://github.com/cugone/Roguelike/blob/master/Roguelike/Code/Game/App.cpp

Notice that the two systems that absolutely must exist prior to anything else, the `JobSystem` and `FileLogger` (which itself is dependent on `JobSystem`) are created first followed by the other engine subsystems. Then they are Initialized in order and have their own calls for the beginning of the frame, the update, render, and endframe steps. The game itself is almost the last thing to get any attention next to the Renderer.

**Comment by DanRStevens** [comment]
The `Game` class sounds similar to what you're describing.

https://github.com/ldicker83/OPHD/issues/146

It probably needs a bit of work though. I don't think it was used by OPHD, since customizations were needed that the class didn't support well.

**Comment by cugone** [comment]
Not really. The Game instance would live inside the Application.

The Application class is the entry point for the overall program (think main or WInMain) and creates the game instance and any subsystems in the correct order that are required; followed by destroying them on program exit. This fixes the problem of the static initialization order fiasco and makes sure subsystems are created and initialized before use and remain available for the game instance to use.

**Comment by DanRStevens** [comment]
I'm looking back at this from a cost/benefit standpoint. Seems like this would add some bloat to the library, though the corresponding value added is unclear. Currently there is not much in the way of logging needs. Running downstream projects produces maybe a screen worth of logging or less.

On top of that, logging needs are often quite specific to the application. That's one reason why I want to push log messages out of the library so the app developers can have better control over logging.

I think any logging improvements should perhaps be done in the downstream projects first. If it proves useful and generic, we might then consider moving it from the downstream project to the library itself.

My guess though, is the downstream projects don't have a whole lot of need in terms of logging. Even less so of advanced multithreaded logging, as was proposed in #395.

I'm thinking this should be closed as not an area that's a priority for us right now.
