### ISSUE TITLE
Minimum windows requirements

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#394]
I'd really like to use the modern threading interface API that Microsoft highly recommends using going forward. The problem with using it is it requires Windows 10 version 1607 or later.

Requiring users to have Windows 10 isn't a big deal, I think, because as of last week, Windows 7 is no longer supported and Windows 8 and 8.1 are nearly universally despised by windows users.

Thoughts?

Ref: https://arstechnica.com/information-technology/2020/01/windows-7-im-not-dead-yet/
Ref: https://support.microsoft.com/en-us/help/13853/windows-lifecycle-fact-sheet

Ref: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-getthreaddescription
Ref: https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setthreaddescription

**Comment by DanRStevens** [comment]
First question, what would it be used for? I'm not aware of any features for a turn based game that really need much in the way of threading. Music playback maybe?

----

C++ has some recent additions to the standard library for threading. We should probably look there first, before going to something platform specific, especially if it's tied to only the latest version of the Windows platform.

**Comment by cugone** [comment]
To answer your first question, it allows for interfacing with threads as one line of code as seen here:  https://github.com/lairworks/nas2d-core/blob/4ce53bdd3bcfb9182a9f1c783d3c15025fb9ee44/src/ThreadUtils.cpp#L134 which is in line with how `pthreads` does on linux: https://github.com/lairworks/nas2d-core/blob/4ce53bdd3bcfb9182a9f1c783d3c15025fb9ee44/src/ThreadUtils.cpp#L156

Additionally, just because the game being written is turn-based doesn't mean things can't be happening in the background prior to the user clicking next turn:
 - Audio must be handled as a multi-threaded resource or you get stuttering and clicking and deaf users.
 - Real-time File logging
 - A Job System can spin up threads for generic jobs that may be handled asynchronously.
  - Saving the game using a job won't lock up the game.
  - Saving any file, actually...
  - Exporting screenshots is much smoother
 - AI and game state can be updated in the background instead of waiting for it to process all at once.

---
To your second: The C++ `<thread>` library does not support setting/getting thread descriptors, that must be handled on an OS-by-OS case using the `std::thread::native_handle()` call, which I am doing in the aformentioned ThreadUtils and it is used in the FileLogger to name the thread for easy debugging: https://github.com/lairworks/nas2d-core/blob/8e8f5c8dadca032f8d14dab57c8fa1f99bcf6c2a/src/FileLogger.cpp#L76

**Comment by DanRStevens** [comment]
Of those reasons, I only find the audio one particularly compelling.

Perhaps as a consequence of that, I don't see much value in having textual thread descriptors.

I've also never encountered a case where logging was a sufficient burden so as to need its own thread.

This seems like it's adding a lot of complexity without a corresponding amount of benefit.

**Comment by cugone** [comment]
> 
> I've also never encountered a case where logging was a sufficient burden so as to need its own thread.

I/O by its very nature is a blocking call and very slow. Threading mitigates this. If you've never profiled your code where you are logging call stacks that output potentially hundreds of times per frame, you wouldn't notice.

**Comment by DanRStevens** [comment]
That strikes me as more of a concern for real time strategy games or first person shooters, and only really when logging is significant, which I would only expect while debugging.

Case in point, I don't ever expect to be logging hundreds of messages per frame.

**Comment by DanRStevens** [comment]
I suppose to add to that, evented I/O would probably be preferred in the cases where it was important. Same effect in terms of concurrency, but less overhead from context switches.

**Comment by DanRStevens** [comment]
Looking back at this, I would like to avoid features that lock us in to the latest version of an OS for distribution purposes. (For development tools it's a different matter, since we have control of our own systems).

In particular, this library is being used on projects that might reasonably be expected to run on really old computers, which may be outdated. In particular, it is known people tend to run OSes long after the support period for the OS has ended. We don't need to officially support such old OSes, but we should avoid going out of our way to make code incompatible for them.

More to the point, the potential benefits of the proposed change are unlikely to be realized in any *significant* way given our current goals. As such, the added complexity is not really justified.

I'm thinking this should be closed as an area we're not looking to explore at this time.
