### ISSUE TITLE
Review Resource class hierarchy design

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#401]
The `Resource` class is used as a base class, however, the only public `virtual` method is the destructor. This is a suspicious design. It seems to impose implementation details on subclasses, while not really providing an interface to access them through. We should perhaps review this class hierarchy and see if we can come up with a better design.

In particular, we should have `virtual` methods to support the implied interface, and try to move implementation details to derived classes, or perhaps a mixin style base class.

**Comment by ldicker83** [comment]
My original thinking on this is that these are all 'assets' used by the engine... ultimately none of them are really very similar to each other and don't really have a common interface except for getting a 'name' which is effectively just the file path and filename.

The hierarchy can probably be dropped altogether as each is implemented very differently.
