### ISSUE TITLE
vcpkg on Linux/MacOS

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#407]
vcpkg has CMake support.

Would this be a good idea to use vcpkg on Linux/MacOS for non-library-based installs such as TinyXML2 and stb? The only other way I can see to install on every platform is a direct inclusion of the source code into the project.

Ref: https://github.com/microsoft/vcpkg/blob/master/docs/users/integration.md#cmake-toolchain-file-recommended-for-open-source-cmake-projects

**Comment by DanRStevens** [comment]
It's easier and faster to use the system provided packages on Linux. Using `brew` on MacOS is probably similar to using `vcpkg`. At any rate, I would prefer using native platform tools to install dependencies when possible. It makes for a better integrated experience for people using those systems.

For reference: The Linux TinyXML2 development package is `libtinyxml2-dev`.

**Comment by DanRStevens** [comment]
I'm thinking this can probably be closed now.

In summary, we use the following preferred ways to install dependencies:
- Windows: `vcpkg`
- MacOS: `brew`
- Linux: Native package manager, dependent on distribution
  - Ubuntu: `apt` (main supported distribution)
  - Centos: `yum`
  - Arch: `pacman`
