### ISSUE TITLE
Add normalized audio volume getters and setters to Configuration and Mixer

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#415]
In order to facilitate abstractions from different audio implementations, `Configuration` and `Mixer` should provide volume setters that take normalized values and getters that return the volume as a normalized value.

Derived classes can then denormalize or rangemap the values based on their own implementations. E.g. SDL_mixer uses [0,128], while XAudio2 (modern Windows API) uses [-1.0,1.0].

Additionally, SDL uses the same setter with a value of `-1` to mean "don't set it, I just care about the current value.", while XAudio2 uses a dedicated getter.

Ref: https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC27
Ref: https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC61
Ref: https://docs.microsoft.com/en-us/windows/win32/api/xaudio2/nf-xaudio2-ixaudio2voice-setvolume
Ref: https://docs.microsoft.com/en-us/windows/win32/xaudio2/xaudio2-volume-and-pitch-control
Ref: https://docs.microsoft.com/en-us/windows/win32/xaudio2/how-to--change-voice-volume

**Comment by DanRStevens** [comment]
One caveat is that if we always interface to audio through SDL, then it sort of doesn't matter what the platform implementation is. Using floating point would then be converted to integer for SDL, which may or may not be converted back to floating point to interface to the platform's native system.

Other than that, this sounds like a reasonable change. Would be curious if Leeor wanted to weigh in on this.
