### ISSUE TITLE
Consider removing the clang-format file.

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#422]
I spent more time fighting with the automatic changes clag-format makes to the whitespace of a file every time I type a curly brace or paste code than I'd like.

I'd be glad to remove it, but that means that my global Visual Studio settings will take over. That means spaces instead of tabs. And that's not the consistency required for this code base.

**Comment by DanRStevens** [comment]
If it's causing trouble, it should probably be removed.

Potentially it can be added back piece meal, with just the minimal fixes that are needed. Perhaps it can have just a single setting to use tabs instead of spaces.

**Comment by cugone** [comment]
Turning on `Run ClangFormat only for manually invoked formatting commands` in `Tools > Options > Text Editor > C/C++ >Formatting > General > ClangFormat execution` has made life easier as the whole file isn't formatted unless I choose to.
