### ISSUE TITLE
No way to test graphics code visually

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#427]
I just implemented #27 but I have no way to test it.

Creating a test application that we could use to test graphics code visually and/or locally would be nice.

I don't know if it should live here or in a separate repo though.

**Comment by cugone** [comment]
I just noticed the nas2d-tests repo, https://github.com/lairworks/nas2d-tests, but it's nearly a year out of date.

Maybe including the graphics test app in this repo will allow testing up-to-date versions of NAS2D.

**Comment by DanRStevens** [comment]
Looks like this was closed by #465.
