### ISSUE TITLE
XML configuration file format

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#430]
I was looking at an XML configuration file:
```xml
<!--Automatically generated Configuration file.-->
<configuration>
	<graphics screenwidth="1000" screenheight="700" bitdepth="60" fullscreen="false" vsync="false" />
	<audio mixrate="22050" channels="2" sfxvolume="128" musicvolume="128" bufferlength="1024" mixer="SDL" />
	<options>
		<option name="maximized" value="false" />
		<option name="skip-splash" value="true" />
	</options>
</configuration>
```

I noticed the `<options>` section doesn't follow the same format as the other section. If it did, it might end up looking more like:
```xml
<options maximized="false" skip-splash="true" />
```

Was there a particular reason for the change in format? I was thinking about writing more generic parsing code. Having a more consistent format could make that easier.

On the other hand, a clearer description of why the difference was chosen might also be helpful.

It might come down to simply being "because the programmer or file format said so". In which case, the kind of parsing needed could be decided at a higher level, and there could be two types of parsers, depending on which section you are trying to parse.

----

Ultimately, it seems configuration data is stored in sections, where each section consists of key/value pairs. We could potentially represent parsed data as key/value string pairs using a `std::map`.

Granted, the choice of strings for the value is largely due to the text file format, where all data must be serialized to/from string format. Some of those values actually represent integers or booleans, so there needs to be a bit of support for converting between such basic types and the storage format. The interface the game actually cares about is with the proper data types.

**Comment by cugone** [comment]
We could just drop XML entirely and use raw key-value pairs for config files:
```
#Automatically generated Configuration file.

#Graphics Options
screenwidth=1000
screenheight=700
refreshRate=60
fullscreen=false
vsync=false
maximizedwindow=false

#Audio options
audiomixrate=22050
audiochannels=2
sfxvolume=128
musicvolume=128
bufferlength=1024
mixer=SDL

#Game options
skipsplash=true
```

**Comment by DanRStevens** [comment]
Yes, our needs for the configuration data are simple enough that an `.ini` file would suffice.

The `Sprite` data I believe is more involved, and probably wouldn't work so well with a flat format like `.ini`. We likely need either XML or JSON for that.

For now though, I want to avoid large format changes. I want to work on the API used to read configuration data, and only once that is abstracted enough do I want to worry about changing the internal format.

Which I suppose answers my own question. If current configuration files are written this way, and exist in that format on end user systems, we should probably stick with that format for now. Changing the config file format could break things for people who are currently testing the game. The config file is outside the scope of release packages, so wouldn't be overwritten by a new install. That may mean careful consideration to what happens in the `Configuration` class if an old configuration file format is found.

For the sake of end users, if we're going to change the format a little, maybe we should wait until we're ready to change it all the way, and perhaps convert to `.ini` files.

**Comment by cugone** [comment]
> The `Sprite` data I believe is more involved, and probably wouldn't work so well with a flat format like `.ini`. We likely need either XML or JSON for that.

Yes. Absolutely. I should have been more clear, I was only referring to the config files and nothing else.

**Comment by DanRStevens** [comment]
From an external discussion, it seems the difference in format was originally chosen to support unknown parameter names. Hence the parameter name ended up being a value accessed through the known `name` attribute.

Given the structure of the XML code, this distinction is not strictly necessary. The XML code allows reading arbitrary attribute names, and provides them in string form. As such, the original format could still be used for unknown parameter names.

----

Given the above, it seems we could reasonably change the file format to make things consistent. However, we might also consider that configuration files in the existing format are already out in the wild, so it may be wise to keep some support for them, at least for reading, so it doesn't negatively impact player experience.

What could be done is to write code to parse both formats, while perhaps only writing a single format, causing existing files to be updated to a newer consistent format.

----

Given the nature of the format is better understood now, I'm going to close this discussion.
