### ISSUE TITLE
Add XML Validation

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#434]
Add a validation function that verifies an XML element for correctness.
```
void ValidateXmlElement(const XMLElement& element,
                        const std::string& name,
                        const std::string& requiredChildElements,
                        const std::string& requiredAttributes,
                        const std::string& optionalChildElements = std::string{},
                        const std::string& optionalAttributes = std::string{}) noexcept;
```
 The function should:
- [x] Verify the name is correct. Pop an error dialog then exit the program if the names do not match.
- [x] Ensure all required child elements exist. Pop an error dialog then exit the program if an element is missing.
- [x] Ensure all required attributes exist. Pop an error dialog then exit the program if an attribute is missing.
- [x] Verify any extra child elements are in the optional list. Pop a warning dialog and/or log in debug mode, but otherwise ignore extra elements.
- [x] Verify any extra attributes are in the optional list. Pop a warning dialog and/or log in debug mode, but otherwise ignore extra elements.

**Comment by DanRStevens** [comment]
Could you maybe give a motivating example of why and how this would be used?

I noticed the current XML parsing code does a bit of validation while parsing. I suppose it could be checked up front, though I don't know it would necessarily be easier that way.

Actually, in terms of the `Configuration` code, I wonder if things might be re-written to have less error checking code, and instead just have things work in a sensible way if settings are missing or out of range.

I haven't really looked much at the `Sprite` XML code, and haven't given much consideration to other potential uses of XML.

**Comment by cugone** [comment]
As you said, it allows for inline validation during loading. With this function `Configuration::readConfig` becomes: (continued at bottom)

```
bool Configuration::readConfig(const std::string& filePath) {
	File xmlFile = Utility<Filesystem>::get().open(filePath);

	XmlDocument config;
	config.parse(xmlFile.raw_bytes());
	if (config.error()) {
		std::cout << "Error parsing configuration file '" << filePath << "' on Row " << config.errorRow() << ", Column " << config.errorCol() << ": " << config.errorDesc() << std::endl;
		return false;
	}
	
	if(auto* root = config.RootElement()) {
		DataUtils::Xml::ValidateXmlElement(*root, "configuration", "graphics,audio,options", "");
		
		//graphics, audio and options child elements are required and have already been checked at this point, so there's no need to check them again.
		auto* xml_graphics = root->FirstChildElement("graphics");
		parseGraphics(*xml_graphics);
		
		auto* xml_audio = root->FirstChildElement("audio");
		parseAudio(*xml_audio);
		
		auto* xml_options = root->FirstChildElement("options");
		parseOptions(*xml_options);
		
		return true;
	}
	return false;
}

void Configuration::parseGraphics(XmlElement& element)
{
	DataUtils::Xml::ValidateXmlElement(element, "graphics", "", "screenwidth,screenheight,bitdepth,fullscreen,vsync");
	
	//current element, attribute name, default value
	mScreenWidth = DataUtils::Xml::ParseXmlAttribute(element, GRAPHICS_CFG_SCREEN_WIDTH, mScreenWidth);
	mScreenHeight = DataUtils::Xml::ParseXmlAttribute(element, GRAPHICS_CFG_SCREEN_HEIGHT, mScreenHeight);
	mScreenBpp = DataUtils::Xml::ParseXmlAttribute(element, GRAPHICS_CFG_SCREEN_DEPTH, mScreenBpp);
	mVsync = DataUtils::Xml::ParseXmlAttribute(element, GRAPHICS_CFG_VSYNC, mVsync);
	mFullscreen = DataUtils::Xml::ParseXmlAttribute(element, GRAPHICS_CFG_FULLSCREEN, mFullscreen);
}

void Configuration::parseAudio(XmlElement& element)
{
	DataUtils::Xml::ValidateXmlElement(element, "audio", "", "mixrate,channels,sfxvolume,musicvolume,bufferlength,mixer");

	mMixRate = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_MIXRATE, mMixRate);
	if(!(mMixRate == AUDIO_LOW_QUALITY || mMixRate == AUDIO_MEDIUM_QUALITY || mMixRate == AUDIO_HIGH_QUALITY))
	{
		std::cout << "Invalid audio mixrate setting '" << mMixRate << "'. Expected 11025, 22050 or 44100. Setting to default of 22050." << std::endl;
		mMixRate = AUDIO_MEDIUM_QUALITY;
	}
	
	mStereoChannels = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_CHANNELS, mStereoChannels);
	if(!(mStereoChannels == AUDIO_MONO || mStereoChannels == AUDIO_STEREO))
	{
		std::cout << "Invalid audio channels setting '" << mStereoChannels << "'. Expected 1 or 2. Setting to default of 2." << std::endl;
		mStereoChannels = AUDIO_STEREO;
	}
	
	mSfxVolume = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_SFX_VOLUME, mSfxVolume);
	mSfxVolume = std::clamp(AUDIO_SFX_MIN_VOLUME, AUDIO_SFX_MAX_VOLUME);

	mMusicVolume = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_MUS_VOLUME, mMusicVolume);
	mMusicVolume = std::clamp(mMusicVolume, AUDIO_MUSIC_MIN_VOLUME, AUDIO_MUSIC_MAX_VOLUME);

	mBufferLength = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_BUFFER_SIZE, mBufferLength);
	mBufferLength = std::clamp(mBufferLength, AUDIO_BUFFER_MIN_SIZE, AUDIO_BUFFER_MAX_SIZE);
	
	mMixerName = DataUtils::Xml::ParseXmlAttribute(element, AUDIO_CFG_MIXER, mMixerName);
	
}

void Configuration::parseOptions(XmlElement& element)
{

	DataUtils::Xml::ValidateXmlElement(element, "options", "option", "");

	for (auto& option : GetChildElements(element)))
	{
		DataUtils::Xml::ValidateXmlElement(option, "option", "", "name,value");

		std::string name = DataUtils::Xml::ParseXmlAttribute(option, "name", "");
		std::string value = DataUtils::Xml::ParseXmlAttribute(option, "value", "");

		if (name.empty() || value.empty())
		{
			std::cout << "Invalid name/value pair in <option> tag in configuration file on row " << option->row() << ". This option will be ignored." << std::endl;
			continue;
		}

		mOptions[name] = value;
	}
}
```

Notice this is much cleaner and contains no XML-related validation; only value-related validation in case the user puts a bad valid in the XML file.

Similarly for `Sprite` the code is much easier to follow and the only error checking being done is directly related to the element being parsed:
```
void Sprite::processXml(const std::string& filePath)
{
	Filesystem& fs = Utility<Filesystem>::get();

	if (!fs.exists(filePath))
	{
		cout << "Sprite file '" << filePath << "' doesn't exist." << endl;
		addDefaultAction();
		return;
	}

	File xmlFile = fs.open(filePath);

	// Load the file
	if (xmlFile.empty())
	{
		cout << "Sprite file '" << filePath << "' is empty." << endl;
		addDefaultAction();
		return;
	}

	XmlDocument docXml;
	docXml.parse(xmlFile.raw_bytes());
	if (docXml.error())
	{
		cout << "Malformed XML. Row: " << docXml.errorRow() << " Column: " << docXml.errorCol() << ": " << docXml.errorDesc() << " (" << name() << ")" << endl;
		addDefaultAction();
		return;
	}
	
	if(auto* xml_root = docXml.RootElement())
	{
		DataUtils::Xml::ValidateXmlElement(*root, "sprite", "imagesheet,action", "version");
		auto version = DataUtils::Xml::ParseXmlAttribute(*root, SPRITE_VERSION, "");
		if(version != SPRITE_VERSION)
		{
			cout << "Sprite version mismatch (" << versionString() << ") in '" << filePath << "'. Expected (" << SPRITE_VERSION << ")." << endl;
			addDefaultAction();
			return;
		}
		
		auto* xml_imagesheet = xml_root->FirstChildElement(xml_root, "imagesheet");
		processImageSheets(*xml_imagesheet);
		
		for(auto& action : GetChildElements(*xml_root, "action"))
		{
			processActions(action);
		}
	}
}

void Sprite::processImageSheets(XMLElement& element)
{
	DataUtils::Xml::ValidateXmlElement(element, "imagesheet", "", "id,src");
	std::string id = DataUtils::Xml::ParseXmlAttribute(element, "id", "");
	std::string src = DataUtils::Xml::ParseXmlAttribute(element, "src", "");
	//addImageSheet no longer needs to verify the node internally.
	addImageSheet(id, src, element);
}

void Sprite::addImageSheet(const std::string& id, const std::string& src, XmlElement& element)
{
	Filesystem& fs = Utility<Filesystem>::get();

	// Search for an image sheet with 'id'. If not found, add it.
	auto found_iter = mImageSheets.find(toLowercase(id));
	if(found_iter != mImageSheets.end())
	{
		cout << "Image-sheet redefinition '" << id << "'." << endTag(element->row(), name()) << ". Imagesheet ignored." << endl;
		return;
	}

	std::string imagePath = fs.workingPath(mSpriteName);
	imagePath += src;
	if (!fs.exists(imagePath))
	{
		cout << "Couldn't find '" << imagePath << "' defined in sprite file '" << name() << "'." << endl;
		mImageSheets[toLowercase(id)]; // Add a default image
		return;
	}
	
	mImageSheets[id] = Image(imagePath);
}

void Sprite::processActions(XmlElement& element)
{
	DataUtils::Xml::ValidateXmlElement(element, "action", "frame", "name");

	std::string name = toLowercase(DataUtils::Xml::ParseXmlAttribute(element, "name", ""));
	if(name.empty())
	{
		std::cout << "Zero-length 'name' value in Action definition." << endTag(element.row(), name()) << endl;
		return;
	}
	
	auto found_iter = mActions.find(name);
	if(found_iter != mActions.end())
	{
		cout << "Redefinition of action '" << action_name << "'. First definition will be used." << endTag(element.row(), name()) << endl;
		return;
	}

	FrameList frameList;
	for(auto& frame : GetEachChildElement(element, "frame"))
	{
		auto frame = processFrame(action_name, frame);
		frameList.push_back(frame);
	}
	mActions[name] = frameList;
}

SpriteFrame Sprite::processFrame(const std::string& action, XmlElement& element)
{
	DataUtils::Xml::ValidateXmlElement(element, "frame", "sheetid,delay,x,y,width,height,anchorx,anchory", "");

	std::string id = DataUtils::Xml::ParseXmlAttribute(element, "id", "");
	int delay = DataUtils::Xml::ParseXmlAttribute(element, "delay", 0);
	int x = DataUtils::Xml::ParseXmlAttribute(element, "x", 0);
	int y = DataUtils::Xml::ParseXmlAttribute(element, "y", 0);
	int w = DataUtils::Xml::ParseXmlAttribute(element, "width", 0);
	int h = DataUtils::Xml::ParseXmlAttribute(element, "height", 0);
	int anchorx = DataUtils::Xml::ParseXmlAttribute(element, "anchorx", 0);
	int anchory = DataUtils::Xml::ParseXmlAttribute(element, "anchory", 0);

	if(!validateSheet(id)) { return; }

	auto curr_sheet = mImageSheet.find(id);
	auto curr_width = curr_sheet->second.width();
	auto curr_height = curr_sheet->second.height();
	auto element_row = element.row();
	if(x < 0 || x > curr_width)
	{
		cout << "Value 'x' is out of bounds." << endTag(element_row, name()) << endl;
		return;
	}
	if(y < 0 || y > curr_height)
	{
		cout << "Value 'y' is out of bounds." << endTag(element_row, name()) << endl;
		return;
	}
	if(width < 1)
	{
		cout << "'width' value must be greater than 0." << endTag(element_row, name()) << endl;
		return;
	}
	if(x + width > curr_width)
	{
		cout << "'x' + 'width' value exceeds dimensions of specified imagesheet." << endTag(element_row, name()) << endl;
		return;
	}
	if(height < 1)
	{
		cout << "'height' value must be greater than 0." << endTag(element_row, name()) << endl;
		return;
	}
	if (y + height > curr_height)
	{
		cout << "'y' + 'height' value exceeds dimensions of specified imagesheet." << endTag(element_row, name()) << endl;
		return;
	}
	return SpriteFrame(sheetId, x, y, width, height, anchorx, anchory, delay);
}
```

**Comment by DanRStevens** [comment]
There's something about this approach that feels a bit unsatisfying. It processes the XML data twice. It does one pass to validate it's of a certain format, then does a second pass, with error checking removed, assuming the data is already in the proper format, and parses it. In this way, the error checking of the XML is divorced from the XML processing. Additionally, the program specific rules are still blended into XML processing code.

Ideally, I would like to see XML parsing and error checking done together, perhaps to a neutral data structure such as a `std::map` of key/value pairs, while the program specific data is then separated from any XML processing code, using only already parsed data.

One of the benefits of such an approach is the program specific data rules then become quite independent of the file format. Any data format that could be parsed to the `std::map` data structure would then be used to load data.

Not everyone loves XML. If someone wanted to use JSON instead, or an INI file, they could have that option.

**Comment by cugone** [comment]
Trying to be generic enough that the validation also validates the actual game-specific values is nearly impossible due to the infinite number of possible values. So the function doesn't try. Leave that as "it's up to the business logic."

Supporting JSON is a separate issue, (I'd recomment [nlohmann's josn library](https://github.com/nlohmann/json) anyway) and so is raw `key=value` pair `.ini` files (trivial, though).

**Comment by cugone** [comment]
Also, as stated on TinyXML's github, neither TinyXML1 nor TinyXML2 support validation through Schemas. It's no the intent of the library. The intent of the library is to be fast and portable specifically for game development.

**Comment by DanRStevens** [comment]
I wasn't trying to state that JSON or INI file support should be part of this PR. Rather I was trying to set the intent for the direction we want to evolve this code. I don't think the changes here are quite in line with the intent I have for this code.

I'm also not saying the parser should ever try to validate program specific values. I'm saying that part of validation should be separated from the parsing code.

Here the program specific code is still tied to XML parsing, while validation of XML structure is now separate from XML parsing. I don't think that's the direction we want to go.

I think XML data should be parsed in a very generic way, to a standard format. XML specific parse errors should be tied to XML parsing code. Validation of what values should have been parsed, or range checking the values that are parsed should be entirely separate from the parse step, and should not have any direct interaction with XML specific code.

For example, parse XML data to a `std::map` of key/value pairs. Then validate the `std::map` to ensure it has expected keys, and that values are in range.

**Comment by cugone** [comment]
The program-specific code still being tied to XML is a consequence of only supporting that format. If you want it to support more, it's a matter of adding functions to the class to parse that expected data format.

For example, the font exporter I use in my engine, [BMFont](https://www.angelcode.com/products/bmfont/), can be exported as [Text, XML, or Binary](https://www.angelcode.com/products/bmfont/doc/export_options.html) so when loading my fonts I have a way to detect the difference and then choosing the correct [loading function](https://github.com/cugone/Abrams2019/blob/159b8d0702a063456da699a878cb89ec9a0bcd1d/Engine/Code/Engine/Core/KerningFont.cpp#L131)

**Comment by DanRStevens** [comment]
To elaborate on this idea, I think parsing should be done in a function such as:
```cpp
Dictionary parseXmlAttributes(const XmlElement& element);
```

The `Dictionary` might be an alias or wrapper for `std::map<std::string, std::string>`. It would be a collection of key/value string pairs. The reason why I suggest a wrapper type, is we may want to read integer or boolean values from those strings, and so we could support custom type converting getter methods.

Once the `Dictionary` type is parsed, we then read values from it, as a specific data type, and with optional defaults.

```cpp
auto someString = dictionary.get("someString"); // Default type is string
auto someFlag = dictionary.get<bool>("someFlag"); // Convert to bool, no default
auto someValue = dictionary.get<int>("someValue", 500); // Convert to int, default is 500
auto clampedValue = std::clamp(dictionary.get<int>("clampedValue"), 0, 100); // Clamped to 0..100
```

----

If at some point in the future, you want to parse from .ini files, you create a method:
```cpp
Dictionary parseIniSection(const std::string& iniFile, const std::string& iniSection);
```

All the rest, of the code can remain untouched. There are no changes needed for type conversions, default values, clamping, or any other data validation, as it would be completely separate from the data parsing.

**Comment by DanRStevens** [comment]
Forgot to mention, in terms of validating which fields are present against which are required or optional, I think that should also be done after parsing, on the `Dictionary` object. Again, this is so the validation is independent of the input format.

```cpp
auto keySet = std::set<std::string>(dictionary.keys);
auto missingRequiredKeys = RequiredKeySet - keySet;
if (!missingRequiredKeys.empty()) {
  throw std::runtime_error("Missing required keys: " + format(missingRequiredKeys));
}
auto unknownKeys = keySet - RequiredKeySet - OptionalKeySet;
if (!unknownKeys.empty()) {
  // Warn about extra unknown keys
}
```

**Comment by cugone** [comment]
XML support is being dropped.
