### ISSUE TITLE
Game calls SDL_Quit but not SDL_Init

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#446]
The `Game` class calls `SDL_Quit` in the destructor, but has no corresponding `SDL_Init` in the constructor.

----

SDL documentation references:
[`SDL_Init`](https://wiki.libsdl.org/SDL_Init)
[`SDL_Quit`](https://wiki.libsdl.org/SDL_Quit)
[`SDL_InitSubSystem`](https://wiki.libsdl.org/SDL_InitSubSystem)
[`SDL_QuitSubSystem`](https://wiki.libsdl.org/SDL_QuitSubSystem)

**Comment by DanRStevens** [comment]
Tagging #701 as likely related.

**Comment by ldicker83** [comment]
I believe Init is done in the Renderer. It's not intuitive and I'm game for finding a better way to do this.

**Comment by DanRStevens** [comment]
Tagging #810 as possibly related.
