### ISSUE TITLE
Add getClosestMatchingDisplayMode

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#471]
Wraps the `SDL_GetClosestDisplayMode` as below. It removes the need to declare the implementation-specific `extern SDL_Window* underlyingWindow;` in game code.
```
NAS2D::DisplayDesc getClosestMatchingDisplayMode(const DisplayDesc& preferred)
{
    const auto display_index = SDL_GetWindowDisplayIndex(underlyingWindow);
    SDL_DisplayMode desired{preferred.width, preferred.height}; //Filter by resolution only. Default other members to desktop.
    SDL_DisplayMode closest{};
    if(SDL_GetClosestDisplayMode(display_index, &desired, &closest))
    {
        return NAS2D::DisplayDesc{closest.w, closest.h, closest.refreshRate};
    }
    const auto err_str = std::string{__FUNCTION__} + " no closest matching display mode available."
    throw std::runtime_error(err_str);
}
```

**Comment by DanRStevens** [comment]
The code looks alright. I'm having a bit of trouble understanding the context. I assume this would be used from the options menu. Is this to remove the `extern` declaration from the options menu code? I've noticed the same `extern` declaration is used in other places as well.

Is this replacing existing behaviour, or to extend behaviour?

**Comment by cugone** [comment]
It's wrapping the `extern underlyingWindow` declaration and replacing non-portable code with extendible code that a DirectX renderer can implement.

**Comment by DanRStevens** [comment]
That doesn't really tell me much.

It doesn't really wrap an `extern` variable. It implements a specific function. The function does happen to use the `extern` variable, though there are other uses of that variable in different contexts where the new function doesn't apply. It's not immediately clear that this new function replaces any of those `extern` uses, or if this provides new functionality for which you would have needed to add a new `extern` use to implement.
