### ISSUE TITLE
Add Common Vector constants

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#495]
Add common Vector constants to support readability and common vector operations along orthogonal axis (i.e. `DotProduct(Vector::X_Axis, Vector{0.8f, 0.6f}`) or specifying sizes in a compact manner:

```cpp
class Vector
{
    public:
        static const Vector Zero;
        static const Vector X_Axis;
        static const Vector Y_Axis;
        static const Vector One;
        static const Vector XY_Axis;
        static const Vector YX_Axis;
}
// ...
const Vector<BaseType> Vector<BaseType>::Zero{0,0};
const Vector<BaseType> Vector<BaseType>::X_Axis{1,0};
const Vector<BaseType> Vector<BaseType>::Y_Axis{0,1};
const Vector<BaseType> Vector<BaseType>::One{1,1};
const Vector<BaseType> Vector<BaseType>::XY_Axis{1,1};
const Vector<BaseType> Vector<BaseType>::YX_Axis{1,1};
```

**Comment by DanRStevens** [comment]
Some of these would be handy.

I noticed the last 3 are all the same. I suppose it may make sense to break them out more if we had more dimensions. Seems less useful if we stick with 2D.

----

Could make them `constexpr`, and initialize them inline. Making them `constexpr` automatically makes them `inline`, so they can be declared and defined in the header.

----

I'm wondering if the name `One` might be a bit misleading. This could easily mean a normalized vector, which would not match the given definition.

**Comment by cugone** [comment]
The `One` vector can be used to give sizes in a compact manner: `Vector::One * 2048`, etc.

**Comment by DanRStevens** [comment]
I don't doubt the usefulness of it. I just wonder if there might be a better name. I sort of have a feeling such a vector must have some kind of standard name in the realm of math.

**Comment by DanRStevens** [comment]
`ManhattanUnit`

:wink:

**Comment by cugone** [comment]
As funny as that is...it's just too long. :P

Convention in game development says the name "vector one" is well understood to mean "all ones" in each dimension:

https://docs.unrealengine.com/en-US/BlueprintAPI/Math/Vector2D/Vector2DOne/index.html
https://docs.unrealengine.com/en-US/BlueprintAPI/Math/Vector/VectorOne/index.html
(Unreal doesn't have a Vector4 One constant)

https://docs.unity3d.com/ScriptReference/Vector2-one.html
https://docs.unity3d.com/ScriptReference/Vector3-one.html
https://docs.unity3d.com/ScriptReference/Vector4-one.html

**Comment by DanRStevens** [comment]
Those links are useful to see what is already out there in terms of established practice. I am perhaps still a bit cautious about calling something well understood using only 2 examples. It does seem like it may be a reasonable name though.

----

For the `{0, 0}` case, do we want to call it `Zero`, or perhaps `Origin`?

Alternatively, we could potentially omit the zero case, since the default values are 0. It would be shorter to initialize with curly braces:
```cpp
Vector<float>::Zero; // {0, 0}
Vector<float>{}; // {0, 0}
```

----

The other names I'm still not so fond of. I think that's mainly due to the underscore. I would really like to avoid a name with an underscore in it. I don't think I would object so strongly to `XAxis` and `YAxis`. There is still room for confusion with that though, since the axis is assumed to be effectively an infinite sized vector in the given direction. It might be nice to have a name that implies a unit sized vector in a given direction. Maybe `UnitX` and `UnitY`? Don't know if I'm totally fond of that though.

**Comment by cugone** [comment]
> Those links are useful to see what is already out there in terms of established practice. I am perhaps still a bit cautious about calling something well understood using only 2 examples. It does seem like it may be a reasonable name though.


The two most-popular and most-used (non-proprietary) game engines on the planet. Both are always in the top 5, if not at the top, of any serious game engine list.
https://www.gamedesigning.org/career/video-game-engines/
https://instabug.com/blog/game-engines/
https://www.worldofleveldesign.com/categories/level_design_tutorials/recommended-game-engines.php
https://conceptartempire.com/free-game-engines/
https://thetool.io/2018/mobile-game-development-platforms (my opinion on mobile games not-with-standing)

---

> For the `{0, 0}` case, do we want to call it `Zero`, or perhaps `Origin`?

The "zero vector" is well defined in math:
https://en.wikipedia.org/wiki/Euclidean_vector#Length (sub heading zero vector)
https://en.wikipedia.org/wiki/Zero_element#Additive_identities

I really only hear "origin" being used to describe the origin/handedness of world space or screen projection, i.e., setting up the world origin or the ortho and camera spaces such that [0,0] is in the middle of the screen or off in one of the corners.

---

> Alternatively, we could potentially omit the zero case, since the default values are 0. It would be shorter to initialize with curly braces:
> 
> ```c++
> Vector<float>::Zero; // {0, 0}
> Vector<float>{}; // {0, 0}
> ```

Yes, but that would incur a run-time construction and space cost vs being constructed at startup once, statically available, and taking up zero space in the class.

`Zero` exists because it's a thing in math, and I fully intend for there to be a 4-dimensional `XYZ_One_W_Zero` and `XYZ_Zero_W_One` vector for affine transformations with Matrix4.

--- 

> The other names I'm still not so fond of. I think that's mainly due to the underscore. I would really like to avoid a name with an underscore in it. I don't think I would object so strongly to `XAxis` and `YAxis`. There is still room for confusion with that though, since the axis is assumed to be effectively an infinite sized vector in the given direction. It might be nice to have a name that implies a unit sized vector in a given direction. Maybe `UnitX` and `UnitY`? Don't know if I'm totally fond of that though.

`X_Axis` is me just being overly cautious for readability. Could easily just name is `X`, `Y`, `XY`, `YX`, etc.
