### ISSUE TITLE
Missing declarations warnings

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#510]
When compiled with `-Wmissing-declarations`, GCC-8 produces the following warnings:
```
src/Resources/Sprite.cpp:27:8: warning: no previous declaration for ‘std::__cxx11::string endTag(int, const string&)’ [-Wmissing-declarations]
 string endTag(int row, const std::string& name)
        ^~~~~~

src/Resources/Font.cpp:58:10: warning: no previous declaration for ‘unsigned int nextPowerOf2(unsigned int)’ [-Wmissing-declarations]
 unsigned nextPowerOf2(unsigned n)
          ^~~~~~~~~~~~

src/Mixer/MixerSDL.cpp:34:6: warning: no previous declaration for ‘void MIXER_HOOK()’ [-Wmissing-declarations]
 void MIXER_HOOK() { MIXER_HOOK_CALLBACK_SIGNAL(); }
      ^~~~~~~~~~

src/Xml/XmlBase.cpp:20:6: warning: no previous declaration for ‘void fillErrorTable()’ [-Wmissing-declarations]
 void fillErrorTable()
      ^~~~~~~~~~~~~~
```

I've found wrapping a method in an anonymous namespace can silence the warning. Perhaps these should be investigated to see if they are file level functions that should be protected from outside access.

**Comment by DanRStevens** [comment]
The `-Wmissing-declarations` flag, and a number of other flags were found from various articles suggesting warning flags to compile with.

References:
[GCC: 3.8 Options to Request or Suppress Warnings](https://gcc.gnu.org/onlinedocs/gcc/Warning-Options.html)
[StackOverflow: How to turn on (literally) ALL of GCC's warnings?](https://stackoverflow.com/questions/11714827/how-to-turn-on-literally-all-of-gccs-warnings)
[Best GCC warning flags for compiling C++](https://www.artificialworlds.net/blog/2014/07/18/best-gcc-warning-flags-for-compiling-c/)

**Comment by cugone** [comment]
Oddly, this is compiler specific. MSVC doesn't, and has never, warned for this. The only warning I get is `Function definition for 'function' not be found.` from live code analysis, not intellisense or the compiler, for missing *definitions* not declarations. The code compiles just fine, no warnings, even with Warning Level All and Warnings As Errors. If I'm missing a declaration at class scope it's declared as an error: `<Foo> Is not a member of <Bar>`, but file-level functions work just fine.

There is a similar warning in the "warnings that are off by default" article on docs.microsoft but it only applies to C code and no matter the warning settings applied, it will not trigger in C++ code.
https://docs.microsoft.com/en-us/cpp/preprocessor/compiler-warnings-that-are-off-by-default?view=vs-2019

**Comment by DanRStevens** [comment]
Yes, it's compiler specific. Many warnings are compiler specific. In particular, this one only shows up if the `-Wmissing-declarations` flag is passed. The warning is not enabled by default. It only seems to show up for GCC-8. I don't see the warning with GCC-7.5, nor with Clang.

Each compiler checks for a different set of possible warnings. That's one reason why we try to compile with multiple compilers. It gives better coverage for potential problem code constructs.

----

Check for a function prototype without a function definition is a rather different warning, meant for a different purpose. That would be to catch a function that was declared, but never defined, and might not be warned about because it was never used. That's different from a defined function that was never declared in a header, which may either have been a global function that was forgotten about in the header, or a private function that accidentally has larger scope impact than intended.

----

That particular MSVC warning looks pretty different. It's checking for no explicit parameter list. That's more about a difference in behaviour for old style C-code and newer code. Personally I think having an explicit `void` parameter to indicate no parameters is a bad practice, as was the old style practice of declaring a function name without also indicating essential type information, such as the parameter list.

**Comment by DanRStevens** [comment]
Closing, as all 4 warnings listed in the original post have been resolved by the 4 fix PRs.

We may want to revisit the links in the second post at some point, and add more permanent warning flags so these sorts of things don't creep back in. That may require using certain flags only with certain compilers.
