### ISSUE TITLE
Check `getDirectionVector` for accuracy

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#519]
As noted in https://github.com/lairworks/nas2d-core/pull/516#discussion_r392646167, the forumla used to convert an `angle` to a `Vector` may be incorrect.

The formula is dependent on the orientation of the coordinate system and the orientation of the angle, so I wanted to give this a little extra scrutiny.

For reference: [Rotation Matrix](https://en.wikipedia.org/wiki/Rotation_matrix)

**Comment by cugone** [comment]
I'll repeat my comment in #516 here.

The above referenced Rotation Matrix only applies if you are rotating a point in space. `angleToDirection` isn't doing that. It's calculating a unit vector given an angle:
https://en.wikipedia.org/wiki/Trigonometric_functions#Unit-circle_definitions

>The trigonometric functions cos and sin are defined, respectively, as the x- and y-coordinate values of point A, i.e., cos [theta] = Ax and sin [theta] = Ay

Ref:
https://math.stackexchange.com/questions/180874/convert-angle-radians-to-a-heading-vector

**Comment by DanRStevens** [comment]
The two are actually related. To see that though, you need to define the origin values. For instance, an angle of 0 might correspond with a unit vector pointing to the right, with increasing angle moving counter-clockwise. Combine that with the standard mathematical basis where the point one unit to the right is `Vector{1, 0}`. Using these values, you can rotate that initial vector by the angle, which corresponds to multiplying it by the rotation matrix.

```
v = |1|  (unit vector to the right)
    |0|

R = | cos θ  -sin θ |  (Rotation Matrix)
    | sin θ   cos θ |


Rv = | cos θ  -sin θ | |1|
     | sin θ   cos θ | |0|

   = | 1 * cos θ + 0 * -sin θ |
     | 1 * sin θ + 0 *  cos θ |

   = | cos θ |
     | sin θ |
```

----

Now, if instead the initial 0 angle was up, increased counter-clockwise, and the standard mathematical basis was used, the initial vector would correspond with `Vector{0, 1}`. The formula then becomes:
```
Rv = | cos θ  -sin θ | |0|
     | sin θ   cos θ | |1|

   = | 0 * cos θ + 1 * -sin θ |
     | 0 * sin θ + 1 *  cos θ |

   = | -sin θ |
     |  cos θ |
```

----

Continuing this way, if we now reverse the Y-direction from the standard mathematical basis, so we now use screen coordinates, then "up" is now `Vector{0, -1}`. The formula then becomes:
```
Rv = | cos θ  -sin θ | | 0|
     | sin θ   cos θ | |-1|

   = | 0 * cos θ + -1 * -sin θ |
     | 0 * sin θ + -1 *  cos θ |

   = |  sin θ |
     | -cos θ |
```

This is the formula used in the code.

----

Given the above, you could claim the function is not wrong per se, but rather not well documented.
