### ISSUE TITLE
Possible crash bug in Sprite::update

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#525]
If `Sprite::update` is called when an invalid `mCurrentAction` string is set, it can result in a crash error. The code in question is:
```cpp
void Sprite::update(Point<float> position)
{
	const auto& frame = mActions[mCurrentAction][mCurrentFrame];

	if (!mPaused && (frame.frameDelay != FRAME_PAUSE))
```

The `mActions` type is defined as `std::map<std::string, std::vector<SpriteFrame>>`. If the lookup string is not found, then `std::map::operator[]` will create a new value, which results in an empty `std::vector`. The index lookup on the `std::vector` then yields undefined behaviour, since it is still size 0, so any index is out of bounds.

Since the code stores the address, rather than immediately uses it, any ill effects may be deferred. A crash may be realized by the memory access from `frame.frameDelay`, which will try to fetch from an invalid address.

**Comment by cugone** [comment]
This is why `std::map::operator[]` should be banned. :P

The function could use some refactoring after the fact, particularly flipping conditionals to reduce arrow code, though.

```cpp
void Sprite::update(Point<float> position)
{
    const auto found = mActions.find(mCurrentAction);
    if(found != mActions.end())
    {
        const auto [actionName, actionFrames] = *currentAction;
        if(mCurrentFrame < actionFrames.size())
        {
            const auto& frame = actionFrames[mCurrentFrame];
            if(!mPaused && (frame.frameDelay != FRAME_PAUSE))
            {
                // ...
            }
        }
        // ...
    }
    // ...
```

**Comment by DanRStevens** [comment]
Agreed on not using `std::map::operator[]`.

Not sure I quite see how flipping conditionals will work at this point. This function has code at the tail, so an early exit doesn't seem possible.

Mind you, the code at the end is the rendering code, which as you've already proposed, should be split from the update code.
