### ISSUE TITLE
Bug in RendererOpenGL::setOrthoProjection method

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#540]
There looks to be a bug in `setOrthoProjection` in the following line:
```cpp
glOrtho(orthoBounds.startPoint().x(), orthoBounds.endPoint().x(), orthoBounds.endPoint().y(), orthoBounds.startPoint().x(), -1.0, 1.0f);
```

There are 3 instances of `x` but only one instance of `y`.

----

Additionally, the `1.0f` is over specified to be `float`. The actual parameter to [`glOrtho`](https://www.khronos.org/registry/OpenGL-Refpages/gl2.1/xhtml/glOrtho.xml) is `GLdouble`. This can cause a warning about `float` being promoted to `double` when the flag `-Wdouble-promotion` (#528) is specified.

The other parameters from `orthoBounds` are similarly affected. We may want this method to either accept `const Rectangle<double>&`, or call `orthoBounds.to<double>()` within the method.

**Comment by cugone** [comment]
Because there is a disparity between DirectX and OpenGL, one takes floats, the other takes doubles; and the Renderer interface already expects floats I'm going to leave it and just convert in-place inside OpenGL's version.

**Comment by cugone** [comment]
Realistically it should take a AABB3 it account for the near and far parameters as well, so they are not hard-coded.
