### ISSUE TITLE
Possible crash bug in RendererOpenGL initialization

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#544]
The function [`glGetString`](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glGetString.xhtml) can potentially return 0, which can cause an access violation if it is dereferenced. This can happen during `RendererOpenGL` initialization in the `std::string` constructor:
```cpp
	// Spit out system graphics information.
	std::cout << "\t- OpenGL System Info -" << std::endl;

	driverName((char*)glGetString(GL_RENDERER));

	std::cout << "\tVendor: " << glGetString(GL_VENDOR) << std::endl;
	std::cout << "\tRenderer: " << driverName() << std::endl;
	std::cout << "\tDriver Version: " << glGetString(GL_VERSION) << std::endl;

	std::string glsl_v = (char*)glGetString(GL_SHADING_LANGUAGE_VERSION);
```

When running Windows in a virtual machine, the last line causes a crash.

----

Since we call `glGetString` multiple times, perhaps we should wrap it in a method that can safely return an empty `std::string` when a `nullptr` is returned.

**Comment by cugone** [comment]
[The documentation](http://docs.gl/gl4/glGetString) says it only returns zero if there was an error and that an error only occurs if you give it the wrong `name` value. Since we are already giving it all the possible *name* values, the error can never occur. (`glGetStringi` and `GL_EXTENTIONS` notwithstanding as that's a different function.)

**Comment by cugone** [comment]
After a bit of googling, several sites and stack exchange network question/answers state that VMs don't get access to the physical GPU. Instead they get a virtual software GPU. (Unless you have HyperV and GPU passthrough, but that's highly unlikely). Trying to support VMs is a rabbit hole that should be avoided.

**Comment by DanRStevens** [comment]
Nevertheless, I did get an error, and the program crashed.

We should at minimum provide a proper error message and shutdown gracefully when an error occurs.
