### ISSUE TITLE
Relax GLSL support requirement in RendererOpenGL

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#545]
Perhaps we should remove this restriction for RendererOpenGL:
```cpp
	if (glsl_v.empty())
	{
		throw renderer_no_glsl();
	}
```

When running Windows in a Virtual Machine, I encountered a case where there was no GLSL support.

Commenting out this line allowed the game to load and display startup graphics. (It failed later due to a missing font file, so I didn't check if game play could display graphics).

**Comment by cugone** [comment]
Where is that code?

**Comment by cugone** [comment]
After a bit of googling, several sites and stack exchange network question/answers state that VMs don't get access to the physical GPU. Instead they get a virtual software GPU. (Unless you have HyperV and GPU passthrough, but that's highly unlikely). Trying to support VMs is a rabbit hole that should be avoided.

**Comment by DanRStevens** [comment]
My point was, we may not have an actual hard requirement here. If we don't require it, we shouldn't abort when it doesn't exist.

When I commented out the check, I was getting graphics output.

----

Tagging #544 as a related issue. This check follows immediately after the code to retrieve strings from OpenGL.

**Comment by DanRStevens** [comment]
Closed by #646.
