### ISSUE TITLE
The .gitignore file lists versioned files

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#549]
I noticed the `.gitignore` file lists at least one versioned file: `InstallVcpkgDeps.bat`
The ignore is through the line: `/*.bat`

We should maybe go through that file and clean out stuff that doesn't need to be in there.

From the Linux side, the following ignores are used:
```
.build/
lib/
```

**Comment by DanRStevens** [comment]
For Windows, Visual Studio seems to need the following ignores:
```
Debug/
Release/
*.user
```

----

I noticed other projects have rather common ignores, though I don't know if they are up-to-date. Examples:
- `.vs/`
- `*.suo`
- `*.db`
- `*.opendb`

I haven't found any information on if or when VS2019 would generate these.

**Comment by cugone** [comment]
All of those are used.

`.vs/` is the hidden folder where VS keeps bookkeeping-related and the intellisense database.

I checked the file history, `/*.bat` was added manually to the template in 2017 by Leeor. That is safe to remove.

**Comment by DanRStevens** [comment]
I mentioned `.vs/` in the associated issue. I can't figure out how to generate it though. Doing a Google search mostly reveals stuff from VS2015. Is it up-to-date? If so, how can I get VS to generate that folder?

**Comment by cugone** [comment]
The files are generated on compile in Visual Studio if they don't exist. I only have Visual Studio Community 2019 and, after deleting `/.vs`, it still generates them. (You can't have Visual Studio open if you try to delete them).
