### ISSUE TITLE
FpsCounter Bugs

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#554]
In `FpsCounter` there appears to be an index error, where the index ranges from 1 .. ArraySize, rather than from 0 .. (ArraySize - 1).
```cpp
	FPS_COUNTS[++INDEX] = 1000 / TICK_DELTA;

	if (INDEX >= FPS_COUNTS_SIZE) { INDEX = 0; }
```

An easy fix would be to increment after use, and to immediately wrap it after increment:
```cpp
	FPS_COUNTS[INDEX] = 1000 / TICK_DELTA;
	++INDEX;
	if (INDEX >= FPS_COUNTS_SIZE) { INDEX = 0; }
```

----

The initial tick value is initialized to 0, which means the first calculated delta may be surprisingly large, depending on SDL startup time relative to construction of the `FpsCounter` object:
```cpp
	LAST_TICK = CURRENT_TICK;
	CURRENT_TICK = SDL_GetTicks();

	TICK_DELTA = CURRENT_TICK - LAST_TICK;
```

The current tick value should probably be initialized to `SDL_GetTicks()` during construction.

Of course the effects of the initial value are quite temporary in nature, and perhaps not a big concern. Especially since the error is weighted in a direction where it may not matter much, and would be similar to a lack of data, or the initialization value.

**Comment by cugone** [comment]
Howard Hinnant (the guy who *wrote* the std::chrono library!) did a great write-up on how to use `std::chrono` with the `SDL_GetTicks`. It might be useful. 

https://stackoverflow.com/a/59446610/421178

**Comment by DanRStevens** [comment]
Thank you for that. I was looking at `FpsCounter` earlier today, and wondering if we even need it. It's not used within the NAS2D library itself, and the only use in OPHD is not actually used for anything. Was thinking perhaps we could scrap it, or use a standard library replacement. I thought it might be a bit early to make the call though. I figured for now, at least fix any warnings or glaring bugs, if it is easy.
