### ISSUE TITLE
Deciding on a Vertex format

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#596]
I want to start looking in to modernizing the OpenGL implementation (shaders and the programmable pipeline instead of the fixed functions) and moving away from Open GL 3,x and earlier.

Part of that is defining a vertex format. There are a couple ways to go about it.

---

The easy but hard to change version where there is one vertex type whose attributes are added to over time.

```cpp
struct Vertex3D {
    Vector3 position;
    Vector4 color;
    Vertex3D(const Vector3& position = Vector3::Zero, const Color& color = Color::White);
};

inline Vertex3D::Vertex3D(const Vector3& position, const Color& color)
: position(position)
, color(color.As<float>())
{ }

// .. Some time later

struct Vertex3D {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
    Vertex3D(const Vector3& position = Vector3::Zero, const Color& color = Color::White, const Vector2& uv = Vector2::Zero);
};

inline Vertex3D::Vertex3D(const Vector3& position, const Color& color, const Vector2& uv)
: position(position)
, color(color.As<float>())
, uv(uv)
{ }

// .. Some more time later

struct Vertex3D {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
    Vertex3D(const Vector3& position = Vector3::Zero, const Color& color = Color::White, const Vector2& uv = Vector2::Zero, const Vector3& normal = Vector3::Zero);
};

inline Vertex3D::Vertex3D(const Vector3& position, const Color& color, const Vector2& uv, const Vector3& normal)
: position(position)
, color(color.As<float>())
, uv(uv)
, normal(normal)
{ }
```

This makes up-front coding easier but if the format and/or layout changes, everywhere it's used must also change, i.e. shaders, layout definitions (`gl*Pointer` in OGL, `InputLayouts` in DX), per-element function calls (`PushVertex(...)` for something like a `Mesh` class ), etc.

---

The harder to implement but easier to make changes is different Vertex formats for individual uses (I'm only including the layout for brevity):

```cpp
struct Vertex2_P {
    Vector2 position;
};

struct Vertex2_PC {
    Vector2 position;
    Vector4 color;
};

struct Vertex2_PCU {
    Vector2 position;
    Vector4 color;
    Vector2 uv;
};

struct Vertex2_PCN {
    Vector2 position;
    Vector4 color;
    Vector3 normal;
};

struct Vertex2_PCUN {
    Vector2 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
};

// Full tangent space for normal mapping... no, I'm not calling it PC*NT
struct Vertex2_PCUT {
    Vector2 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
    Vector3 tangent;
    Vector3 bitangent;
};

struct Vertex3_P {
    Vector3 position;
};

struct Vertex3_PC {
    Vector3 position;
    Vector4 color;
};

struct Vertex3_PCU {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
};

struct Vertex3_PCN {
    Vector3 position;
    Vector4 color;
    Vector3 normal;
};

struct Vertex3_PCUN {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
};

// Full tangent space for normal mapping... no, I'm not calling it PC*NT
struct Vertex3_PCUT {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
    Vector3 tangent;
    Vector3 bitangent;
};

// Texture skinning a mesh in 2D isn't a thing.
struct Vertex3_PCUTB {
    Vector3 position;
    Vector4 color;
    Vector2 uv;
    Vector3 normal;
    Vector3 tangent;
    Vector3 bitangent;
    Vector4 bone_weights;
};

```

This allows for having shaders and vertex data that may only need positions to never have to change later as the vertex layout changes. Adding texture mapping, normal mapping, full lighting support, and/or bone weights (I don't see this becoming a feature in NAS2D...maybe NAS3D?) is as simple as adding a new vertex type that supports it.

**Comment by DanRStevens** [comment]
I think more context needs to be given about how this fits into the plan. I don't really see how the current API would make use of these structures. That makes it a little hard to decide on a direction.

More detail is required about what functions would be changed, and how.

Included in that detail should be how changes would impact compatibility. Do the proposed changes impose more strict hardware requirements? Are there updated software requirements?
