### ISSUE TITLE
Leaky Headers

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#61]
The NAS2D headers leak third party includes (OpenGL) in exactly one file: [ShaderManager](https://github.com/lairworks/nas2d-core/blob/e21acce0a5a9b57b93962ca7fd43dc9f92cb9f7b/include/NAS2D/Renderer/ShaderManager.h#L15-L22)

Should this be allowed, or should users of NAS2D be isolated from the underlying implementation (OpenGL, SDL, etc.). Personally, I think third party includes should stay out of public header files whenever possible. The one exception being when two libraries are meant to be used together in tandem by the client code, which does not appear to be the case here.

Further, ShaderManager is currently dead code. The header is not included by the main NAS2D header, nor is any of it's code referenced from other parts of the project. I think ShaderManager, and the recently commented out Shader, should be deleted from the current version.

Going forward, I'd suggest keeping third party includes out of public headers as a rule.

**Comment by ldicker83** [comment]
I actually agree. It's the biggest change I made in 1.4.0, an effort to hide implementation details and only expose NAS2D interfaces.

I'll pull the files associated with shader management and usage as those are features that will be implemented in another release.

**Comment by ldicker83** [comment]
Looking at the header Renderer/ShaderManager.h, the copyright notice kinda says it all:

`// = Copyright � 2008 - 2012 New Age Software`

Hasn't been touched for at least 5 years, almost 6.

**Comment by DanRStevens** [comment]
Alright, seeing as how you've now removed the files in question, I'm going to close this issue.
