### ISSUE TITLE
Extract Window class from Renderer

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#701]
The `Renderer` methods largely fall into two categories:
- Drawing methods
- Windows management methods

We should split the Window management methods into their own `Window` class.

The `Window` class should control things like the `icon` and the `title`, as well as the control area (`Rectangle`). It should also provide the event handlers for the `onResize` event, the `minimumSize` property, the `resizeable` property, and the `fullscreen` property.

Potentially this class could allow access to the underlying `HWND` handle on Windows, which could be used as an escape for calling native Windows API methods. In particular, it could be used for modal popup boxes (which we should generally discourage using).

**Comment by cugone** [comment]
This might be more involved than previously realized. A basic Rendering Hardware Interface (RHI) setup for refactoring out the instance, device, context, and output might be required. Especially in differences between DX/OGL and ownership of particular instances. Modern Metal/Vulkan/DX12 minimizes the differences due to similar support for various features but that's way beyond the scope of the engine.

**Comment by DanRStevens** [comment]
Yes, I expect this one to be quite involved. Though I believe it's important work. I'm not entirely sure of what the final design would look like yet. There are some obvious awkward points in terms of underlying window handles and rendering contexts.

I've been tempted to keep the same methods initially, but to somehow split them into a `Window` class and a `Renderer` class, and perhaps give `friend` access between them to minimize external API burdens. I'm sure a better design could be evolved from there.

**Comment by DanRStevens** [comment]
I guess technically the points of this issue have been met. There's probably more room for improvement, perhaps decoupling the new `Window` class from `Renderer` so there is no longer inheritance between them, but perhaps that can be done under a separate issue when the time comes.
