### ISSUE TITLE
Allow read/write of floats to XML attributes

### ISSUE THREAD

**Issue by Brett208** [lairworks/nas2d-core#737]
Request addition of something like queryFloatValue (https://leethomason.github.io/tinyxml2/classtinyxml2_1_1_x_m_l_attribute.html#a049dea6449a6259b6cfed44a9427b607).

Currently we have to use static_cast to go from double to float when serializing to a float to prevent failing CI builds caused by compiler warnings.

Related to #211. May be able to solve by just updating to TinyXML 2.

**Comment by DanRStevens** [comment]
I agree about updating to TinyXML2.

Related: #239

Actually, there's been a lot of work on refactoring the `Configuration` class, which was basically pre-work for decoupling from the modified integrated TinyXML1 library, and to make way for an upgrade to TinyXML2. I should probably open an issue for that, and add PR references to track all the work in one place.

**Comment by DanRStevens** [comment]
I'm wondering if we should close this and instead track under an issue to update to TinyXML2 using `vcpkg`. That's sort of what #211 is about, though it doesn't explicitly say to upgrade to TinyXML2. Similarly #239 says to update to TinyXML2, but doesn't explicitly say to use `vcpkg`. Or maybe we should create a new issue and link to the old ones. There's quite a bit of discussion in the old issues, so they're no longer quite so cut and dried about what exactly needs to be done.

**Comment by Brett208** [comment]
I would be ok either linking this issue to #211 and stating the planned solution to support floats is through TinyXML2 or just closing this issue if preferred to not track the detail that XML float parsing is a desired feature.

**Comment by ldicker83** [comment]
Keep in mind a lot of the 'query' type functions are basically custom functions I added myself in the modified TinyXML implementation.

I'm beginning to see why it's better to just use a library as it's implemented. I'm completely okay with switching to TinyXML 2 but it's going to take some work to modify the I/O code to handle that for savegames in OPHD.

Still, not opposed to it as I think it's a better option to dump old code that's not maintained anymore and instead use an actively developed library.

**Comment by DanRStevens** [comment]
Well, on the bright side, we learned something valuable about code maintenance through experience!

GitHub has already created a link back from #211 due to the reference from this thread. The link includes the title of this thread, so it should be pretty clear.
