### ISSUE TITLE
Read/Write from XML elements instead of element attributes

### ISSUE THREAD

**Issue by Brett208** [lairworks/nas2d-core#738]
Currently, NAS2D only supports reading from XML attributes. Sometimes this is suboptimal, especially when reading large amounts of text.

For example, in OPHD, we would likely like to remove the planet descriptions from being hardcoded. They would work well stored within an XML element, but would work poorly (it at all?) if stored in an XML attribute.

I haven't checked if TinyXML2 has this support built in. Maybe solvable but upgrading the library dependency.

**Comment by DanRStevens** [comment]
I believe it would work fine with attributes. Though yes, it does seem a bit messy to store that amount of text in an attribute.

The `Configuration` class could potentially be extended to read from either attributes or from sub tags/values. I'm not sure how you would specify that for writing with the current API, but it should be easy enough to support reading from either attributes or sub tag values.

Either TinyXML1 or TinyXML2 should have no trouble supporting this feature.

**Comment by DanRStevens** [comment]
I think I'd like to close this as out of scope for NAS2D.

The TinyXML1 and TinyXML2 libraries both already support reading and writing of XML element values. We don't really need to store values in attributes, this is just an artifact of re-using existing wrapper parsing code that does things that way. In terms of parsing from XML element values, this seems like a higher level parsing concern. In particular, OPHD already makes direct use of TinyXML, so this could be accomplished there.

Granted, we are trying to move away from direct use of TinyXML in OPHD, as loading data through an abstraction layer can make upgrading the library easier. Though that effort is somewhat hampered by some degree of custom parsing needed to handle custom file formats. In particular, reading XML element values would be such custom parsing. It might be that we end up maintaining custom parse routines in OPHD. Hopefully such routines will be a bit more generalized and re-usable, as current parse code is somewhat verbose and spread through the code base. In terms of eliminating it entirely from OPHD, that may not be entirely feasible.

Unless we can come up with a generalized format for parsing all data from a simple generic format, we should probably push this concern to higher level code.

**Comment by Brett208** [comment]
I'm ok using TinyXML directly in OPHD to read from elements and closing this issue. I guess I didn't realize we could do that when writing this up.

-Brett

**Comment by ldicker83** [comment]
Ultimately I'd like to move away from XML as a savegame format. I did it initially so I could read the output in a text editor to ensure that things were behaving properly with the ultimate intention of saving it as a binary format somewhere down the line. Or some other human readable form but with a much, much smaller footprint.

If, on the other hand, we opt to stick with XML I want to ensure that whatever library is used has a vcpkg option for Windows and is also available on Linux/macOS.

**Comment by DanRStevens** [comment]
Hmm, interesting looking library.

I'm fine if we stuck with XML, or another text format.

First issue though is to refactor the code so it is more decoupled from the specific library. Using `vcpkg` and upgrading, or considering alternate libraries will then be easier at that time.

**Comment by ldicker83** [comment]
I'm generally in agreement. I think it would make sense to upgrade to TinyXML 2 via vcpkg, port everything over to that and then strip the XML interface out of NAS2D entirely. I'm curious about thoughts using XML internally for the configuration class but if we go with a strictly dictionary type of approach we could build a basic custom parser that uses a sort of 'INI' type of deal with simple key/value pairs? Would eliminate the dependency on TinyXML in NAS2D itself and then individual projects (like OutpostHD) can decide how to handle it.

It would mean redefining Sprite definitions if XML were dumped. I can still see it being done simply enough using key/value pairs in some way though the XML definition does make it nice and neat. It could be a simple text type of document that's formatted in a particular way using some sort of delimiter, like commas or spaces? Thought now we're getting off the subject at hand and into different issue territory.

Anyway, food for thought.

**Comment by DanRStevens** [comment]
Yeah, I'd considered that. Because of the current dependence on XML for `Configuration` and `Sprite` data, I would keep the dependency for now. I suppose long term you could look at removing the parse code, and instead only offer a constructor with already parsed data. That way you can push parsing responsibility off to the client code. The client project can then choose which formats it wants to support, and which libraries to use to parse the data. I'm not sure if the classes would be as useful though. Hence that might never happen. Just a thought that we might revisit in the future, when we're in a better position to see where things might go.
