### ISSUE TITLE
Make recipes for real targets should not list phony order-only dependencies

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#75]
Well, I learned something new today. This goes back to some code I wrote months back. Code that was criticised for an issue, which I ignored.

https://github.com/lairworks/nas2d-core/blob/818725081ad043882e5cd57ae1656b95f7618554/makefile#L39
https://github.com/lairworks/nas2d-core/blob/818725081ad043882e5cd57ae1656b95f7618554/makefile#L43-L46

A phony target has no output, and so can never be up-to-date. As such, the rule will always run when building a real target.

In this case, the rule doesn't need to be phony, since the created directory is a real output. The only thing invalid about it is the date, hence why it's an order-only dependency.

The rule should be updated so the object file has an order-only dependency on the directory, and the directory (rather than a phony rule) should be the target of the build rule to create it.

That should eliminate needless attempts to create already existing folders during a build.

**Comment by cugone** [comment]
Has this issue been fixed?

**Comment by DanRStevens** [comment]
No.

I have an open branch that would have fixed this, but it fails on MacOS. I may pull a small bit from that branch just to address this one point. The branch was a little more all encompassing than this issue called for, since it basically pulled in a new Makefile from another project which has undergone quite a bit of development.
