### ISSUE TITLE
Clean out repository cruft

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#80]
There is 20MB of data in `proj/xcode`. I suspect most of it is either automated downloads for a local MacOS environment, or build output for MacOS. Either way, I don't think it should be there. Automated dependency downloads are typically listed in the `.gitignore` file, as are build outputs.

**Comment by ldicker83** [comment]
xcode stuff is kind of a mystery to me. If memory serves it's basically the dependencies kind of like .lib files on Windows. Maybe @allenmoatallen can weigh in on that?

**Comment by DanRStevens** [comment]
No response. Should we just gut it? It will still exist in project history, and so could be brought back if needed.

It looks like the bulk of the data is dependency packages from the `Frameworks` folder:
```
du -hcs proj/xcode/Frameworks/*
500K	proj/xcode/Frameworks/libphysfs.2.0.3.dylib
2.7M	proj/xcode/Frameworks/SDL2.framework
2.3M	proj/xcode/Frameworks/SDL2_image.framework
7.1M	proj/xcode/Frameworks/SDL2_mixer.framework
7.2M	proj/xcode/Frameworks/SDL2_ttf.framework
20M	total
```

Platform specific dependency packages should probably be downloaded with a tool or script, where the download commands are versioned, but the packages themselves are `.gitignore`d.
