### ISSUE TITLE
NAS2D::split() throws unhandled exception when passed an empty string

### ISSUE THREAD

**Issue by ldicker83** [lairworks/nas2d-core#825]
I suspect that most use cases here would not pass empty strings through `split()` but there is a case in OutpostHD that could pass an empty string when loading a `RobotCommandCenter` that's been saved before any robots can be assigned to it.

I'm not sure if this should be considered an error and throw our own `std::runtime_error` or if it should be silently ignored and just pass back an empty `vector<string>`.

In the mean time I'll use a work around in the OutpostHD code that doesn't attempt to load an empty robot list string.

As a note, adding:

```cpp
if (str.empty()) { return std::vector<std::string>(); }
```

to the top of the function eliminates the throw. It's the silent swallowing of potentially incorrect use that has me unsure of the best way to approach this.

**Comment by DanRStevens** [comment]
Are you sure this is diagnosed correctly? From the unit tests:
```cpp
EXPECT_EQ((NAS2D::StringList{}), NAS2D::split(""));
```

Mind you, the other split variants don't have unit tests, so if you're using `splitOnFirst` or `splitOnLast`, they are not unit tested.

I suspect perhaps the method is being passed a bad value and invoking undefined behaviour. Perhaps a dangling reference to a string or vector being passed in from OPHD code? Is the problem from existing code, or new code in a branch?

**Comment by ldicker83** [comment]
It's using split() and I'm pretty sure it is. I I use a guard that doesn't call split() unless the passed string is not empty, it doesn't break. If I modify the function to use the line I mentioned above, it doesn't break.

In hindsight this is actually a debug assertion failure so perhaps this isn't something that needs to be addressed?

![image](https://user-images.githubusercontent.com/13858902/107280847-dcc2fd80-6a26-11eb-8f22-7ea93790b1ca.png)
![image](https://user-images.githubusercontent.com/13858902/107280921-f6fcdb80-6a26-11eb-9681-cb166b16502a.png)

Still, I don't think we need to have debuggers exploding on 'errors' that aren't really errors. Hence the request for opinion. :D

**Comment by DanRStevens** [comment]
Hmm, that is very useful additional info. The Linux builds probably don't run the same sort of debug assertions, such as checking for a non-empty `std::string` before calling `back()`. Technically, there is no requirement to fail or report when undefined behaviour has been invoked. This may actually be a bug in the library code.
