### ISSUE TITLE
Update Filesystem exceptions

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#83]
The exception hierarchy and error reporting could perhaps be re-worked a bit.

For PhysFS errors, the error could be captured inside an exception constructor, simplifying the calling code quite a bit. This may also ease transition from the now deprecated [`getLastError`](https://icculus.org/physfs/docs/html/physfs_8h.html#a9f78e4ab560885fd10202988d2fff1b6) and help transition to [`getLastErrorCode`](https://icculus.org/physfs/docs/html/physfs_8h.html#ae916a873aae2cf6b6e09d733cd1b3f4b) and [`getErrorByCode`](https://icculus.org/physfs/docs/html/physfs_8h.html#a545f6b5ba97faa19441932dffb65c3be).

Currently error messages are being dumped to `cout`. Better would be to report errors to `cerr`. Best would be to capture the message in the exception itself. If the exception message is logged in caller, it can log it to `cerr`, or whatever log file it produces.

----

I believe the exceptions should be more closely tied to the component they are associated with. Currently the filesystem related exceptions are in a generic `Exception.h`. I think it would be better to keep the filesystem specific exceptions as part of the `Filesystem` class, perhaps as contained classes.

----

I believe there should be a common filesystem related base class for all filesystem exceptions. Currently each one derives from `runtime_error` directly.

I'm uncertain if we need the granular detail of having separate exception classes for each of the possible filesystem errors. Currently we have:
- `filesystem_backend_init_failure`
- `filesystem_not_initialized`
- `filesystem_already_initialized`
- `filesystem_file_handle_still_open`

In particular, the PhysFS library already checks and reports many of these conditions. We could have just a generic exception which captures the PhysFS error and reports that.

**Comment by DanRStevens** [comment]
I was taking a look at the exception code. It seems `filesystem_not_initialized` is used the most by far. This makes sense considering the C style Physfs interface, and how pretty much every filesystem method requires the initialization method to be called first.

I was thinking, this check would not be needed if we used a modern C++ style interface with checked exceptions. Within the constructor of `Filesystem`, we could call `PHYSFS_init`, throw if it fails, and then assume it has already been called for all member functions. This would require collapsing the two stage initialization (constructor + init) into a single stage initialization (constructor only).

Curiously, the two stage initialization pattern seems to derive from old C code, or early C++ code from before C++ had exceptions. Hard to remember C++ not having exceptions, but yes, there was a time, and things like MFC, and certain classes in the standard library had designs influenced by that.

The standard practice now, is to use single stage initialization, and to throw from the constructor if initialization fails. Throwing from the constructor prevents object creation. That way, you can't have a partially initialized object in some unusable zombie state. The object is either fully initialized and usable, or simply doesn't exist.

----

There are some challenges with the above suggestion. In particular, the `Utility` class creates objects on demand by calling the default constructor. This mechanism does not provide a way to specify constructor parameters.

Another challenge might be what happens if someone tries to construct two Filesystem objects, or manually calls `PHYSFS_init` or `PHYSFS_deinit`. The Physfs documentation does not address what happens if `PHYSFS_init` is called multiple times.

Currently the `Filesystem` object is designed to work as a singleton, and the `Utility` class ensures this, with cached lazy initialization. As such, we don't need to worry about multiple objects. Though there is still a possibility for manual calls to `PHYSFS_init` and `PHYSFS_deinit`. My though is, if Physfs isn't initialized, the other calls will already fail and report errors, so don't worry about it. Such logic errors would be caught very quickly during development.

Additionally, rather than rely on an additional `FILESYSTEM_INITIALIZED` variable, the check could be based on `PHYSFS_isInit` instead.

----

I'm thinking the `Filesystem` initialization should be done in a more explicit manner, rather than lazily constructed through the `Utility` class. In particular, the `init` method is already called explicitly within the `Game` constructor, which represents a natural place to initialize global game objects.

Anyway, I may need to think about all of this a bit more.

**Comment by DanRStevens** [comment]
On a related matter, if you want to auto capture Physfs error messages in exceptions, it can be done in the exception's constructor. As many of the checks represent logic errors, which indicate programming bugs, a base type of [`std::logic_error`](https://en.cppreference.com/w/cpp/error/logic_error) may make sense there.

Filesystem.h:
```cpp
class FilesystemLogicError : public std::logic_error {
public:
	FilesystemLogicError();
};
```

Filesystem.cpp:
```cpp
Filesystem::FilesystemLogicError::FilesystemLogicError() :
	std::logic_error(PHYSFS_getLastError())
{}
```

**Comment by ldicker83** [comment]
I'm going to close this issue as there is likely to be no further development or support of the object in lieu of using C++17 filesystem functions and making that the problem of the user (see #179 for details).
