### ISSUE TITLE
Update calls to deprecated PhysFS functions

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#84]
A number of PhysFS functions have been deprecated, with suggested alternatives:
- [`getUserDir`](https://icculus.org/physfs/docs/html/physfs_8h.html#a9d86fca7a5cbbc53f5425ff7539b1426) ==> [`getPrefDir`](https://icculus.org/physfs/docs/html/physfs_8h.html#acd87392d234d070695303521bb8052a5) (or [`setSaneConfig`](https://icculus.org/physfs/docs/html/physfs_8h.html#afef8700f714b6800ff688372c540bfe2))
- [`addToSearchPath`](https://icculus.org/physfs/docs/html/physfs_8h.html#a0956d926822291a23ee540c2ffefa1af) ==> [`mount`](https://icculus.org/physfs/docs/html/physfs_8h.html#a8eb320e9af03dcdb4c05bbff3ea604d44)
- [`getLastError`](https://icculus.org/physfs/docs/html/physfs_8h.html#a9f78e4ab560885fd10202988d2fff1b6) ==> [`getLastErrorCode`](https://icculus.org/physfs/docs/html/physfs_8h.html#ae916a873aae2cf6b6e09d733cd1b3f4b) and [`getErrorByCode`](https://icculus.org/physfs/docs/html/physfs_8h.html#a545f6b5ba97faa19441932dffb65c3be)
- [`read`](https://icculus.org/physfs/docs/html/physfs_8h.html#a91234f576477f7de67d635761d01aa7b) ==> [`readBytes`](https://icculus.org/physfs/docs/html/physfs_8h.html#a63ac40ecdb3f9b91e6ee309bdbad0ce8)
- [`write`](https://icculus.org/physfs/docs/html/physfs_8h.html#af5dc83d5e4ef0b0c9bce1834ea1bb498) ==> [`writeBytes`](https://icculus.org/physfs/docs/html/physfs_8h.html#a192ae4f946656ae2aef5e16e438f94e1)
- [`isDirectory`](https://icculus.org/physfs/docs/html/physfs_8h.html#a5877fcafb72dca892c1c2465292eef47) ==> [`stat`](https://icculus.org/physfs/docs/html/physfs_8h.html#a7f5e23675c50ffe51ad00cceb5a65348)

Some of these calls could be updated using the current older version of PhysFS. This would reduce the warnings when using a newer library version, while still maintaining compatibility with the older version. Other updates may be part of an upgrade effort that breaks PhysFS version compatibility (such as `getPrefDir` and `setSaneConfig`).

**Comment by DanRStevens** [comment]
I came across the [deprecation list for Physfs](https://icculus.org/physfs/docs/html/deprecated.html).

Most methods in the deprecation list have an alternate listed as of Physfs 2.1. The stock Ubuntu 16.04 package of Physfs is version 2.0.3. Hence the only method that can be upgraded without breaking compatibility with the stock Ubuntu 16.04 package is `addToSearchPath` ==> `mount`.

I had hoped to do the upgrade in stages to reduce the warnings and the change sets. Looks like the set of methods to transition before the upgrade will be more limited.

**Comment by DanRStevens** [comment]
I came across this release note:
[https://hg.icculus.org/icculus/physfs/rev/release-2.1.1](https://hg.icculus.org/icculus/physfs/rev/release-2.1.1)

It seems there was no official 2.1.0 nor 2.1.1 release. Those were internal release numbers. Hence, there is no corresponding package on the download page. The download package versions jump from 2.0.3 to 3.0.0.

Looks like the only upgrade step will be to jump from 2.0.3 to either 3.0.0 or 3.0.1. The releases are only about a month apart. Looks like mostly small bug fixes in 3.0.1, with no interface changes, so that should be the target for the upgrade.

**Comment by DanRStevens** [comment]
There is now a single warning left for deprecated PhysFS functions:
```
src/Filesystem.cpp:375:9: warning: 'PHYSFS_getUserDir' is deprecated
      [-Wdeprecated-declarations]
        return PHYSFS_getUserDir();
               ^
/usr/local/include/physfs.h:792:49: note: 'PHYSFS_getUserDir' has been
      explicitly marked deprecated here
PHYSFS_DECL const char *PHYSFS_getUserDir(void) PHYSFS_DEPRECATED;
                                                ^
/usr/local/include/physfs.h:241:42: note: expanded from macro
      'PHYSFS_DEPRECATED'
#define PHYSFS_DEPRECATED __attribute__((deprecated))
                                         ^
1 warning generated.
```

From the documentation, they have the note:

> Deprecated:
> As of PhysicsFS 2.1, you probably want PHYSFS_getPrefDir().
> 

The relevant documentation is:
[`PHYSFS_getUserDir()`](https://icculus.org/physfs/docs/html/physfs_8h.html#a9d86fca7a5cbbc53f5425ff7539b1426) : Get the path where user's home directory resides.
[`PHYSFS_getPrefDir()`](https://icculus.org/physfs/docs/html/physfs_8h.html#acd87392d234d070695303521bb8052a5) : Get the user-and-app-specific path where files can be written.

There is a subtle distinction between the two:
The `getUserDir` method returns paths such as: `C:\Users\username`
The `getPrefDir` method returns paths such as: `C:\Users\username\AppData\Roaming\Company\AppName`

----

The `PHYSFS_getUserDir()` method is used in `Filesystem::userPath()`. This method does not appear to be used anywhere in NAS2D nor in OPHD.

We could potentially just drop the method. Or we can modify the method to use the `PHYSFS_getPrefDir()` method, in which case the `Filesystem` method should also be renamed to be more descriptive. Or we could keep existing behaviour and silence the warning.

I think I disagree that PhysFS should deprecate that particular method, though I can understand why they'd do it to encourage people to abandon old ways of getting a system specific write folder and use the new way. That doesn't mean all uses of that particular old method are necessarily invalid though.

As the method is not used, I think I have a slight preference to just drop it. I'd be willing to do the work to rename if someone had a good alternate name or semantic they wanted to implement.

**Comment by DanRStevens** [comment]
@ldicker83, may I please draw your attention to the above post. This may need some input from you to decide where we want to go with this.

The last PhysFS deprecation warning is from a function wrapper, where the wrapper itself doesn't appear to be used anywhere.

I see three options:
1) Drop the method (it's unused, and easy to do)
2) Change the wrapper to not use deprecated methods (needs alternative specification/behavior)
3) Silence the warning (likely compiler specific)

**Comment by DanRStevens** [comment]
I looked briefly into silencing the warning. Although C++ now has a standard way to declare something as deprecated, it seems there's no standard way to ignore a deprecation warning. I looked into how MSVC, Clang, and GCC do it. My attempted resulted in the following:
```cpp
	#pragma GCC diagnostic push
	#pragma GCC diagnostic ignored "-Wdeprecated-declarations"
	#pragma clang diagnostic push
	#pragma clang diagnostic ignored "-Wdeprecated-declarations"
	#pragma warning(suppress : 4996)
	return PHYSFS_getUserDir();
	#pragma clang diagnostic pop
	#pragma GCC diagnostic pop
```

A big downside to the above is the compilers will now warn about the unrecognized pragmas for the other compilers. This is starting to feel a bit like an arms race.

I was tempted to disable the warnings about the unknown pragmas, those quickly realized there is an easier way. Do a compiler detect first, and only issue the pragmas for the current compiler. Still messy, but at least with an end in sight.

I came across this thread, which contains an answer where macros are setup to do this for MSVC, Clang, and GCC:
https://stackoverflow.com/questions/3378560/how-to-disable-gcc-warnings-for-a-few-lines-of-code
It's basically a screenful of code to disable the warning for 1 line.

**Comment by ldicker83** [comment]
My feeling is to just dump the function and be done with it. No sense spending more time than necessary with it.
