### ISSUE TITLE
Update Doxygen comments

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#850]
Doxygen documentation: https://www.doxygen.nl/manual/index.html

The Doxygen config was left to stagnate for a long time and got pretty out-of-date. Some of it was updated recently. This raised some questions about best practices for writing Doxygen comments, and if we are making best use of available features. It seems highly possible more features have been added since we last considered the config file, and perhaps documentation styles may have been updated since then.

----

One question was if `\class` was really needed when adding class comments immediately before a class. It would appear that no, it's not strictly needed, at least not unless you want to indicate a non-default include filename (other than the one containing the class). Another use for `\class` was if the documentation was not immediately before the class, but rather included elsewhere in the code, such as at the end of the file.

Reference: https://www.doxygen.nl/manual/starting.html#step3
> If the EXTRACT_ALL option is set to NO in the configuration file (the default), then doxygen will only generate documentation for documented entities. So how do you document these? For members, classes and namespaces there are basically two options:
> 
> 1. Place a special documentation block in front of the declaration or definition of the member, class or namespace. For file, class and namespace members it is also allowed to place the documentation directly after the member.
> 
> See section Special comment blocks to learn more about special documentation blocks.
> 
> 2. Place a special documentation block somewhere else (another file or another location) and put a structural command in the documentation block. A structural command links a documentation block to a certain entity that can be documented (e.g. a member, class, namespace or file).
> 
> See section Documentation at other places to learn more about structural commands.
> 
> The advantage of the first option is that you do not have to repeat the name of the entity.
> 
> Files can only be documented using the second option, since there is no way to put a documentation block before a file. Of course, file members (functions, variables, typedefs, defines) do not need an explicit structural command; just putting a special documentation block in front or behind them will work fine.

Potentially we can remove a lot of the `\class` lines, as they are not required. Additionally, that would remove repetition of the class name, which is an added burden when refactoring to rename a class.

----

Another area that may be worth investigating is the auto brief features. Potentially the `\brief` command could be omitted.

**Comment by ldicker83** [comment]
I'm game for updating the documentation. I started using doxygen over a decade ago and it's matured considerably since then. I think the more we can take advantage of automatic documentation features the better.

Additionally a lot of the architecture and assumptions made by NAS2D, especially in the Signals/Slots implementation, have changed a lot.

**Comment by DanRStevens** [comment]
The `QT_AUTOBRIEF` setting sounds potentially useful:
https://www.doxygen.nl/manual/config.html#cfg_qt_autobrief

> If the QT_AUTOBRIEF tag is set to YES then doxygen will interpret the first line (until the first dot) of a Qt-style comment as the brief description. If set to NO, the Qt-style will behave just like regular Qt-style comments (thus requiring an explicit \brief command for a brief description.)
> 
> The default value is: NO.

That could eliminate the need to manually write `\brief` for each entry.

That might be better than using `MULTILINE_CPP_IS_BRIEF`:
https://www.doxygen.nl/manual/config.html#cfg_multiline_cpp_is_brief
> The MULTILINE_CPP_IS_BRIEF tag can be set to YES to make doxygen treat a multi-line C++ special comment block (i.e. a block of //! or /// comments) as a brief description. This used to be the default behavior. The new default is to treat a multi-line C++ comment block as a detailed description. Set this tag to YES if you prefer the old behavior instead.
> Note that setting this tag to YES also means that rational rose comments are not recognized any more.
> 
> The default value is: NO.
>
