### ISSUE TITLE
Update or remove hosted documentation

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#860]
The NAS2D website hosts documentation that appears to be years out of date.

http://nas2d.lairworks.com/nas2d_doc/

This documentation should either be updated or removed, so as to avoid misleading people.

@ldicker83 : I believe you're the only person with access to update that documentation.

----

Longer term, we might look into generating and updating documentation as part of the CI build process. Perhaps builds of the `master` branch (triggered after a merge to `master`) could be used to regenerate and upload documentation. That might be considered a separate issue though.

**Comment by cugone** [comment]
404 Error on the link to the documentation. Soo...is the issue resolved as "removed hosted documentation"?

**Comment by DanRStevens** [comment]
Closing this as I believe @ldicker83 has removed the online copy of the documentation.
