### ISSUE TITLE
Set project code style

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#893]
Set rules for project code style, using a `.clang-format` file, so machine checking and auto formatting can be done with the `clang-format` tool.

----

Documentation:
https://releases.llvm.org/11.0.0/tools/clang/docs/ClangFormatStyleOptions.html (v11)
https://clang.llvm.org/docs/ClangFormatStyleOptions.html (current) (was v13 at time of posting)

----

On Ubuntu 20.04 the default version of `clang-format` is **11.0.0**:
`clang-format --version`
> Ubuntu clang-format version 11.0.0-2~ubuntu20.04.1

This is relevant, since some options listed in the v13 documentation don't work with that version.

**Comment by cugone** [comment]
In the process of doing an editing pass on the documentation a copy-paste operation revealed that the `.clang-format` file is in fact turned on via a "Hey, you have a clang-format file. I'mma use it unless you tell me not to." dialog box.

**Comment by cugone** [comment]
I just checked VS2019 16.10.3's shipped version of clang-format and likewise they've updated the version to 11.0:
```none
C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\Llvm\bin>clang-format.exe -version
clang-format version 11.0.0
```

**Comment by DanRStevens** [comment]
Updated first post with a link to the v11 documentation.
https://releases.llvm.org/11.0.0/tools/clang/docs/ClangFormatStyleOptions.html

Looks very much like we should be targeting v11 based on default support from both Ubuntu and Windows.

**Comment by DanRStevens** [comment]
I've noticed `clang-format` doesn't (yet) support trailing closing braces on a new line. We use that in a number of places for data definitions.

A `clang-format` feature has been proposed for trailing braces on a new line, but seems to be hanging in limbo.

https://stackoverflow.com/questions/52158077/clang-format-closing-bracket-on-a-new-line
https://reviews.llvm.org/D33029

Example code:
```cpp
return {
    static_cast<NewBaseType>(x),
    static_cast<NewBaseType>(y)
};
```

What `clang-format` currently tries to do with it:
```cpp
return {
    static_cast<NewBaseType>(x),
    static_cast<NewBaseType>(y)};
```

**Comment by DanRStevens** [comment]
I came across a couple of projects that will try to analyze project source for style and produce a `.clang-format` file that matches that source as closely as possible:
- [Unformat](https://github.com/johnmcfarlane/unformat)
- [whatstyle](https://github.com/mikr/whatstyle)

Pretty neat idea. Sounds like they can take a while to run though if there is a lot of source code to analyze. Apparently they try various combinations of formatting options and diffs the output to see how many changes are produced. Might be fun to try.

----

Came across another tool that can format C++ code. Not sure how it compares to `clang-format`, though it seems to have quite a large number of options:
- [Uncrustify](https://github.com/uncrustify/uncrustify)

If `clang-format` is not able to represent certain aspects of style, perhaps we can try other tools.

**Comment by DanRStevens** [comment]
Curious, what version of `clang-format` is available now on Windows? I figure it's got to be a new version since we updated the build images for Visual Studio 2022.

For the somewhat recent Ubuntu 22.04 update, we now have:
`clang-format --version`
> Ubuntu clang-format version 14.0.0-1ubuntu1

That should enable us to use some of the options that weren't previously available.

----

Update on `clang-format` feature to support trailing braces on a newline:

The issue [D33029](https://reviews.llvm.org/D33029) was eventually superseded by [D109557](https://reviews.llvm.org/D109557), which was merged. The terminology seems to be a bit different, but the end result is the same.

`AlignAfterOpenBracket: BlockIndent`

This option can be found in the documentation for version 14 (but not version 13):
https://releases.llvm.org/14.0.0/tools/clang/docs/ClangFormatStyleOptions.html
https://releases.llvm.org/13.0.0/tools/clang/docs/ClangFormatStyleOptions.html

**Comment by cugone** [comment]
> Curious, what version of `clang-format` is available now on Windows? I figure it's got to be a new version since we updated the build images for Visual Studio 2022.
> 

Visual Studio 2022 version 17.3.4 (most up-to-date as of this post) uses clang-format version 14.0.5 as determined by the above.
