### ISSUE TITLE
Fix Sprite frame update

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#939]
The `Sprite` frame update code doesn't appear to be as robust as it could be. In particular, it doesn't seem to account for variable `frameDelay` values between frames. It sets a `frame` reference once, before the update loop, and then uses the same `frameDelay` value from that one frame for all advancement. It would be more correct to use the `frameDelay` from each `Frame` being stepped through.

```cpp
const auto& frame = (*mCurrentAction)[mCurrentFrame];

if (!mPaused && !frame.isStopFrame())
{
	while (mTimer.accumulator() >= frame.frameDelay)
	{
		mTimer.adjust_accumulator(frame.frameDelay);
		mCurrentFrame++;
	}

	if (mCurrentFrame >= mCurrentAction->size())
	{
		mCurrentFrame = 0;
		mAnimationCompleteSignal();
	}
}
else if (frame.isStopFrame())
{
	mAnimationCompleteSignal();
}
```

A more correct implementation might look something like:
```cpp
const auto& frames = *mCurrentAction;
unsigned int accumulator = 0;
for (;;)
{
	const auto frame = frames[mCurrentFrame];

	if (frame.isStopFrame() || (timeDelta - accumulator < frame.frameDelay))
	{
		return accumulator;
	}

	accumulator += frame.frameDelay;
	mCurrentFrame++;
	if (mCurrentFrame >= frames.size())
	{
		mCurrentFrame = 0;
		mAnimationCompleteSignal();
	}
}
```

----

We should add unit tests for the `Sprite` code. As `Sprite` depends on `Image`, it may make sense to start there, and prioritize work on #938 first.

Additionally, to make writing unit tests easier, we should provide an alternate constructor for `Sprite`, taking data objects, that would allow a `Sprite` object to be initialized from in-memory data. That would be easier for unit testing than requiring a filename to be specified and loading the data from a file, which would need to be packaged with the unit tests and found within the filesystem.

**Comment by cugone** [comment]
>The Sprite frame update code doesn't appear to be as robust as it could be. In particular, it doesn't seem to account for variable frameDelay values between frames.
> 
For uniformly-sized sprite sheets (say, an [asteroid](https://opengameart.org/content/asteroid-spritesheet), or [multiple game assets](https://opengameart.org/content/64-16x16-food-sprites) (some with a frameDelay of zero, (only one frame), some not), this is standard practice. A single length of time for the entire defined frame indexes of the animation divided up between all the frames. You can then modify the duration at runtime to affect the playback speed.

If the sprite sheet contains differently-sized objects it gets a little more complicated as you'd have to specify their sizes as well as their locations.
