### ISSUE TITLE
Remove loops argument from Mixer fade functions

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#944]
Ref: [#923 comment](https://github.com/lairworks/nas2d-core/pull/923/files#r670116146)

In addition to the referenced comment, it doesn't make sense to loop a simple linear volume change over time.  That is, unless the underlying implementation actually *plays* the music, in that case, the implementation is probably incorrect.

**Comment by cugone** [comment]
The fade loop arguments are specific to and part of the [SDL Mixer API](https://www.libsdl.org/projects/SDL_mixer/docs/SDL_mixer.html#SEC52). Requiring the loop arguments in the base Interface should be re-evaluated.

**Comment by ldicker83** [comment]
I'm not opposed to reconsidering this. We could just remove the loops part of the interface and assume that the user always wants the music to loop. I'm not sure in any of the times that I've used the `playMusic` or f`adeInMusic` interfaces I've ever used anything besides the default values. In the event that there's a point where we don't want it to be continuous we can address that later with a different interface function versus a paramter.

**Comment by cugone** [comment]
Closing as too similar to https://github.com/lairworks/nas2d-core/issues/945
