### ISSUE TITLE
Inconsistency between Mixer and Render fade types

### ISSUE THREAD

**Issue by DanRStevens** [lairworks/nas2d-core#954]
The `Mixer` fade speed is now specified with type `std::chrono::milliseconds`. However the `Renderer` fade methods were not also updated to use this type. This creates awkwardness in downstream OPHD, since it uses the same constant for both `Music` and `Renderer` fades.

We should update these types to match.

**Comment by cugone** [comment]
Patched in #955.

**Comment by DanRStevens** [comment]
Adding reference to #948, #943.
