### ISSUE TITLE
Rename Color to Rgba?

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#956]
While working on #958, I noticed that Color had a comment immediately before it describing its layout:

Color.h:

```cpp

namespace NAS2D
{
	/**
	 * RGBA Color.
	 */
	struct Color
	{
//...
```

Describing the layout as the class name would be better as it forces the user to understand what the layout of the class is simply by using it instead of having to guess and/or try to remember what it is on the fly. Additionally you can explicitly prohibit layouts to not be convertible to each other:

```cpp
Rgba(Argb&) = delete;
Rgba(Brga&) = delete;
```

Suggest an intermediate change for now until it can be changed in all downstream projects:

Color.h:

```cpp

namespace NAS2D
{
    /**
    * RGBA Color.
    */
    struct Color
    {
        //...
    };

    using Rgba = Color;
}
```

**Comment by DanRStevens** [comment]
I'm a bit "meh" on this one. I have no particular plans to support alternative color channel orderings. I kind of don't want the complexity.

@ldicker83 : Do you have any opinion on this one?

**Comment by cugone** [comment]
Also it allows removing the potentially low-value comment in the first place. :)

**Comment by DanRStevens** [comment]
Well, you could remove that comment anyway. The struct definition immediately follows, which makes it obvious what the color components are, and in what order.

**Comment by cugone** [comment]
Not if you aren't looking at it. Re:
>
>...[it] forces the user to understand what the layout of the class is simply by using it instead of having to guess and/or try to remember what it is on the fly...

**Comment by ldicker83** [comment]
I think Color is more natural though you do bring up a good point.

I'm not sure it matters what the layout is. RGBA vs BRGA is irrelevant as that's hidden by the interface (it handles it internally). For now I think leaving it as Color is easier to understand since there are calls like Color::White, Color::Blue, Color::Red, etc. which feels a lot more natural than RGBA::White.

Anyway, the comments could be removed. I sorta went a little crazy with the doxygen documentation.

**Comment by DanRStevens** [comment]
I agree with Leeor that `Color` is more natural. Especially when considering the defined color constants. Besides, RGB(A) is pretty much the most common and expected order.

I think getting specific with `RGBA` versus `BGRA`, or whatever, only really makes sense if you're getting down to bit-depth specific frame buffer code and need to manually deal with different hardware layouts. We generally avoid that in NAS2D.

I think we should just remove the comment and consider that good enough to close this.

**Comment by cugone** [comment]
Okay. :) The comment's been removed.
