### ISSUE TITLE
Move fade operations to shader program?

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#963]
Moving the fade operations to the shader/GPU-side should simplify things greatly on the CPU-side. The code is exactly the same regardless of fading in or out on the CPU and the full screen effect amounts to a single call to `lerp` on the GPU.

CPU-side:
https://github.com/cugone/Roguelike/blob/c8fcc8f029bd4ca0232e9acf05e102f4e4977c75/Roguelike/Code/Game/Game.cpp#L515

GPU-side:
https://github.com/cugone/Roguelike/blob/master/Roguelike/Run_x64/Data/ShaderPrograms/Fullscreen.hlsl

**Comment by DanRStevens** [comment]
It's not clear to me this would significantly simplify things. As it stands now, the fade code draws a semi-transparent rectangle over the screen, which from my understanding, would be done on the GPU.

I'm probably not in a great position to comment much on the graphics code, though what you linked looks more complicated than what we have, and I'm concerned the `*g_theRenderer->GetDeviceContext()` part may be getting into realm of platform specific code, which I would like to avoid.

I should also mention that we're not currently experiencing any sort of performance problem, and for a turn based game, we're not likely to ever hit a graphics performance problem. A graphics performance improvement would need to be weighed against added code complexity, with a strong bias against adding significant code complexity.
