### ISSUE TITLE
Refactor FileSystem internals to use std::filesystem

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#967]
As a stepping stone to moving away from complex string manipulations and towards type-safe and proper error checking with the std::filesystem library, we should refactor the internal and private implementations of `FileSystem` to use `std::filesystem::path` and the manipulation methods therein.

For now, leaving the public API as `std::string` will work as they can just be converted to paths immediately after being passed in and converted back via `std::filesystem::path::string()`.

Downstream code can prepare for the eventual API change by using `std::filesystem::path` variables and passing in a copy of `std::filesystem::path::string()`.

**Comment by DanRStevens** [comment]
I approve of the idea to take a two step approach to the changes.

I've seen some code mix strings and paths, though I can't remember if it was for auto converting or simply for comparison. If `std::string` auto converts to `std::filesystem::path`, then it should be fairly safe to update the API without breaking source compatibility. Binary compatibility is a different matter, though we use static linking with this library, so I'm less concerned about that.

Be aware that functions as currently defined may not perfectly match functionality provided by `std::filesystem::path`. In particular, empty directory components may be inconsistent. Current code might refer to the current working directory as `""`, while `std::filesystem::path` might use `"./"`. This discrepancy may be caught by unit tests.

**Comment by ldicker83** [comment]
Still need to ensure that building on macOS doesn't break using std::filesystem. I'm entirely in favor of this, just super annoyed that Apple lags way behind in adopting new standards even though this standard is over 4 years old now.
