### ISSUE TITLE
Move Vector implementation to Vector2 file

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#975]
This is to disambiguate between `Vector2` and `Vector3` (see #974). `Vector.h` can be repurposed to be include delegates for both until downstream projects update their includes:

Vector.h
```cpp
#include "Vector2.h"
#include "Vector3.h"
```

Vector2.h
```cpp
//Original contents of Vector.h
```

**Comment by DanRStevens** [comment]
I think I desire to not split `Vector` into 2D and 3D versions.

**Comment by ldicker83** [comment]
See my last comment on #974, this isn't really the direction I want to go with NAS2D.
