### ISSUE TITLE
Visual Studio 2022 launches Monday Nov. 8th

### ISSUE THREAD

**Issue by cugone** [lairworks/nas2d-core#993]
Just a heads up, Visual Studio 2022 enters General Availability on Monday November 8th.

https://devblogs.microsoft.com/visualstudio/join-us-november-8th-for-the-launch-of-visual-studio-2022/

**Comment by ldicker83** [comment]
Nice. Looking forward to upgrading.

**Comment by cugone** [comment]
I don't remember if they mentioned it could be installed side-by-side like 2017 and 2019 could. Considering the additions to the core language and full C++20 support, I dunno if I want to and just continue forward with 2022.

Supposedly it's finally a 64-bit application, too!

**Comment by ldicker83** [comment]
I would just replace VS2019. I don't really need or care to have them running side by side. Unlike Xcode visual studio tends to run with the latest core standards. Plus the itellisense has gotten really really good with it's AI learning. Really helped me improve my code for the OphdTechEdit project.

**Comment by cugone** [comment]
I've uninstalled VS2019 and instead installed VS2022. I'm in the process of creating VS2022 versions of my repos.

**Comment by DanRStevens** [comment]
I think this issue can be closed now. It looks like issue #999 contains the action items. This issue was more informative of a pending release date, which has now passed.
